# coding: utf-8

"""
    Gate API

    Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.  # noqa: E501

    Contact: support@mail.gate.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from gate_api.configuration import Configuration


class AIHubPortfolioStopRequest(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'strategy_id': 'str',
        'strategy_type': 'StrategyType'
    }

    attribute_map = {
        'strategy_id': 'strategy_id',
        'strategy_type': 'strategy_type'
    }

    def __init__(self, strategy_id=None, strategy_type=None, local_vars_configuration=None):  # noqa: E501
        # type: (str, StrategyType, Configuration) -> None
        """AIHubPortfolioStopRequest - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._strategy_id = None
        self._strategy_type = None
        self.discriminator = None

        self.strategy_id = strategy_id
        self.strategy_type = strategy_type

    @property
    def strategy_id(self):
        """Gets the strategy_id of this AIHubPortfolioStopRequest.  # noqa: E501


        :return: The strategy_id of this AIHubPortfolioStopRequest.  # noqa: E501
        :rtype: str
        """
        return self._strategy_id

    @strategy_id.setter
    def strategy_id(self, strategy_id):
        """Sets the strategy_id of this AIHubPortfolioStopRequest.


        :param strategy_id: The strategy_id of this AIHubPortfolioStopRequest.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and strategy_id is None:  # noqa: E501
            raise ValueError("Invalid value for `strategy_id`, must not be `None`")  # noqa: E501

        self._strategy_id = strategy_id

    @property
    def strategy_type(self):
        """Gets the strategy_type of this AIHubPortfolioStopRequest.  # noqa: E501


        :return: The strategy_type of this AIHubPortfolioStopRequest.  # noqa: E501
        :rtype: StrategyType
        """
        return self._strategy_type

    @strategy_type.setter
    def strategy_type(self, strategy_type):
        """Sets the strategy_type of this AIHubPortfolioStopRequest.


        :param strategy_type: The strategy_type of this AIHubPortfolioStopRequest.  # noqa: E501
        :type: StrategyType
        """
        if self.local_vars_configuration.client_side_validation and strategy_type is None:  # noqa: E501
            raise ValueError("Invalid value for `strategy_type`, must not be `None`")  # noqa: E501

        self._strategy_type = strategy_type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AIHubPortfolioStopRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, AIHubPortfolioStopRequest):
            return True

        return self.to_dict() != other.to_dict()
