# coding: utf-8

"""
    Gate API

    Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.  # noqa: E501

    Contact: support@mail.gate.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from gate_api.configuration import Configuration


class AIHubPortfolioPosition(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'amount': 'str',
        'entry_price': 'str',
        'quote_amount': 'str',
        'position_value': 'str',
        'margin': 'str',
        'side': 'str'
    }

    attribute_map = {
        'amount': 'amount',
        'entry_price': 'entry_price',
        'quote_amount': 'quote_amount',
        'position_value': 'position_value',
        'margin': 'margin',
        'side': 'side'
    }

    def __init__(self, amount=None, entry_price=None, quote_amount=None, position_value=None, margin=None, side=None, local_vars_configuration=None):  # noqa: E501
        # type: (str, str, str, str, str, str, Configuration) -> None
        """AIHubPortfolioPosition - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._amount = None
        self._entry_price = None
        self._quote_amount = None
        self._position_value = None
        self._margin = None
        self._side = None
        self.discriminator = None

        if amount is not None:
            self.amount = amount
        if entry_price is not None:
            self.entry_price = entry_price
        if quote_amount is not None:
            self.quote_amount = quote_amount
        if position_value is not None:
            self.position_value = position_value
        if margin is not None:
            self.margin = margin
        if side is not None:
            self.side = side

    @property
    def amount(self):
        """Gets the amount of this AIHubPortfolioPosition.  # noqa: E501


        :return: The amount of this AIHubPortfolioPosition.  # noqa: E501
        :rtype: str
        """
        return self._amount

    @amount.setter
    def amount(self, amount):
        """Sets the amount of this AIHubPortfolioPosition.


        :param amount: The amount of this AIHubPortfolioPosition.  # noqa: E501
        :type: str
        """

        self._amount = amount

    @property
    def entry_price(self):
        """Gets the entry_price of this AIHubPortfolioPosition.  # noqa: E501


        :return: The entry_price of this AIHubPortfolioPosition.  # noqa: E501
        :rtype: str
        """
        return self._entry_price

    @entry_price.setter
    def entry_price(self, entry_price):
        """Sets the entry_price of this AIHubPortfolioPosition.


        :param entry_price: The entry_price of this AIHubPortfolioPosition.  # noqa: E501
        :type: str
        """

        self._entry_price = entry_price

    @property
    def quote_amount(self):
        """Gets the quote_amount of this AIHubPortfolioPosition.  # noqa: E501


        :return: The quote_amount of this AIHubPortfolioPosition.  # noqa: E501
        :rtype: str
        """
        return self._quote_amount

    @quote_amount.setter
    def quote_amount(self, quote_amount):
        """Sets the quote_amount of this AIHubPortfolioPosition.


        :param quote_amount: The quote_amount of this AIHubPortfolioPosition.  # noqa: E501
        :type: str
        """

        self._quote_amount = quote_amount

    @property
    def position_value(self):
        """Gets the position_value of this AIHubPortfolioPosition.  # noqa: E501


        :return: The position_value of this AIHubPortfolioPosition.  # noqa: E501
        :rtype: str
        """
        return self._position_value

    @position_value.setter
    def position_value(self, position_value):
        """Sets the position_value of this AIHubPortfolioPosition.


        :param position_value: The position_value of this AIHubPortfolioPosition.  # noqa: E501
        :type: str
        """

        self._position_value = position_value

    @property
    def margin(self):
        """Gets the margin of this AIHubPortfolioPosition.  # noqa: E501


        :return: The margin of this AIHubPortfolioPosition.  # noqa: E501
        :rtype: str
        """
        return self._margin

    @margin.setter
    def margin(self, margin):
        """Sets the margin of this AIHubPortfolioPosition.


        :param margin: The margin of this AIHubPortfolioPosition.  # noqa: E501
        :type: str
        """

        self._margin = margin

    @property
    def side(self):
        """Gets the side of this AIHubPortfolioPosition.  # noqa: E501


        :return: The side of this AIHubPortfolioPosition.  # noqa: E501
        :rtype: str
        """
        return self._side

    @side.setter
    def side(self, side):
        """Sets the side of this AIHubPortfolioPosition.


        :param side: The side of this AIHubPortfolioPosition.  # noqa: E501
        :type: str
        """

        self._side = side

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AIHubPortfolioPosition):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, AIHubPortfolioPosition):
            return True

        return self.to_dict() != other.to_dict()
