# coding: utf-8

"""
    Gate API

    Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.  # noqa: E501

    Contact: support@mail.gate.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from gate_api.configuration import Configuration


class AutoInvestPlanRecordItem(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'int',
        'type': 'str',
        'money': 'str',
        'user_id': 'int',
        'plan_id': 'int',
        'plan_version': 'int',
        'amount': 'str',
        'create_time': 'int',
        'update_time': 'int',
        'status': 'str',
        'status_type': 'int',
        'side': 'int',
        'status_message': 'str',
        'detail': 'str',
        'asset': 'str'
    }

    attribute_map = {
        'id': 'id',
        'type': 'type',
        'money': 'money',
        'user_id': 'user_id',
        'plan_id': 'plan_id',
        'plan_version': 'plan_version',
        'amount': 'amount',
        'create_time': 'create_time',
        'update_time': 'update_time',
        'status': 'status',
        'status_type': 'status_type',
        'side': 'side',
        'status_message': 'status_message',
        'detail': 'detail',
        'asset': 'asset'
    }

    def __init__(self, id=None, type=None, money=None, user_id=None, plan_id=None, plan_version=None, amount=None, create_time=None, update_time=None, status=None, status_type=None, side=None, status_message=None, detail=None, asset=None, local_vars_configuration=None):  # noqa: E501
        # type: (int, str, str, int, int, int, str, int, int, str, int, int, str, str, str, Configuration) -> None
        """AutoInvestPlanRecordItem - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._id = None
        self._type = None
        self._money = None
        self._user_id = None
        self._plan_id = None
        self._plan_version = None
        self._amount = None
        self._create_time = None
        self._update_time = None
        self._status = None
        self._status_type = None
        self._side = None
        self._status_message = None
        self._detail = None
        self._asset = None
        self.discriminator = None

        self.id = id
        self.type = type
        self.money = money
        self.user_id = user_id
        self.plan_id = plan_id
        self.plan_version = plan_version
        self.amount = amount
        self.create_time = create_time
        self.update_time = update_time
        self.status = status
        self.status_type = status_type
        self.side = side
        self.status_message = status_message
        if detail is not None:
            self.detail = detail
        if asset is not None:
            self.asset = asset

    @property
    def id(self):
        """Gets the id of this AutoInvestPlanRecordItem.  # noqa: E501

        Record ID  # noqa: E501

        :return: The id of this AutoInvestPlanRecordItem.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this AutoInvestPlanRecordItem.

        Record ID  # noqa: E501

        :param id: The id of this AutoInvestPlanRecordItem.  # noqa: E501
        :type: int
        """
        if self.local_vars_configuration.client_side_validation and id is None:  # noqa: E501
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def type(self):
        """Gets the type of this AutoInvestPlanRecordItem.  # noqa: E501

        type  # noqa: E501

        :return: The type of this AutoInvestPlanRecordItem.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this AutoInvestPlanRecordItem.

        type  # noqa: E501

        :param type: The type of this AutoInvestPlanRecordItem.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and type is None:  # noqa: E501
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type

    @property
    def money(self):
        """Gets the money of this AutoInvestPlanRecordItem.  # noqa: E501

        SourceCurrency  # noqa: E501

        :return: The money of this AutoInvestPlanRecordItem.  # noqa: E501
        :rtype: str
        """
        return self._money

    @money.setter
    def money(self, money):
        """Sets the money of this AutoInvestPlanRecordItem.

        SourceCurrency  # noqa: E501

        :param money: The money of this AutoInvestPlanRecordItem.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and money is None:  # noqa: E501
            raise ValueError("Invalid value for `money`, must not be `None`")  # noqa: E501

        self._money = money

    @property
    def user_id(self):
        """Gets the user_id of this AutoInvestPlanRecordItem.  # noqa: E501

        User ID  # noqa: E501

        :return: The user_id of this AutoInvestPlanRecordItem.  # noqa: E501
        :rtype: int
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id):
        """Sets the user_id of this AutoInvestPlanRecordItem.

        User ID  # noqa: E501

        :param user_id: The user_id of this AutoInvestPlanRecordItem.  # noqa: E501
        :type: int
        """
        if self.local_vars_configuration.client_side_validation and user_id is None:  # noqa: E501
            raise ValueError("Invalid value for `user_id`, must not be `None`")  # noqa: E501

        self._user_id = user_id

    @property
    def plan_id(self):
        """Gets the plan_id of this AutoInvestPlanRecordItem.  # noqa: E501

        Plan ID  # noqa: E501

        :return: The plan_id of this AutoInvestPlanRecordItem.  # noqa: E501
        :rtype: int
        """
        return self._plan_id

    @plan_id.setter
    def plan_id(self, plan_id):
        """Sets the plan_id of this AutoInvestPlanRecordItem.

        Plan ID  # noqa: E501

        :param plan_id: The plan_id of this AutoInvestPlanRecordItem.  # noqa: E501
        :type: int
        """
        if self.local_vars_configuration.client_side_validation and plan_id is None:  # noqa: E501
            raise ValueError("Invalid value for `plan_id`, must not be `None`")  # noqa: E501

        self._plan_id = plan_id

    @property
    def plan_version(self):
        """Gets the plan_version of this AutoInvestPlanRecordItem.  # noqa: E501

        PlanVersion  # noqa: E501

        :return: The plan_version of this AutoInvestPlanRecordItem.  # noqa: E501
        :rtype: int
        """
        return self._plan_version

    @plan_version.setter
    def plan_version(self, plan_version):
        """Sets the plan_version of this AutoInvestPlanRecordItem.

        PlanVersion  # noqa: E501

        :param plan_version: The plan_version of this AutoInvestPlanRecordItem.  # noqa: E501
        :type: int
        """
        if self.local_vars_configuration.client_side_validation and plan_version is None:  # noqa: E501
            raise ValueError("Invalid value for `plan_version`, must not be `None`")  # noqa: E501

        self._plan_version = plan_version

    @property
    def amount(self):
        """Gets the amount of this AutoInvestPlanRecordItem.  # noqa: E501

        Investment amount  # noqa: E501

        :return: The amount of this AutoInvestPlanRecordItem.  # noqa: E501
        :rtype: str
        """
        return self._amount

    @amount.setter
    def amount(self, amount):
        """Sets the amount of this AutoInvestPlanRecordItem.

        Investment amount  # noqa: E501

        :param amount: The amount of this AutoInvestPlanRecordItem.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and amount is None:  # noqa: E501
            raise ValueError("Invalid value for `amount`, must not be `None`")  # noqa: E501

        self._amount = amount

    @property
    def create_time(self):
        """Gets the create_time of this AutoInvestPlanRecordItem.  # noqa: E501

        Investment time  # noqa: E501

        :return: The create_time of this AutoInvestPlanRecordItem.  # noqa: E501
        :rtype: int
        """
        return self._create_time

    @create_time.setter
    def create_time(self, create_time):
        """Sets the create_time of this AutoInvestPlanRecordItem.

        Investment time  # noqa: E501

        :param create_time: The create_time of this AutoInvestPlanRecordItem.  # noqa: E501
        :type: int
        """
        if self.local_vars_configuration.client_side_validation and create_time is None:  # noqa: E501
            raise ValueError("Invalid value for `create_time`, must not be `None`")  # noqa: E501

        self._create_time = create_time

    @property
    def update_time(self):
        """Gets the update_time of this AutoInvestPlanRecordItem.  # noqa: E501

        Update time  # noqa: E501

        :return: The update_time of this AutoInvestPlanRecordItem.  # noqa: E501
        :rtype: int
        """
        return self._update_time

    @update_time.setter
    def update_time(self, update_time):
        """Sets the update_time of this AutoInvestPlanRecordItem.

        Update time  # noqa: E501

        :param update_time: The update_time of this AutoInvestPlanRecordItem.  # noqa: E501
        :type: int
        """
        if self.local_vars_configuration.client_side_validation and update_time is None:  # noqa: E501
            raise ValueError("Invalid value for `update_time`, must not be `None`")  # noqa: E501

        self._update_time = update_time

    @property
    def status(self):
        """Gets the status of this AutoInvestPlanRecordItem.  # noqa: E501

        Status  # noqa: E501

        :return: The status of this AutoInvestPlanRecordItem.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this AutoInvestPlanRecordItem.

        Status  # noqa: E501

        :param status: The status of this AutoInvestPlanRecordItem.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and status is None:  # noqa: E501
            raise ValueError("Invalid value for `status`, must not be `None`")  # noqa: E501

        self._status = status

    @property
    def status_type(self):
        """Gets the status_type of this AutoInvestPlanRecordItem.  # noqa: E501

        Status enum  # noqa: E501

        :return: The status_type of this AutoInvestPlanRecordItem.  # noqa: E501
        :rtype: int
        """
        return self._status_type

    @status_type.setter
    def status_type(self, status_type):
        """Sets the status_type of this AutoInvestPlanRecordItem.

        Status enum  # noqa: E501

        :param status_type: The status_type of this AutoInvestPlanRecordItem.  # noqa: E501
        :type: int
        """
        if self.local_vars_configuration.client_side_validation and status_type is None:  # noqa: E501
            raise ValueError("Invalid value for `status_type`, must not be `None`")  # noqa: E501

        self._status_type = status_type

    @property
    def side(self):
        """Gets the side of this AutoInvestPlanRecordItem.  # noqa: E501

        2 = Buy, Other = Sell  # noqa: E501

        :return: The side of this AutoInvestPlanRecordItem.  # noqa: E501
        :rtype: int
        """
        return self._side

    @side.setter
    def side(self, side):
        """Sets the side of this AutoInvestPlanRecordItem.

        2 = Buy, Other = Sell  # noqa: E501

        :param side: The side of this AutoInvestPlanRecordItem.  # noqa: E501
        :type: int
        """
        if self.local_vars_configuration.client_side_validation and side is None:  # noqa: E501
            raise ValueError("Invalid value for `side`, must not be `None`")  # noqa: E501

        self._side = side

    @property
    def status_message(self):
        """Gets the status_message of this AutoInvestPlanRecordItem.  # noqa: E501

        Status description  # noqa: E501

        :return: The status_message of this AutoInvestPlanRecordItem.  # noqa: E501
        :rtype: str
        """
        return self._status_message

    @status_message.setter
    def status_message(self, status_message):
        """Sets the status_message of this AutoInvestPlanRecordItem.

        Status description  # noqa: E501

        :param status_message: The status_message of this AutoInvestPlanRecordItem.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and status_message is None:  # noqa: E501
            raise ValueError("Invalid value for `status_message`, must not be `None`")  # noqa: E501

        self._status_message = status_message

    @property
    def detail(self):
        """Gets the detail of this AutoInvestPlanRecordItem.  # noqa: E501

        Details  # noqa: E501

        :return: The detail of this AutoInvestPlanRecordItem.  # noqa: E501
        :rtype: str
        """
        return self._detail

    @detail.setter
    def detail(self, detail):
        """Sets the detail of this AutoInvestPlanRecordItem.

        Details  # noqa: E501

        :param detail: The detail of this AutoInvestPlanRecordItem.  # noqa: E501
        :type: str
        """

        self._detail = detail

    @property
    def asset(self):
        """Gets the asset of this AutoInvestPlanRecordItem.  # noqa: E501

        Currency  # noqa: E501

        :return: The asset of this AutoInvestPlanRecordItem.  # noqa: E501
        :rtype: str
        """
        return self._asset

    @asset.setter
    def asset(self, asset):
        """Sets the asset of this AutoInvestPlanRecordItem.

        Currency  # noqa: E501

        :param asset: The asset of this AutoInvestPlanRecordItem.  # noqa: E501
        :type: str
        """

        self._asset = asset

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AutoInvestPlanRecordItem):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, AutoInvestPlanRecordItem):
            return True

        return self.to_dict() != other.to_dict()
