# coding: utf-8

"""
    Gate API

    Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.  # noqa: E501

    Contact: support@mail.gate.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from gate_api.configuration import Configuration


class AutoInvestPlanUpdate(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'plan_id': 'int',
        'fund_source': 'str',
        'fund_flow': 'str'
    }

    attribute_map = {
        'plan_id': 'plan_id',
        'fund_source': 'fund_source',
        'fund_flow': 'fund_flow'
    }

    def __init__(self, plan_id=None, fund_source=None, fund_flow=None, local_vars_configuration=None):  # noqa: E501
        # type: (int, str, str, Configuration) -> None
        """AutoInvestPlanUpdate - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._plan_id = None
        self._fund_source = None
        self._fund_flow = None
        self.discriminator = None

        self.plan_id = plan_id
        if fund_source is not None:
            self.fund_source = fund_source
        if fund_flow is not None:
            self.fund_flow = fund_flow

    @property
    def plan_id(self):
        """Gets the plan_id of this AutoInvestPlanUpdate.  # noqa: E501

        Plan ID  # noqa: E501

        :return: The plan_id of this AutoInvestPlanUpdate.  # noqa: E501
        :rtype: int
        """
        return self._plan_id

    @plan_id.setter
    def plan_id(self, plan_id):
        """Sets the plan_id of this AutoInvestPlanUpdate.

        Plan ID  # noqa: E501

        :param plan_id: The plan_id of this AutoInvestPlanUpdate.  # noqa: E501
        :type: int
        """
        if self.local_vars_configuration.client_side_validation and plan_id is None:  # noqa: E501
            raise ValueError("Invalid value for `plan_id`, must not be `None`")  # noqa: E501

        self._plan_id = plan_id

    @property
    def fund_source(self):
        """Gets the fund_source of this AutoInvestPlanUpdate.  # noqa: E501

        Fund source Spotspot or Flexible Savingsearn，Default spot  # noqa: E501

        :return: The fund_source of this AutoInvestPlanUpdate.  # noqa: E501
        :rtype: str
        """
        return self._fund_source

    @fund_source.setter
    def fund_source(self, fund_source):
        """Sets the fund_source of this AutoInvestPlanUpdate.

        Fund source Spotspot or Flexible Savingsearn，Default spot  # noqa: E501

        :param fund_source: The fund_source of this AutoInvestPlanUpdate.  # noqa: E501
        :type: str
        """

        self._fund_source = fund_source

    @property
    def fund_flow(self):
        """Gets the fund_flow of this AutoInvestPlanUpdate.  # noqa: E501

        Fund Flow Direction Spotauto_invest or Flexible Savingsearn，Default auto_invest  # noqa: E501

        :return: The fund_flow of this AutoInvestPlanUpdate.  # noqa: E501
        :rtype: str
        """
        return self._fund_flow

    @fund_flow.setter
    def fund_flow(self, fund_flow):
        """Sets the fund_flow of this AutoInvestPlanUpdate.

        Fund Flow Direction Spotauto_invest or Flexible Savingsearn，Default auto_invest  # noqa: E501

        :param fund_flow: The fund_flow of this AutoInvestPlanUpdate.  # noqa: E501
        :type: str
        """

        self._fund_flow = fund_flow

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AutoInvestPlanUpdate):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, AutoInvestPlanUpdate):
            return True

        return self.to_dict() != other.to_dict()
