# coding: utf-8

"""
    Gate API

    Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.  # noqa: E501

    Contact: support@mail.gate.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from gate_api.configuration import Configuration


class ChaseOrder(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'str',
        'user': 'str',
        'contract': 'str',
        'settle': 'str',
        'amount': 'str',
        'price_limit': 'str',
        'reduce_only': 'bool',
        'text': 'str',
        'create_time': 'int',
        'finish_time': 'int',
        'original_status': 'int',
        'status': 'str',
        'reason': 'str',
        'fill_amount': 'str',
        'average_fill_price': 'str',
        'suborder_id': 'str',
        'is_dual_mode': 'bool',
        'side_label': 'str',
        'position_side_output': 'str',
        'chase_price': 'str',
        'interval_sec': 'int',
        'updated_at': 'int',
        'suborder_price': 'str',
        'suborder_ongoing': 'bool',
        'suborder_finish_as': 'str',
        'price_type': 'int',
        'price_gap_type': 'str',
        'price_gap_value': 'str',
        'status_code': 'str',
        'create_time_precise': 'str',
        'finish_time_precise': 'str',
        'pos_margin_mode': 'str',
        'position_mode': 'str',
        'leverage': 'str',
        'error_label': 'str'
    }

    attribute_map = {
        'id': 'id',
        'user': 'user',
        'contract': 'contract',
        'settle': 'settle',
        'amount': 'amount',
        'price_limit': 'price_limit',
        'reduce_only': 'reduce_only',
        'text': 'text',
        'create_time': 'create_time',
        'finish_time': 'finish_time',
        'original_status': 'original_status',
        'status': 'status',
        'reason': 'reason',
        'fill_amount': 'fill_amount',
        'average_fill_price': 'average_fill_price',
        'suborder_id': 'suborder_id',
        'is_dual_mode': 'is_dual_mode',
        'side_label': 'side_label',
        'position_side_output': 'position_side_output',
        'chase_price': 'chase_price',
        'interval_sec': 'interval_sec',
        'updated_at': 'updated_at',
        'suborder_price': 'suborder_price',
        'suborder_ongoing': 'suborder_ongoing',
        'suborder_finish_as': 'suborder_finish_as',
        'price_type': 'price_type',
        'price_gap_type': 'price_gap_type',
        'price_gap_value': 'price_gap_value',
        'status_code': 'status_code',
        'create_time_precise': 'create_time_precise',
        'finish_time_precise': 'finish_time_precise',
        'pos_margin_mode': 'pos_margin_mode',
        'position_mode': 'position_mode',
        'leverage': 'leverage',
        'error_label': 'error_label'
    }

    def __init__(self, id=None, user=None, contract=None, settle=None, amount=None, price_limit=None, reduce_only=None, text=None, create_time=None, finish_time=None, original_status=None, status=None, reason=None, fill_amount=None, average_fill_price=None, suborder_id=None, is_dual_mode=None, side_label=None, position_side_output=None, chase_price=None, interval_sec=None, updated_at=None, suborder_price=None, suborder_ongoing=None, suborder_finish_as=None, price_type=None, price_gap_type=None, price_gap_value=None, status_code=None, create_time_precise=None, finish_time_precise=None, pos_margin_mode=None, position_mode=None, leverage=None, error_label=None, local_vars_configuration=None):  # noqa: E501
        # type: (str, str, str, str, str, str, bool, str, int, int, int, str, str, str, str, str, bool, str, str, str, int, int, str, bool, str, int, str, str, str, str, str, str, str, str, str, Configuration) -> None
        """ChaseOrder - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._id = None
        self._user = None
        self._contract = None
        self._settle = None
        self._amount = None
        self._price_limit = None
        self._reduce_only = None
        self._text = None
        self._create_time = None
        self._finish_time = None
        self._original_status = None
        self._status = None
        self._reason = None
        self._fill_amount = None
        self._average_fill_price = None
        self._suborder_id = None
        self._is_dual_mode = None
        self._side_label = None
        self._position_side_output = None
        self._chase_price = None
        self._interval_sec = None
        self._updated_at = None
        self._suborder_price = None
        self._suborder_ongoing = None
        self._suborder_finish_as = None
        self._price_type = None
        self._price_gap_type = None
        self._price_gap_value = None
        self._status_code = None
        self._create_time_precise = None
        self._finish_time_precise = None
        self._pos_margin_mode = None
        self._position_mode = None
        self._leverage = None
        self._error_label = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if user is not None:
            self.user = user
        if contract is not None:
            self.contract = contract
        if settle is not None:
            self.settle = settle
        if amount is not None:
            self.amount = amount
        if price_limit is not None:
            self.price_limit = price_limit
        if reduce_only is not None:
            self.reduce_only = reduce_only
        if text is not None:
            self.text = text
        if create_time is not None:
            self.create_time = create_time
        if finish_time is not None:
            self.finish_time = finish_time
        if original_status is not None:
            self.original_status = original_status
        if status is not None:
            self.status = status
        if reason is not None:
            self.reason = reason
        if fill_amount is not None:
            self.fill_amount = fill_amount
        if average_fill_price is not None:
            self.average_fill_price = average_fill_price
        if suborder_id is not None:
            self.suborder_id = suborder_id
        if is_dual_mode is not None:
            self.is_dual_mode = is_dual_mode
        if side_label is not None:
            self.side_label = side_label
        if position_side_output is not None:
            self.position_side_output = position_side_output
        if chase_price is not None:
            self.chase_price = chase_price
        if interval_sec is not None:
            self.interval_sec = interval_sec
        if updated_at is not None:
            self.updated_at = updated_at
        if suborder_price is not None:
            self.suborder_price = suborder_price
        if suborder_ongoing is not None:
            self.suborder_ongoing = suborder_ongoing
        if suborder_finish_as is not None:
            self.suborder_finish_as = suborder_finish_as
        if price_type is not None:
            self.price_type = price_type
        if price_gap_type is not None:
            self.price_gap_type = price_gap_type
        if price_gap_value is not None:
            self.price_gap_value = price_gap_value
        if status_code is not None:
            self.status_code = status_code
        if create_time_precise is not None:
            self.create_time_precise = create_time_precise
        if finish_time_precise is not None:
            self.finish_time_precise = finish_time_precise
        if pos_margin_mode is not None:
            self.pos_margin_mode = pos_margin_mode
        if position_mode is not None:
            self.position_mode = position_mode
        if leverage is not None:
            self.leverage = leverage
        if error_label is not None:
            self.error_label = error_label

    @property
    def id(self):
        """Gets the id of this ChaseOrder.  # noqa: E501


        :return: The id of this ChaseOrder.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ChaseOrder.


        :param id: The id of this ChaseOrder.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def user(self):
        """Gets the user of this ChaseOrder.  # noqa: E501


        :return: The user of this ChaseOrder.  # noqa: E501
        :rtype: str
        """
        return self._user

    @user.setter
    def user(self, user):
        """Sets the user of this ChaseOrder.


        :param user: The user of this ChaseOrder.  # noqa: E501
        :type: str
        """

        self._user = user

    @property
    def contract(self):
        """Gets the contract of this ChaseOrder.  # noqa: E501


        :return: The contract of this ChaseOrder.  # noqa: E501
        :rtype: str
        """
        return self._contract

    @contract.setter
    def contract(self, contract):
        """Sets the contract of this ChaseOrder.


        :param contract: The contract of this ChaseOrder.  # noqa: E501
        :type: str
        """

        self._contract = contract

    @property
    def settle(self):
        """Gets the settle of this ChaseOrder.  # noqa: E501


        :return: The settle of this ChaseOrder.  # noqa: E501
        :rtype: str
        """
        return self._settle

    @settle.setter
    def settle(self, settle):
        """Sets the settle of this ChaseOrder.


        :param settle: The settle of this ChaseOrder.  # noqa: E501
        :type: str
        """

        self._settle = settle

    @property
    def amount(self):
        """Gets the amount of this ChaseOrder.  # noqa: E501

        Total size in contracts; positive for buy, negative for sell  # noqa: E501

        :return: The amount of this ChaseOrder.  # noqa: E501
        :rtype: str
        """
        return self._amount

    @amount.setter
    def amount(self, amount):
        """Sets the amount of this ChaseOrder.

        Total size in contracts; positive for buy, negative for sell  # noqa: E501

        :param amount: The amount of this ChaseOrder.  # noqa: E501
        :type: str
        """

        self._amount = amount

    @property
    def price_limit(self):
        """Gets the price_limit of this ChaseOrder.  # noqa: E501


        :return: The price_limit of this ChaseOrder.  # noqa: E501
        :rtype: str
        """
        return self._price_limit

    @price_limit.setter
    def price_limit(self, price_limit):
        """Sets the price_limit of this ChaseOrder.


        :param price_limit: The price_limit of this ChaseOrder.  # noqa: E501
        :type: str
        """

        self._price_limit = price_limit

    @property
    def reduce_only(self):
        """Gets the reduce_only of this ChaseOrder.  # noqa: E501


        :return: The reduce_only of this ChaseOrder.  # noqa: E501
        :rtype: bool
        """
        return self._reduce_only

    @reduce_only.setter
    def reduce_only(self, reduce_only):
        """Sets the reduce_only of this ChaseOrder.


        :param reduce_only: The reduce_only of this ChaseOrder.  # noqa: E501
        :type: bool
        """

        self._reduce_only = reduce_only

    @property
    def text(self):
        """Gets the text of this ChaseOrder.  # noqa: E501


        :return: The text of this ChaseOrder.  # noqa: E501
        :rtype: str
        """
        return self._text

    @text.setter
    def text(self, text):
        """Sets the text of this ChaseOrder.


        :param text: The text of this ChaseOrder.  # noqa: E501
        :type: str
        """

        self._text = text

    @property
    def create_time(self):
        """Gets the create_time of this ChaseOrder.  # noqa: E501


        :return: The create_time of this ChaseOrder.  # noqa: E501
        :rtype: int
        """
        return self._create_time

    @create_time.setter
    def create_time(self, create_time):
        """Sets the create_time of this ChaseOrder.


        :param create_time: The create_time of this ChaseOrder.  # noqa: E501
        :type: int
        """

        self._create_time = create_time

    @property
    def finish_time(self):
        """Gets the finish_time of this ChaseOrder.  # noqa: E501


        :return: The finish_time of this ChaseOrder.  # noqa: E501
        :rtype: int
        """
        return self._finish_time

    @finish_time.setter
    def finish_time(self, finish_time):
        """Sets the finish_time of this ChaseOrder.


        :param finish_time: The finish_time of this ChaseOrder.  # noqa: E501
        :type: int
        """

        self._finish_time = finish_time

    @property
    def original_status(self):
        """Gets the original_status of this ChaseOrder.  # noqa: E501

        Raw status enum  # noqa: E501

        :return: The original_status of this ChaseOrder.  # noqa: E501
        :rtype: int
        """
        return self._original_status

    @original_status.setter
    def original_status(self, original_status):
        """Sets the original_status of this ChaseOrder.

        Raw status enum  # noqa: E501

        :param original_status: The original_status of this ChaseOrder.  # noqa: E501
        :type: int
        """

        self._original_status = original_status

    @property
    def status(self):
        """Gets the status of this ChaseOrder.  # noqa: E501

        Simplified status, e.g. open / finished  # noqa: E501

        :return: The status of this ChaseOrder.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this ChaseOrder.

        Simplified status, e.g. open / finished  # noqa: E501

        :param status: The status of this ChaseOrder.  # noqa: E501
        :type: str
        """

        self._status = status

    @property
    def reason(self):
        """Gets the reason of this ChaseOrder.  # noqa: E501


        :return: The reason of this ChaseOrder.  # noqa: E501
        :rtype: str
        """
        return self._reason

    @reason.setter
    def reason(self, reason):
        """Sets the reason of this ChaseOrder.


        :param reason: The reason of this ChaseOrder.  # noqa: E501
        :type: str
        """

        self._reason = reason

    @property
    def fill_amount(self):
        """Gets the fill_amount of this ChaseOrder.  # noqa: E501


        :return: The fill_amount of this ChaseOrder.  # noqa: E501
        :rtype: str
        """
        return self._fill_amount

    @fill_amount.setter
    def fill_amount(self, fill_amount):
        """Sets the fill_amount of this ChaseOrder.


        :param fill_amount: The fill_amount of this ChaseOrder.  # noqa: E501
        :type: str
        """

        self._fill_amount = fill_amount

    @property
    def average_fill_price(self):
        """Gets the average_fill_price of this ChaseOrder.  # noqa: E501


        :return: The average_fill_price of this ChaseOrder.  # noqa: E501
        :rtype: str
        """
        return self._average_fill_price

    @average_fill_price.setter
    def average_fill_price(self, average_fill_price):
        """Sets the average_fill_price of this ChaseOrder.


        :param average_fill_price: The average_fill_price of this ChaseOrder.  # noqa: E501
        :type: str
        """

        self._average_fill_price = average_fill_price

    @property
    def suborder_id(self):
        """Gets the suborder_id of this ChaseOrder.  # noqa: E501


        :return: The suborder_id of this ChaseOrder.  # noqa: E501
        :rtype: str
        """
        return self._suborder_id

    @suborder_id.setter
    def suborder_id(self, suborder_id):
        """Sets the suborder_id of this ChaseOrder.


        :param suborder_id: The suborder_id of this ChaseOrder.  # noqa: E501
        :type: str
        """

        self._suborder_id = suborder_id

    @property
    def is_dual_mode(self):
        """Gets the is_dual_mode of this ChaseOrder.  # noqa: E501


        :return: The is_dual_mode of this ChaseOrder.  # noqa: E501
        :rtype: bool
        """
        return self._is_dual_mode

    @is_dual_mode.setter
    def is_dual_mode(self, is_dual_mode):
        """Sets the is_dual_mode of this ChaseOrder.


        :param is_dual_mode: The is_dual_mode of this ChaseOrder.  # noqa: E501
        :type: bool
        """

        self._is_dual_mode = is_dual_mode

    @property
    def side_label(self):
        """Gets the side_label of this ChaseOrder.  # noqa: E501


        :return: The side_label of this ChaseOrder.  # noqa: E501
        :rtype: str
        """
        return self._side_label

    @side_label.setter
    def side_label(self, side_label):
        """Sets the side_label of this ChaseOrder.


        :param side_label: The side_label of this ChaseOrder.  # noqa: E501
        :type: str
        """

        self._side_label = side_label

    @property
    def position_side_output(self):
        """Gets the position_side_output of this ChaseOrder.  # noqa: E501


        :return: The position_side_output of this ChaseOrder.  # noqa: E501
        :rtype: str
        """
        return self._position_side_output

    @position_side_output.setter
    def position_side_output(self, position_side_output):
        """Sets the position_side_output of this ChaseOrder.


        :param position_side_output: The position_side_output of this ChaseOrder.  # noqa: E501
        :type: str
        """

        self._position_side_output = position_side_output

    @property
    def chase_price(self):
        """Gets the chase_price of this ChaseOrder.  # noqa: E501


        :return: The chase_price of this ChaseOrder.  # noqa: E501
        :rtype: str
        """
        return self._chase_price

    @chase_price.setter
    def chase_price(self, chase_price):
        """Sets the chase_price of this ChaseOrder.


        :param chase_price: The chase_price of this ChaseOrder.  # noqa: E501
        :type: str
        """

        self._chase_price = chase_price

    @property
    def interval_sec(self):
        """Gets the interval_sec of this ChaseOrder.  # noqa: E501


        :return: The interval_sec of this ChaseOrder.  # noqa: E501
        :rtype: int
        """
        return self._interval_sec

    @interval_sec.setter
    def interval_sec(self, interval_sec):
        """Sets the interval_sec of this ChaseOrder.


        :param interval_sec: The interval_sec of this ChaseOrder.  # noqa: E501
        :type: int
        """

        self._interval_sec = interval_sec

    @property
    def updated_at(self):
        """Gets the updated_at of this ChaseOrder.  # noqa: E501


        :return: The updated_at of this ChaseOrder.  # noqa: E501
        :rtype: int
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at):
        """Sets the updated_at of this ChaseOrder.


        :param updated_at: The updated_at of this ChaseOrder.  # noqa: E501
        :type: int
        """

        self._updated_at = updated_at

    @property
    def suborder_price(self):
        """Gets the suborder_price of this ChaseOrder.  # noqa: E501


        :return: The suborder_price of this ChaseOrder.  # noqa: E501
        :rtype: str
        """
        return self._suborder_price

    @suborder_price.setter
    def suborder_price(self, suborder_price):
        """Sets the suborder_price of this ChaseOrder.


        :param suborder_price: The suborder_price of this ChaseOrder.  # noqa: E501
        :type: str
        """

        self._suborder_price = suborder_price

    @property
    def suborder_ongoing(self):
        """Gets the suborder_ongoing of this ChaseOrder.  # noqa: E501


        :return: The suborder_ongoing of this ChaseOrder.  # noqa: E501
        :rtype: bool
        """
        return self._suborder_ongoing

    @suborder_ongoing.setter
    def suborder_ongoing(self, suborder_ongoing):
        """Sets the suborder_ongoing of this ChaseOrder.


        :param suborder_ongoing: The suborder_ongoing of this ChaseOrder.  # noqa: E501
        :type: bool
        """

        self._suborder_ongoing = suborder_ongoing

    @property
    def suborder_finish_as(self):
        """Gets the suborder_finish_as of this ChaseOrder.  # noqa: E501


        :return: The suborder_finish_as of this ChaseOrder.  # noqa: E501
        :rtype: str
        """
        return self._suborder_finish_as

    @suborder_finish_as.setter
    def suborder_finish_as(self, suborder_finish_as):
        """Sets the suborder_finish_as of this ChaseOrder.


        :param suborder_finish_as: The suborder_finish_as of this ChaseOrder.  # noqa: E501
        :type: str
        """

        self._suborder_finish_as = suborder_finish_as

    @property
    def price_type(self):
        """Gets the price_type of this ChaseOrder.  # noqa: E501

        PriceType enum: 1 latest, 2 index, 3 mark  # noqa: E501

        :return: The price_type of this ChaseOrder.  # noqa: E501
        :rtype: int
        """
        return self._price_type

    @price_type.setter
    def price_type(self, price_type):
        """Sets the price_type of this ChaseOrder.

        PriceType enum: 1 latest, 2 index, 3 mark  # noqa: E501

        :param price_type: The price_type of this ChaseOrder.  # noqa: E501
        :type: int
        """

        self._price_type = price_type

    @property
    def price_gap_type(self):
        """Gets the price_gap_type of this ChaseOrder.  # noqa: E501


        :return: The price_gap_type of this ChaseOrder.  # noqa: E501
        :rtype: str
        """
        return self._price_gap_type

    @price_gap_type.setter
    def price_gap_type(self, price_gap_type):
        """Sets the price_gap_type of this ChaseOrder.


        :param price_gap_type: The price_gap_type of this ChaseOrder.  # noqa: E501
        :type: str
        """

        self._price_gap_type = price_gap_type

    @property
    def price_gap_value(self):
        """Gets the price_gap_value of this ChaseOrder.  # noqa: E501


        :return: The price_gap_value of this ChaseOrder.  # noqa: E501
        :rtype: str
        """
        return self._price_gap_value

    @price_gap_value.setter
    def price_gap_value(self, price_gap_value):
        """Sets the price_gap_value of this ChaseOrder.


        :param price_gap_value: The price_gap_value of this ChaseOrder.  # noqa: E501
        :type: str
        """

        self._price_gap_value = price_gap_value

    @property
    def status_code(self):
        """Gets the status_code of this ChaseOrder.  # noqa: E501


        :return: The status_code of this ChaseOrder.  # noqa: E501
        :rtype: str
        """
        return self._status_code

    @status_code.setter
    def status_code(self, status_code):
        """Sets the status_code of this ChaseOrder.


        :param status_code: The status_code of this ChaseOrder.  # noqa: E501
        :type: str
        """

        self._status_code = status_code

    @property
    def create_time_precise(self):
        """Gets the create_time_precise of this ChaseOrder.  # noqa: E501

        Creation time (seconds.microseconds)  # noqa: E501

        :return: The create_time_precise of this ChaseOrder.  # noqa: E501
        :rtype: str
        """
        return self._create_time_precise

    @create_time_precise.setter
    def create_time_precise(self, create_time_precise):
        """Sets the create_time_precise of this ChaseOrder.

        Creation time (seconds.microseconds)  # noqa: E501

        :param create_time_precise: The create_time_precise of this ChaseOrder.  # noqa: E501
        :type: str
        """

        self._create_time_precise = create_time_precise

    @property
    def finish_time_precise(self):
        """Gets the finish_time_precise of this ChaseOrder.  # noqa: E501


        :return: The finish_time_precise of this ChaseOrder.  # noqa: E501
        :rtype: str
        """
        return self._finish_time_precise

    @finish_time_precise.setter
    def finish_time_precise(self, finish_time_precise):
        """Sets the finish_time_precise of this ChaseOrder.


        :param finish_time_precise: The finish_time_precise of this ChaseOrder.  # noqa: E501
        :type: str
        """

        self._finish_time_precise = finish_time_precise

    @property
    def pos_margin_mode(self):
        """Gets the pos_margin_mode of this ChaseOrder.  # noqa: E501


        :return: The pos_margin_mode of this ChaseOrder.  # noqa: E501
        :rtype: str
        """
        return self._pos_margin_mode

    @pos_margin_mode.setter
    def pos_margin_mode(self, pos_margin_mode):
        """Sets the pos_margin_mode of this ChaseOrder.


        :param pos_margin_mode: The pos_margin_mode of this ChaseOrder.  # noqa: E501
        :type: str
        """

        self._pos_margin_mode = pos_margin_mode

    @property
    def position_mode(self):
        """Gets the position_mode of this ChaseOrder.  # noqa: E501


        :return: The position_mode of this ChaseOrder.  # noqa: E501
        :rtype: str
        """
        return self._position_mode

    @position_mode.setter
    def position_mode(self, position_mode):
        """Sets the position_mode of this ChaseOrder.


        :param position_mode: The position_mode of this ChaseOrder.  # noqa: E501
        :type: str
        """

        self._position_mode = position_mode

    @property
    def leverage(self):
        """Gets the leverage of this ChaseOrder.  # noqa: E501


        :return: The leverage of this ChaseOrder.  # noqa: E501
        :rtype: str
        """
        return self._leverage

    @leverage.setter
    def leverage(self, leverage):
        """Sets the leverage of this ChaseOrder.


        :param leverage: The leverage of this ChaseOrder.  # noqa: E501
        :type: str
        """

        self._leverage = leverage

    @property
    def error_label(self):
        """Gets the error_label of this ChaseOrder.  # noqa: E501


        :return: The error_label of this ChaseOrder.  # noqa: E501
        :rtype: str
        """
        return self._error_label

    @error_label.setter
    def error_label(self, error_label):
        """Sets the error_label of this ChaseOrder.


        :param error_label: The error_label of this ChaseOrder.  # noqa: E501
        :type: str
        """

        self._error_label = error_label

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ChaseOrder):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ChaseOrder):
            return True

        return self.to_dict() != other.to_dict()
