# coding: utf-8

"""
    Gate API

    Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.  # noqa: E501

    Contact: support@mail.gate.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from gate_api.configuration import Configuration


class DualOrderRefundPreview(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'create_timest': 'int',
        'delivery_timest': 'int',
        'exercise_price': 'str',
        'invest_amount': 'str',
        'invest_currency': 'str',
        'name': 'str',
        'order_id': 'int',
        'req_id': 'str',
        'refund_service_charge': 'int',
        'settle_price': 'str',
        'settlement_amount': 'str',
        'settlement_currency': 'str',
        'settlement_interest': 'str',
        'settlement_principle': 'str',
        'type': 'str',
        'money_back_timest': 'int'
    }

    attribute_map = {
        'create_timest': 'create_timest',
        'delivery_timest': 'delivery_timest',
        'exercise_price': 'exercise_price',
        'invest_amount': 'invest_amount',
        'invest_currency': 'invest_currency',
        'name': 'name',
        'order_id': 'order_id',
        'req_id': 'req_id',
        'refund_service_charge': 'refund_service_charge',
        'settle_price': 'settle_price',
        'settlement_amount': 'settlement_amount',
        'settlement_currency': 'settlement_currency',
        'settlement_interest': 'settlement_interest',
        'settlement_principle': 'settlement_principle',
        'type': 'type',
        'money_back_timest': 'money_back_timest'
    }

    def __init__(self, create_timest=None, delivery_timest=None, exercise_price=None, invest_amount=None, invest_currency=None, name=None, order_id=None, req_id=None, refund_service_charge=None, settle_price=None, settlement_amount=None, settlement_currency=None, settlement_interest=None, settlement_principle=None, type=None, money_back_timest=None, local_vars_configuration=None):  # noqa: E501
        # type: (int, int, str, str, str, str, int, str, int, str, str, str, str, str, str, int, Configuration) -> None
        """DualOrderRefundPreview - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._create_timest = None
        self._delivery_timest = None
        self._exercise_price = None
        self._invest_amount = None
        self._invest_currency = None
        self._name = None
        self._order_id = None
        self._req_id = None
        self._refund_service_charge = None
        self._settle_price = None
        self._settlement_amount = None
        self._settlement_currency = None
        self._settlement_interest = None
        self._settlement_principle = None
        self._type = None
        self._money_back_timest = None
        self.discriminator = None

        if create_timest is not None:
            self.create_timest = create_timest
        if delivery_timest is not None:
            self.delivery_timest = delivery_timest
        if exercise_price is not None:
            self.exercise_price = exercise_price
        if invest_amount is not None:
            self.invest_amount = invest_amount
        if invest_currency is not None:
            self.invest_currency = invest_currency
        if name is not None:
            self.name = name
        if order_id is not None:
            self.order_id = order_id
        if req_id is not None:
            self.req_id = req_id
        if refund_service_charge is not None:
            self.refund_service_charge = refund_service_charge
        if settle_price is not None:
            self.settle_price = settle_price
        if settlement_amount is not None:
            self.settlement_amount = settlement_amount
        if settlement_currency is not None:
            self.settlement_currency = settlement_currency
        if settlement_interest is not None:
            self.settlement_interest = settlement_interest
        if settlement_principle is not None:
            self.settlement_principle = settlement_principle
        if type is not None:
            self.type = type
        if money_back_timest is not None:
            self.money_back_timest = money_back_timest

    @property
    def create_timest(self):
        """Gets the create_timest of this DualOrderRefundPreview.  # noqa: E501

        Order creation timestamp  # noqa: E501

        :return: The create_timest of this DualOrderRefundPreview.  # noqa: E501
        :rtype: int
        """
        return self._create_timest

    @create_timest.setter
    def create_timest(self, create_timest):
        """Sets the create_timest of this DualOrderRefundPreview.

        Order creation timestamp  # noqa: E501

        :param create_timest: The create_timest of this DualOrderRefundPreview.  # noqa: E501
        :type: int
        """

        self._create_timest = create_timest

    @property
    def delivery_timest(self):
        """Gets the delivery_timest of this DualOrderRefundPreview.  # noqa: E501

        Order delivery timestamp  # noqa: E501

        :return: The delivery_timest of this DualOrderRefundPreview.  # noqa: E501
        :rtype: int
        """
        return self._delivery_timest

    @delivery_timest.setter
    def delivery_timest(self, delivery_timest):
        """Sets the delivery_timest of this DualOrderRefundPreview.

        Order delivery timestamp  # noqa: E501

        :param delivery_timest: The delivery_timest of this DualOrderRefundPreview.  # noqa: E501
        :type: int
        """

        self._delivery_timest = delivery_timest

    @property
    def exercise_price(self):
        """Gets the exercise_price of this DualOrderRefundPreview.  # noqa: E501

        Strike price  # noqa: E501

        :return: The exercise_price of this DualOrderRefundPreview.  # noqa: E501
        :rtype: str
        """
        return self._exercise_price

    @exercise_price.setter
    def exercise_price(self, exercise_price):
        """Sets the exercise_price of this DualOrderRefundPreview.

        Strike price  # noqa: E501

        :param exercise_price: The exercise_price of this DualOrderRefundPreview.  # noqa: E501
        :type: str
        """

        self._exercise_price = exercise_price

    @property
    def invest_amount(self):
        """Gets the invest_amount of this DualOrderRefundPreview.  # noqa: E501

        Investment amount  # noqa: E501

        :return: The invest_amount of this DualOrderRefundPreview.  # noqa: E501
        :rtype: str
        """
        return self._invest_amount

    @invest_amount.setter
    def invest_amount(self, invest_amount):
        """Sets the invest_amount of this DualOrderRefundPreview.

        Investment amount  # noqa: E501

        :param invest_amount: The invest_amount of this DualOrderRefundPreview.  # noqa: E501
        :type: str
        """

        self._invest_amount = invest_amount

    @property
    def invest_currency(self):
        """Gets the invest_currency of this DualOrderRefundPreview.  # noqa: E501

        Investment Token  # noqa: E501

        :return: The invest_currency of this DualOrderRefundPreview.  # noqa: E501
        :rtype: str
        """
        return self._invest_currency

    @invest_currency.setter
    def invest_currency(self, invest_currency):
        """Sets the invest_currency of this DualOrderRefundPreview.

        Investment Token  # noqa: E501

        :param invest_currency: The invest_currency of this DualOrderRefundPreview.  # noqa: E501
        :type: str
        """

        self._invest_currency = invest_currency

    @property
    def name(self):
        """Gets the name of this DualOrderRefundPreview.  # noqa: E501

        Order name identifier  # noqa: E501

        :return: The name of this DualOrderRefundPreview.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this DualOrderRefundPreview.

        Order name identifier  # noqa: E501

        :param name: The name of this DualOrderRefundPreview.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def order_id(self):
        """Gets the order_id of this DualOrderRefundPreview.  # noqa: E501

        Order ID  # noqa: E501

        :return: The order_id of this DualOrderRefundPreview.  # noqa: E501
        :rtype: int
        """
        return self._order_id

    @order_id.setter
    def order_id(self, order_id):
        """Sets the order_id of this DualOrderRefundPreview.

        Order ID  # noqa: E501

        :param order_id: The order_id of this DualOrderRefundPreview.  # noqa: E501
        :type: int
        """

        self._order_id = order_id

    @property
    def req_id(self):
        """Gets the req_id of this DualOrderRefundPreview.  # noqa: E501

        Request ID used for actual redemption  # noqa: E501

        :return: The req_id of this DualOrderRefundPreview.  # noqa: E501
        :rtype: str
        """
        return self._req_id

    @req_id.setter
    def req_id(self, req_id):
        """Sets the req_id of this DualOrderRefundPreview.

        Request ID used for actual redemption  # noqa: E501

        :param req_id: The req_id of this DualOrderRefundPreview.  # noqa: E501
        :type: str
        """

        self._req_id = req_id

    @property
    def refund_service_charge(self):
        """Gets the refund_service_charge of this DualOrderRefundPreview.  # noqa: E501

        Refund fee  # noqa: E501

        :return: The refund_service_charge of this DualOrderRefundPreview.  # noqa: E501
        :rtype: int
        """
        return self._refund_service_charge

    @refund_service_charge.setter
    def refund_service_charge(self, refund_service_charge):
        """Sets the refund_service_charge of this DualOrderRefundPreview.

        Refund fee  # noqa: E501

        :param refund_service_charge: The refund_service_charge of this DualOrderRefundPreview.  # noqa: E501
        :type: int
        """

        self._refund_service_charge = refund_service_charge

    @property
    def settle_price(self):
        """Gets the settle_price of this DualOrderRefundPreview.  # noqa: E501

        Settlement price  # noqa: E501

        :return: The settle_price of this DualOrderRefundPreview.  # noqa: E501
        :rtype: str
        """
        return self._settle_price

    @settle_price.setter
    def settle_price(self, settle_price):
        """Sets the settle_price of this DualOrderRefundPreview.

        Settlement price  # noqa: E501

        :param settle_price: The settle_price of this DualOrderRefundPreview.  # noqa: E501
        :type: str
        """

        self._settle_price = settle_price

    @property
    def settlement_amount(self):
        """Gets the settlement_amount of this DualOrderRefundPreview.  # noqa: E501

        Settlement amount  # noqa: E501

        :return: The settlement_amount of this DualOrderRefundPreview.  # noqa: E501
        :rtype: str
        """
        return self._settlement_amount

    @settlement_amount.setter
    def settlement_amount(self, settlement_amount):
        """Sets the settlement_amount of this DualOrderRefundPreview.

        Settlement amount  # noqa: E501

        :param settlement_amount: The settlement_amount of this DualOrderRefundPreview.  # noqa: E501
        :type: str
        """

        self._settlement_amount = settlement_amount

    @property
    def settlement_currency(self):
        """Gets the settlement_currency of this DualOrderRefundPreview.  # noqa: E501

        Settlement currency  # noqa: E501

        :return: The settlement_currency of this DualOrderRefundPreview.  # noqa: E501
        :rtype: str
        """
        return self._settlement_currency

    @settlement_currency.setter
    def settlement_currency(self, settlement_currency):
        """Sets the settlement_currency of this DualOrderRefundPreview.

        Settlement currency  # noqa: E501

        :param settlement_currency: The settlement_currency of this DualOrderRefundPreview.  # noqa: E501
        :type: str
        """

        self._settlement_currency = settlement_currency

    @property
    def settlement_interest(self):
        """Gets the settlement_interest of this DualOrderRefundPreview.  # noqa: E501

        Settlement interest  # noqa: E501

        :return: The settlement_interest of this DualOrderRefundPreview.  # noqa: E501
        :rtype: str
        """
        return self._settlement_interest

    @settlement_interest.setter
    def settlement_interest(self, settlement_interest):
        """Sets the settlement_interest of this DualOrderRefundPreview.

        Settlement interest  # noqa: E501

        :param settlement_interest: The settlement_interest of this DualOrderRefundPreview.  # noqa: E501
        :type: str
        """

        self._settlement_interest = settlement_interest

    @property
    def settlement_principle(self):
        """Gets the settlement_principle of this DualOrderRefundPreview.  # noqa: E501

        Settlement principal  # noqa: E501

        :return: The settlement_principle of this DualOrderRefundPreview.  # noqa: E501
        :rtype: str
        """
        return self._settlement_principle

    @settlement_principle.setter
    def settlement_principle(self, settlement_principle):
        """Sets the settlement_principle of this DualOrderRefundPreview.

        Settlement principal  # noqa: E501

        :param settlement_principle: The settlement_principle of this DualOrderRefundPreview.  # noqa: E501
        :type: str
        """

        self._settlement_principle = settlement_principle

    @property
    def type(self):
        """Gets the type of this DualOrderRefundPreview.  # noqa: E501

        `call`: sell high; `put`: buy low  # noqa: E501

        :return: The type of this DualOrderRefundPreview.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this DualOrderRefundPreview.

        `call`: sell high; `put`: buy low  # noqa: E501

        :param type: The type of this DualOrderRefundPreview.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def money_back_timest(self):
        """Gets the money_back_timest of this DualOrderRefundPreview.  # noqa: E501

        Redemption time  # noqa: E501

        :return: The money_back_timest of this DualOrderRefundPreview.  # noqa: E501
        :rtype: int
        """
        return self._money_back_timest

    @money_back_timest.setter
    def money_back_timest(self, money_back_timest):
        """Sets the money_back_timest of this DualOrderRefundPreview.

        Redemption time  # noqa: E501

        :param money_back_timest: The money_back_timest of this DualOrderRefundPreview.  # noqa: E501
        :type: int
        """

        self._money_back_timest = money_back_timest

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DualOrderRefundPreview):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, DualOrderRefundPreview):
            return True

        return self.to_dict() != other.to_dict()
