# coding: utf-8

"""
    Gate API

    Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.  # noqa: E501

    Contact: support@mail.gate.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from gate_api.configuration import Configuration


class FixedTermLendRequest(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'product_id': 'int',
        'amount': 'str',
        'year_rate': 'str',
        'reinvest_status': 'int',
        'redeem_account_type': 'int',
        'financial_rate_id': 'int',
        'sub_business': 'int'
    }

    attribute_map = {
        'product_id': 'product_id',
        'amount': 'amount',
        'year_rate': 'year_rate',
        'reinvest_status': 'reinvest_status',
        'redeem_account_type': 'redeem_account_type',
        'financial_rate_id': 'financial_rate_id',
        'sub_business': 'sub_business'
    }

    def __init__(self, product_id=None, amount=None, year_rate=None, reinvest_status=None, redeem_account_type=None, financial_rate_id=None, sub_business=None, local_vars_configuration=None):  # noqa: E501
        # type: (int, str, str, int, int, int, int, Configuration) -> None
        """FixedTermLendRequest - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._product_id = None
        self._amount = None
        self._year_rate = None
        self._reinvest_status = None
        self._redeem_account_type = None
        self._financial_rate_id = None
        self._sub_business = None
        self.discriminator = None

        self.product_id = product_id
        self.amount = amount
        if year_rate is not None:
            self.year_rate = year_rate
        if reinvest_status is not None:
            self.reinvest_status = reinvest_status
        if redeem_account_type is not None:
            self.redeem_account_type = redeem_account_type
        if financial_rate_id is not None:
            self.financial_rate_id = financial_rate_id
        if sub_business is not None:
            self.sub_business = sub_business

    @property
    def product_id(self):
        """Gets the product_id of this FixedTermLendRequest.  # noqa: E501

        Product ID  # noqa: E501

        :return: The product_id of this FixedTermLendRequest.  # noqa: E501
        :rtype: int
        """
        return self._product_id

    @product_id.setter
    def product_id(self, product_id):
        """Sets the product_id of this FixedTermLendRequest.

        Product ID  # noqa: E501

        :param product_id: The product_id of this FixedTermLendRequest.  # noqa: E501
        :type: int
        """
        if self.local_vars_configuration.client_side_validation and product_id is None:  # noqa: E501
            raise ValueError("Invalid value for `product_id`, must not be `None`")  # noqa: E501

        self._product_id = product_id

    @property
    def amount(self):
        """Gets the amount of this FixedTermLendRequest.  # noqa: E501

        Subscription amount  # noqa: E501

        :return: The amount of this FixedTermLendRequest.  # noqa: E501
        :rtype: str
        """
        return self._amount

    @amount.setter
    def amount(self, amount):
        """Sets the amount of this FixedTermLendRequest.

        Subscription amount  # noqa: E501

        :param amount: The amount of this FixedTermLendRequest.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and amount is None:  # noqa: E501
            raise ValueError("Invalid value for `amount`, must not be `None`")  # noqa: E501

        self._amount = amount

    @property
    def year_rate(self):
        """Gets the year_rate of this FixedTermLendRequest.  # noqa: E501

        Annual interest rate  # noqa: E501

        :return: The year_rate of this FixedTermLendRequest.  # noqa: E501
        :rtype: str
        """
        return self._year_rate

    @year_rate.setter
    def year_rate(self, year_rate):
        """Sets the year_rate of this FixedTermLendRequest.

        Annual interest rate  # noqa: E501

        :param year_rate: The year_rate of this FixedTermLendRequest.  # noqa: E501
        :type: str
        """

        self._year_rate = year_rate

    @property
    def reinvest_status(self):
        """Gets the reinvest_status of this FixedTermLendRequest.  # noqa: E501

        Auto-renewal status: 0 for disabled, 1 for enabled  # noqa: E501

        :return: The reinvest_status of this FixedTermLendRequest.  # noqa: E501
        :rtype: int
        """
        return self._reinvest_status

    @reinvest_status.setter
    def reinvest_status(self, reinvest_status):
        """Sets the reinvest_status of this FixedTermLendRequest.

        Auto-renewal status: 0 for disabled, 1 for enabled  # noqa: E501

        :param reinvest_status: The reinvest_status of this FixedTermLendRequest.  # noqa: E501
        :type: int
        """

        self._reinvest_status = reinvest_status

    @property
    def redeem_account_type(self):
        """Gets the redeem_account_type of this FixedTermLendRequest.  # noqa: E501

        Redemption payout account type: 1 for spot account  # noqa: E501

        :return: The redeem_account_type of this FixedTermLendRequest.  # noqa: E501
        :rtype: int
        """
        return self._redeem_account_type

    @redeem_account_type.setter
    def redeem_account_type(self, redeem_account_type):
        """Sets the redeem_account_type of this FixedTermLendRequest.

        Redemption payout account type: 1 for spot account  # noqa: E501

        :param redeem_account_type: The redeem_account_type of this FixedTermLendRequest.  # noqa: E501
        :type: int
        """

        self._redeem_account_type = redeem_account_type

    @property
    def financial_rate_id(self):
        """Gets the financial_rate_id of this FixedTermLendRequest.  # noqa: E501

        Interest rate boost coupon ID, 0 means not used  # noqa: E501

        :return: The financial_rate_id of this FixedTermLendRequest.  # noqa: E501
        :rtype: int
        """
        return self._financial_rate_id

    @financial_rate_id.setter
    def financial_rate_id(self, financial_rate_id):
        """Sets the financial_rate_id of this FixedTermLendRequest.

        Interest rate boost coupon ID, 0 means not used  # noqa: E501

        :param financial_rate_id: The financial_rate_id of this FixedTermLendRequest.  # noqa: E501
        :type: int
        """

        self._financial_rate_id = financial_rate_id

    @property
    def sub_business(self):
        """Gets the sub_business of this FixedTermLendRequest.  # noqa: E501

        Sub-business type  # noqa: E501

        :return: The sub_business of this FixedTermLendRequest.  # noqa: E501
        :rtype: int
        """
        return self._sub_business

    @sub_business.setter
    def sub_business(self, sub_business):
        """Sets the sub_business of this FixedTermLendRequest.

        Sub-business type  # noqa: E501

        :param sub_business: The sub_business of this FixedTermLendRequest.  # noqa: E501
        :type: int
        """

        self._sub_business = sub_business

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FixedTermLendRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, FixedTermLendRequest):
            return True

        return self.to_dict() != other.to_dict()
