# coding: utf-8

"""
    Gate API

    Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.  # noqa: E501

    Contact: support@mail.gate.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from gate_api.configuration import Configuration


class HodlerAirdropV4ProjectItem(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'hodler_id': 'str',
        'name': 'str',
        'asset': 'str',
        'status': 'str',
        'total_amount': 'str',
        'open_timest': 'str',
        'close_timest': 'str',
        'per_gt_reward_token': 'str',
        'user_count': 'str',
        'max_queue_amount': 'str'
    }

    attribute_map = {
        'hodler_id': 'hodler_id',
        'name': 'name',
        'asset': 'asset',
        'status': 'status',
        'total_amount': 'total_amount',
        'open_timest': 'open_timest',
        'close_timest': 'close_timest',
        'per_gt_reward_token': 'per_gt_reward_token',
        'user_count': 'user_count',
        'max_queue_amount': 'max_queue_amount'
    }

    def __init__(self, hodler_id=None, name=None, asset=None, status=None, total_amount=None, open_timest=None, close_timest=None, per_gt_reward_token=None, user_count=None, max_queue_amount=None, local_vars_configuration=None):  # noqa: E501
        # type: (str, str, str, str, str, str, str, str, str, str, Configuration) -> None
        """HodlerAirdropV4ProjectItem - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._hodler_id = None
        self._name = None
        self._asset = None
        self._status = None
        self._total_amount = None
        self._open_timest = None
        self._close_timest = None
        self._per_gt_reward_token = None
        self._user_count = None
        self._max_queue_amount = None
        self.discriminator = None

        self.hodler_id = hodler_id
        self.name = name
        self.asset = asset
        self.status = status
        self.total_amount = total_amount
        self.open_timest = open_timest
        self.close_timest = close_timest
        if per_gt_reward_token is not None:
            self.per_gt_reward_token = per_gt_reward_token
        if user_count is not None:
            self.user_count = user_count
        if max_queue_amount is not None:
            self.max_queue_amount = max_queue_amount

    @property
    def hodler_id(self):
        """Gets the hodler_id of this HodlerAirdropV4ProjectItem.  # noqa: E501

        Product ID  # noqa: E501

        :return: The hodler_id of this HodlerAirdropV4ProjectItem.  # noqa: E501
        :rtype: str
        """
        return self._hodler_id

    @hodler_id.setter
    def hodler_id(self, hodler_id):
        """Sets the hodler_id of this HodlerAirdropV4ProjectItem.

        Product ID  # noqa: E501

        :param hodler_id: The hodler_id of this HodlerAirdropV4ProjectItem.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and hodler_id is None:  # noqa: E501
            raise ValueError("Invalid value for `hodler_id`, must not be `None`")  # noqa: E501

        self._hodler_id = hodler_id

    @property
    def name(self):
        """Gets the name of this HodlerAirdropV4ProjectItem.  # noqa: E501

        Product Name  # noqa: E501

        :return: The name of this HodlerAirdropV4ProjectItem.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this HodlerAirdropV4ProjectItem.

        Product Name  # noqa: E501

        :param name: The name of this HodlerAirdropV4ProjectItem.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and name is None:  # noqa: E501
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def asset(self):
        """Gets the asset of this HodlerAirdropV4ProjectItem.  # noqa: E501

        Airdrop currency  # noqa: E501

        :return: The asset of this HodlerAirdropV4ProjectItem.  # noqa: E501
        :rtype: str
        """
        return self._asset

    @asset.setter
    def asset(self, asset):
        """Sets the asset of this HodlerAirdropV4ProjectItem.

        Airdrop currency  # noqa: E501

        :param asset: The asset of this HodlerAirdropV4ProjectItem.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and asset is None:  # noqa: E501
            raise ValueError("Invalid value for `asset`, must not be `None`")  # noqa: E501

        self._asset = asset

    @property
    def status(self):
        """Gets the status of this HodlerAirdropV4ProjectItem.  # noqa: E501

        Project status  # noqa: E501

        :return: The status of this HodlerAirdropV4ProjectItem.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this HodlerAirdropV4ProjectItem.

        Project status  # noqa: E501

        :param status: The status of this HodlerAirdropV4ProjectItem.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and status is None:  # noqa: E501
            raise ValueError("Invalid value for `status`, must not be `None`")  # noqa: E501
        allowed_values = ["UNDERWAY", "PREHEAT", "FINISH"]  # noqa: E501
        if self.local_vars_configuration.client_side_validation and status not in allowed_values:  # noqa: E501
            raise ValueError(
                "Invalid value for `status` ({0}), must be one of {1}"  # noqa: E501
                .format(status, allowed_values)
            )

        self._status = status

    @property
    def total_amount(self):
        """Gets the total_amount of this HodlerAirdropV4ProjectItem.  # noqa: E501

        Total airdrop amount  # noqa: E501

        :return: The total_amount of this HodlerAirdropV4ProjectItem.  # noqa: E501
        :rtype: str
        """
        return self._total_amount

    @total_amount.setter
    def total_amount(self, total_amount):
        """Sets the total_amount of this HodlerAirdropV4ProjectItem.

        Total airdrop amount  # noqa: E501

        :param total_amount: The total_amount of this HodlerAirdropV4ProjectItem.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and total_amount is None:  # noqa: E501
            raise ValueError("Invalid value for `total_amount`, must not be `None`")  # noqa: E501

        self._total_amount = total_amount

    @property
    def open_timest(self):
        """Gets the open_timest of this HodlerAirdropV4ProjectItem.  # noqa: E501

        Event start time, format Y-m-d H:i:s, UTC  # noqa: E501

        :return: The open_timest of this HodlerAirdropV4ProjectItem.  # noqa: E501
        :rtype: str
        """
        return self._open_timest

    @open_timest.setter
    def open_timest(self, open_timest):
        """Sets the open_timest of this HodlerAirdropV4ProjectItem.

        Event start time, format Y-m-d H:i:s, UTC  # noqa: E501

        :param open_timest: The open_timest of this HodlerAirdropV4ProjectItem.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and open_timest is None:  # noqa: E501
            raise ValueError("Invalid value for `open_timest`, must not be `None`")  # noqa: E501

        self._open_timest = open_timest

    @property
    def close_timest(self):
        """Gets the close_timest of this HodlerAirdropV4ProjectItem.  # noqa: E501

        Event end time, format Y-m-d H:i:s, UTC  # noqa: E501

        :return: The close_timest of this HodlerAirdropV4ProjectItem.  # noqa: E501
        :rtype: str
        """
        return self._close_timest

    @close_timest.setter
    def close_timest(self, close_timest):
        """Sets the close_timest of this HodlerAirdropV4ProjectItem.

        Event end time, format Y-m-d H:i:s, UTC  # noqa: E501

        :param close_timest: The close_timest of this HodlerAirdropV4ProjectItem.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and close_timest is None:  # noqa: E501
            raise ValueError("Invalid value for `close_timest`, must not be `None`")  # noqa: E501

        self._close_timest = close_timest

    @property
    def per_gt_reward_token(self):
        """Gets the per_gt_reward_token of this HodlerAirdropV4ProjectItem.  # noqa: E501

        The number of airdrop coins that can be obtained for each GT. When the calculation is in progress, an empty string is returned.  # noqa: E501

        :return: The per_gt_reward_token of this HodlerAirdropV4ProjectItem.  # noqa: E501
        :rtype: str
        """
        return self._per_gt_reward_token

    @per_gt_reward_token.setter
    def per_gt_reward_token(self, per_gt_reward_token):
        """Sets the per_gt_reward_token of this HodlerAirdropV4ProjectItem.

        The number of airdrop coins that can be obtained for each GT. When the calculation is in progress, an empty string is returned.  # noqa: E501

        :param per_gt_reward_token: The per_gt_reward_token of this HodlerAirdropV4ProjectItem.  # noqa: E501
        :type: str
        """

        self._per_gt_reward_token = per_gt_reward_token

    @property
    def user_count(self):
        """Gets the user_count of this HodlerAirdropV4ProjectItem.  # noqa: E501

        Number of participants  # noqa: E501

        :return: The user_count of this HodlerAirdropV4ProjectItem.  # noqa: E501
        :rtype: str
        """
        return self._user_count

    @user_count.setter
    def user_count(self, user_count):
        """Sets the user_count of this HodlerAirdropV4ProjectItem.

        Number of participants  # noqa: E501

        :param user_count: The user_count of this HodlerAirdropV4ProjectItem.  # noqa: E501
        :type: str
        """

        self._user_count = user_count

    @property
    def max_queue_amount(self):
        """Gets the max_queue_amount of this HodlerAirdropV4ProjectItem.  # noqa: E501

        Personal GT limit  # noqa: E501

        :return: The max_queue_amount of this HodlerAirdropV4ProjectItem.  # noqa: E501
        :rtype: str
        """
        return self._max_queue_amount

    @max_queue_amount.setter
    def max_queue_amount(self, max_queue_amount):
        """Sets the max_queue_amount of this HodlerAirdropV4ProjectItem.

        Personal GT limit  # noqa: E501

        :param max_queue_amount: The max_queue_amount of this HodlerAirdropV4ProjectItem.  # noqa: E501
        :type: str
        """

        self._max_queue_amount = max_queue_amount

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, HodlerAirdropV4ProjectItem):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, HodlerAirdropV4ProjectItem):
            return True

        return self.to_dict() != other.to_dict()
