# coding: utf-8

"""
    Gate API

    Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.  # noqa: E501

    Contact: support@mail.gate.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from gate_api.configuration import Configuration


class InlineObject16(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'asset': 'str',
        'fiat_unit': 'str',
        'trade_type': 'str'
    }

    attribute_map = {
        'asset': 'asset',
        'fiat_unit': 'fiat_unit',
        'trade_type': 'trade_type'
    }

    def __init__(self, asset=None, fiat_unit=None, trade_type=None, local_vars_configuration=None):  # noqa: E501
        # type: (str, str, str, Configuration) -> None
        """InlineObject16 - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._asset = None
        self._fiat_unit = None
        self._trade_type = None
        self.discriminator = None

        if asset is not None:
            self.asset = asset
        if fiat_unit is not None:
            self.fiat_unit = fiat_unit
        if trade_type is not None:
            self.trade_type = trade_type

    @property
    def asset(self):
        """Gets the asset of this InlineObject16.  # noqa: E501

        Cryptocurrency  # noqa: E501

        :return: The asset of this InlineObject16.  # noqa: E501
        :rtype: str
        """
        return self._asset

    @asset.setter
    def asset(self, asset):
        """Sets the asset of this InlineObject16.

        Cryptocurrency  # noqa: E501

        :param asset: The asset of this InlineObject16.  # noqa: E501
        :type: str
        """

        self._asset = asset

    @property
    def fiat_unit(self):
        """Gets the fiat_unit of this InlineObject16.  # noqa: E501

        Fiat currency  # noqa: E501

        :return: The fiat_unit of this InlineObject16.  # noqa: E501
        :rtype: str
        """
        return self._fiat_unit

    @fiat_unit.setter
    def fiat_unit(self, fiat_unit):
        """Sets the fiat_unit of this InlineObject16.

        Fiat currency  # noqa: E501

        :param fiat_unit: The fiat_unit of this InlineObject16.  # noqa: E501
        :type: str
        """

        self._fiat_unit = fiat_unit

    @property
    def trade_type(self):
        """Gets the trade_type of this InlineObject16.  # noqa: E501

        Buy/Sell  # noqa: E501

        :return: The trade_type of this InlineObject16.  # noqa: E501
        :rtype: str
        """
        return self._trade_type

    @trade_type.setter
    def trade_type(self, trade_type):
        """Sets the trade_type of this InlineObject16.

        Buy/Sell  # noqa: E501

        :param trade_type: The trade_type of this InlineObject16.  # noqa: E501
        :type: str
        """

        self._trade_type = trade_type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineObject16):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, InlineObject16):
            return True

        return self.to_dict() != other.to_dict()
