# coding: utf-8

"""
    Gate API

    Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.  # noqa: E501

    Contact: support@mail.gate.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from gate_api.configuration import Configuration


class InlineResponse20012Data(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'list': 'list[InlineResponse20012DataList]',
        'trans_time': 'list[InlineResponse20012DataTransTime]',
        'count': 'int',
        'exported_num': 'int'
    }

    attribute_map = {
        'list': 'list',
        'trans_time': 'trans_time',
        'count': 'count',
        'exported_num': 'exported_num'
    }

    def __init__(self, list=None, trans_time=None, count=None, exported_num=None, local_vars_configuration=None):  # noqa: E501
        # type: (list[InlineResponse20012DataList], list[InlineResponse20012DataTransTime], int, int, Configuration) -> None
        """InlineResponse20012Data - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._list = None
        self._trans_time = None
        self._count = None
        self._exported_num = None
        self.discriminator = None

        self.list = list
        self.trans_time = trans_time
        self.count = count
        self.exported_num = exported_num

    @property
    def list(self):
        """Gets the list of this InlineResponse20012Data.  # noqa: E501


        :return: The list of this InlineResponse20012Data.  # noqa: E501
        :rtype: list[InlineResponse20012DataList]
        """
        return self._list

    @list.setter
    def list(self, list):
        """Sets the list of this InlineResponse20012Data.


        :param list: The list of this InlineResponse20012Data.  # noqa: E501
        :type: list[InlineResponse20012DataList]
        """
        if self.local_vars_configuration.client_side_validation and list is None:  # noqa: E501
            raise ValueError("Invalid value for `list`, must not be `None`")  # noqa: E501

        self._list = list

    @property
    def trans_time(self):
        """Gets the trans_time of this InlineResponse20012Data.  # noqa: E501

        Countdown time  # noqa: E501

        :return: The trans_time of this InlineResponse20012Data.  # noqa: E501
        :rtype: list[InlineResponse20012DataTransTime]
        """
        return self._trans_time

    @trans_time.setter
    def trans_time(self, trans_time):
        """Sets the trans_time of this InlineResponse20012Data.

        Countdown time  # noqa: E501

        :param trans_time: The trans_time of this InlineResponse20012Data.  # noqa: E501
        :type: list[InlineResponse20012DataTransTime]
        """
        if self.local_vars_configuration.client_side_validation and trans_time is None:  # noqa: E501
            raise ValueError("Invalid value for `trans_time`, must not be `None`")  # noqa: E501

        self._trans_time = trans_time

    @property
    def count(self):
        """Gets the count of this InlineResponse20012Data.  # noqa: E501

        Number of orders  # noqa: E501

        :return: The count of this InlineResponse20012Data.  # noqa: E501
        :rtype: int
        """
        return self._count

    @count.setter
    def count(self, count):
        """Sets the count of this InlineResponse20012Data.

        Number of orders  # noqa: E501

        :param count: The count of this InlineResponse20012Data.  # noqa: E501
        :type: int
        """
        if self.local_vars_configuration.client_side_validation and count is None:  # noqa: E501
            raise ValueError("Invalid value for `count`, must not be `None`")  # noqa: E501

        self._count = count

    @property
    def exported_num(self):
        """Gets the exported_num of this InlineResponse20012Data.  # noqa: E501

        Export count  # noqa: E501

        :return: The exported_num of this InlineResponse20012Data.  # noqa: E501
        :rtype: int
        """
        return self._exported_num

    @exported_num.setter
    def exported_num(self, exported_num):
        """Sets the exported_num of this InlineResponse20012Data.

        Export count  # noqa: E501

        :param exported_num: The exported_num of this InlineResponse20012Data.  # noqa: E501
        :type: int
        """
        if self.local_vars_configuration.client_side_validation and exported_num is None:  # noqa: E501
            raise ValueError("Invalid value for `exported_num`, must not be `None`")  # noqa: E501

        self._exported_num = exported_num

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse20012Data):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, InlineResponse20012Data):
            return True

        return self.to_dict() != other.to_dict()
