# coding: utf-8

"""
    Gate API

    Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.  # noqa: E501

    Contact: support@mail.gate.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from gate_api.configuration import Configuration


class InlineResponse20011DataList(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'int',
        'trade_no': 'str',
        'pay_coin': 'str',
        'pay_amount': 'str',
        'get_coin': 'str',
        'get_amount': 'str',
        'rate': 'str',
        'rate_reci': 'str',
        'status': 'str',
        'create_timest': 'int',
        'create_time': 'str'
    }

    attribute_map = {
        'id': 'id',
        'trade_no': 'trade_no',
        'pay_coin': 'pay_coin',
        'pay_amount': 'pay_amount',
        'get_coin': 'get_coin',
        'get_amount': 'get_amount',
        'rate': 'rate',
        'rate_reci': 'rate_reci',
        'status': 'status',
        'create_timest': 'create_timest',
        'create_time': 'create_time'
    }

    def __init__(self, id=None, trade_no=None, pay_coin=None, pay_amount=None, get_coin=None, get_amount=None, rate=None, rate_reci=None, status=None, create_timest=None, create_time=None, local_vars_configuration=None):  # noqa: E501
        # type: (int, str, str, str, str, str, str, str, str, int, str, Configuration) -> None
        """InlineResponse20011DataList - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._id = None
        self._trade_no = None
        self._pay_coin = None
        self._pay_amount = None
        self._get_coin = None
        self._get_amount = None
        self._rate = None
        self._rate_reci = None
        self._status = None
        self._create_timest = None
        self._create_time = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if trade_no is not None:
            self.trade_no = trade_no
        if pay_coin is not None:
            self.pay_coin = pay_coin
        if pay_amount is not None:
            self.pay_amount = pay_amount
        if get_coin is not None:
            self.get_coin = get_coin
        if get_amount is not None:
            self.get_amount = get_amount
        if rate is not None:
            self.rate = rate
        if rate_reci is not None:
            self.rate_reci = rate_reci
        if status is not None:
            self.status = status
        if create_timest is not None:
            self.create_timest = create_timest
        if create_time is not None:
            self.create_time = create_time

    @property
    def id(self):
        """Gets the id of this InlineResponse20011DataList.  # noqa: E501

        Order ID  # noqa: E501

        :return: The id of this InlineResponse20011DataList.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this InlineResponse20011DataList.

        Order ID  # noqa: E501

        :param id: The id of this InlineResponse20011DataList.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def trade_no(self):
        """Gets the trade_no of this InlineResponse20011DataList.  # noqa: E501

        Transaction reference number  # noqa: E501

        :return: The trade_no of this InlineResponse20011DataList.  # noqa: E501
        :rtype: str
        """
        return self._trade_no

    @trade_no.setter
    def trade_no(self, trade_no):
        """Sets the trade_no of this InlineResponse20011DataList.

        Transaction reference number  # noqa: E501

        :param trade_no: The trade_no of this InlineResponse20011DataList.  # noqa: E501
        :type: str
        """

        self._trade_no = trade_no

    @property
    def pay_coin(self):
        """Gets the pay_coin of this InlineResponse20011DataList.  # noqa: E501

        Payment currency  # noqa: E501

        :return: The pay_coin of this InlineResponse20011DataList.  # noqa: E501
        :rtype: str
        """
        return self._pay_coin

    @pay_coin.setter
    def pay_coin(self, pay_coin):
        """Sets the pay_coin of this InlineResponse20011DataList.

        Payment currency  # noqa: E501

        :param pay_coin: The pay_coin of this InlineResponse20011DataList.  # noqa: E501
        :type: str
        """

        self._pay_coin = pay_coin

    @property
    def pay_amount(self):
        """Gets the pay_amount of this InlineResponse20011DataList.  # noqa: E501

        Payment amount  # noqa: E501

        :return: The pay_amount of this InlineResponse20011DataList.  # noqa: E501
        :rtype: str
        """
        return self._pay_amount

    @pay_amount.setter
    def pay_amount(self, pay_amount):
        """Sets the pay_amount of this InlineResponse20011DataList.

        Payment amount  # noqa: E501

        :param pay_amount: The pay_amount of this InlineResponse20011DataList.  # noqa: E501
        :type: str
        """

        self._pay_amount = pay_amount

    @property
    def get_coin(self):
        """Gets the get_coin of this InlineResponse20011DataList.  # noqa: E501

        Received currency  # noqa: E501

        :return: The get_coin of this InlineResponse20011DataList.  # noqa: E501
        :rtype: str
        """
        return self._get_coin

    @get_coin.setter
    def get_coin(self, get_coin):
        """Sets the get_coin of this InlineResponse20011DataList.

        Received currency  # noqa: E501

        :param get_coin: The get_coin of this InlineResponse20011DataList.  # noqa: E501
        :type: str
        """

        self._get_coin = get_coin

    @property
    def get_amount(self):
        """Gets the get_amount of this InlineResponse20011DataList.  # noqa: E501

        Received amount  # noqa: E501

        :return: The get_amount of this InlineResponse20011DataList.  # noqa: E501
        :rtype: str
        """
        return self._get_amount

    @get_amount.setter
    def get_amount(self, get_amount):
        """Sets the get_amount of this InlineResponse20011DataList.

        Received amount  # noqa: E501

        :param get_amount: The get_amount of this InlineResponse20011DataList.  # noqa: E501
        :type: str
        """

        self._get_amount = get_amount

    @property
    def rate(self):
        """Gets the rate of this InlineResponse20011DataList.  # noqa: E501

        Exchange rate  # noqa: E501

        :return: The rate of this InlineResponse20011DataList.  # noqa: E501
        :rtype: str
        """
        return self._rate

    @rate.setter
    def rate(self, rate):
        """Sets the rate of this InlineResponse20011DataList.

        Exchange rate  # noqa: E501

        :param rate: The rate of this InlineResponse20011DataList.  # noqa: E501
        :type: str
        """

        self._rate = rate

    @property
    def rate_reci(self):
        """Gets the rate_reci of this InlineResponse20011DataList.  # noqa: E501

        Reciprocal of the exchange rate  # noqa: E501

        :return: The rate_reci of this InlineResponse20011DataList.  # noqa: E501
        :rtype: str
        """
        return self._rate_reci

    @rate_reci.setter
    def rate_reci(self, rate_reci):
        """Sets the rate_reci of this InlineResponse20011DataList.

        Reciprocal of the exchange rate  # noqa: E501

        :param rate_reci: The rate_reci of this InlineResponse20011DataList.  # noqa: E501
        :type: str
        """

        self._rate_reci = rate_reci

    @property
    def status(self):
        """Gets the status of this InlineResponse20011DataList.  # noqa: E501

        PROCESSING: in progress / DONE: completed / FAILED: failed  # noqa: E501

        :return: The status of this InlineResponse20011DataList.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this InlineResponse20011DataList.

        PROCESSING: in progress / DONE: completed / FAILED: failed  # noqa: E501

        :param status: The status of this InlineResponse20011DataList.  # noqa: E501
        :type: str
        """

        self._status = status

    @property
    def create_timest(self):
        """Gets the create_timest of this InlineResponse20011DataList.  # noqa: E501

        timetimestamp  # noqa: E501

        :return: The create_timest of this InlineResponse20011DataList.  # noqa: E501
        :rtype: int
        """
        return self._create_timest

    @create_timest.setter
    def create_timest(self, create_timest):
        """Sets the create_timest of this InlineResponse20011DataList.

        timetimestamp  # noqa: E501

        :param create_timest: The create_timest of this InlineResponse20011DataList.  # noqa: E501
        :type: int
        """

        self._create_timest = create_timest

    @property
    def create_time(self):
        """Gets the create_time of this InlineResponse20011DataList.  # noqa: E501

        Created time  # noqa: E501

        :return: The create_time of this InlineResponse20011DataList.  # noqa: E501
        :rtype: str
        """
        return self._create_time

    @create_time.setter
    def create_time(self, create_time):
        """Sets the create_time of this InlineResponse20011DataList.

        Created time  # noqa: E501

        :param create_time: The create_time of this InlineResponse20011DataList.  # noqa: E501
        :type: str
        """

        self._create_time = create_time

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse20011DataList):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, InlineResponse20011DataList):
            return True

        return self.to_dict() != other.to_dict()
