# coding: utf-8

"""
    Gate API

    Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.  # noqa: E501

    Contact: support@mail.gate.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from gate_api.configuration import Configuration


class InlineResponse20017DataTransTime(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'od_time': 'int'
    }

    attribute_map = {
        'od_time': 'od_time'
    }

    def __init__(self, od_time=None, local_vars_configuration=None):  # noqa: E501
        # type: (int, Configuration) -> None
        """InlineResponse20017DataTransTime - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._od_time = None
        self.discriminator = None

        if od_time is not None:
            self.od_time = od_time

    @property
    def od_time(self):
        """Gets the od_time of this InlineResponse20017DataTransTime.  # noqa: E501


        :return: The od_time of this InlineResponse20017DataTransTime.  # noqa: E501
        :rtype: int
        """
        return self._od_time

    @od_time.setter
    def od_time(self, od_time):
        """Sets the od_time of this InlineResponse20017DataTransTime.


        :param od_time: The od_time of this InlineResponse20017DataTransTime.  # noqa: E501
        :type: int
        """

        self._od_time = od_time

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse20017DataTransTime):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, InlineResponse20017DataTransTime):
            return True

        return self.to_dict() != other.to_dict()
