# coding: utf-8

"""
    Gate API

    Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.  # noqa: E501

    Contact: support@mail.gate.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from gate_api.configuration import Configuration


class InlineObject2(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'type': 'str',
        'side': 'str',
        'crypto_currency': 'str',
        'fiat_currency': 'str',
        'crypto_amount': 'str',
        'fiat_amount': 'str',
        'promotion_code': 'str',
        'quote_token': 'str',
        'bank_id': 'str'
    }

    attribute_map = {
        'type': 'type',
        'side': 'side',
        'crypto_currency': 'crypto_currency',
        'fiat_currency': 'fiat_currency',
        'crypto_amount': 'crypto_amount',
        'fiat_amount': 'fiat_amount',
        'promotion_code': 'promotion_code',
        'quote_token': 'quote_token',
        'bank_id': 'bank_id'
    }

    def __init__(self, type=None, side=None, crypto_currency=None, fiat_currency=None, crypto_amount=None, fiat_amount=None, promotion_code=None, quote_token=None, bank_id=None, local_vars_configuration=None):  # noqa: E501
        # type: (str, str, str, str, str, str, str, str, str, Configuration) -> None
        """InlineObject2 - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._type = None
        self._side = None
        self._crypto_currency = None
        self._fiat_currency = None
        self._crypto_amount = None
        self._fiat_amount = None
        self._promotion_code = None
        self._quote_token = None
        self._bank_id = None
        self.discriminator = None

        self.type = type
        self.side = side
        self.crypto_currency = crypto_currency
        self.fiat_currency = fiat_currency
        self.crypto_amount = crypto_amount
        self.fiat_amount = fiat_amount
        if promotion_code is not None:
            self.promotion_code = promotion_code
        self.quote_token = quote_token
        self.bank_id = bank_id

    @property
    def type(self):
        """Gets the type of this InlineObject2.  # noqa: E501

        BUY for on-ramp, SELL for off-ramp  # noqa: E501

        :return: The type of this InlineObject2.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this InlineObject2.

        BUY for on-ramp, SELL for off-ramp  # noqa: E501

        :param type: The type of this InlineObject2.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and type is None:  # noqa: E501
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type

    @property
    def side(self):
        """Gets the side of this InlineObject2.  # noqa: E501

        Quote direction returned by the quote API (used for order validation)  # noqa: E501

        :return: The side of this InlineObject2.  # noqa: E501
        :rtype: str
        """
        return self._side

    @side.setter
    def side(self, side):
        """Sets the side of this InlineObject2.

        Quote direction returned by the quote API (used for order validation)  # noqa: E501

        :param side: The side of this InlineObject2.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and side is None:  # noqa: E501
            raise ValueError("Invalid value for `side`, must not be `None`")  # noqa: E501

        self._side = side

    @property
    def crypto_currency(self):
        """Gets the crypto_currency of this InlineObject2.  # noqa: E501

        Cryptocurrency (supported currencies can be queried from the OTC web fiat quote page)  # noqa: E501

        :return: The crypto_currency of this InlineObject2.  # noqa: E501
        :rtype: str
        """
        return self._crypto_currency

    @crypto_currency.setter
    def crypto_currency(self, crypto_currency):
        """Sets the crypto_currency of this InlineObject2.

        Cryptocurrency (supported currencies can be queried from the OTC web fiat quote page)  # noqa: E501

        :param crypto_currency: The crypto_currency of this InlineObject2.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and crypto_currency is None:  # noqa: E501
            raise ValueError("Invalid value for `crypto_currency`, must not be `None`")  # noqa: E501

        self._crypto_currency = crypto_currency

    @property
    def fiat_currency(self):
        """Gets the fiat_currency of this InlineObject2.  # noqa: E501

        Fiat currency (supported currencies can be queried from the OTC web fiat quote page)  # noqa: E501

        :return: The fiat_currency of this InlineObject2.  # noqa: E501
        :rtype: str
        """
        return self._fiat_currency

    @fiat_currency.setter
    def fiat_currency(self, fiat_currency):
        """Sets the fiat_currency of this InlineObject2.

        Fiat currency (supported currencies can be queried from the OTC web fiat quote page)  # noqa: E501

        :param fiat_currency: The fiat_currency of this InlineObject2.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and fiat_currency is None:  # noqa: E501
            raise ValueError("Invalid value for `fiat_currency`, must not be `None`")  # noqa: E501

        self._fiat_currency = fiat_currency

    @property
    def crypto_amount(self):
        """Gets the crypto_amount of this InlineObject2.  # noqa: E501

        Amount of cryptocurrency  # noqa: E501

        :return: The crypto_amount of this InlineObject2.  # noqa: E501
        :rtype: str
        """
        return self._crypto_amount

    @crypto_amount.setter
    def crypto_amount(self, crypto_amount):
        """Sets the crypto_amount of this InlineObject2.

        Amount of cryptocurrency  # noqa: E501

        :param crypto_amount: The crypto_amount of this InlineObject2.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and crypto_amount is None:  # noqa: E501
            raise ValueError("Invalid value for `crypto_amount`, must not be `None`")  # noqa: E501

        self._crypto_amount = crypto_amount

    @property
    def fiat_amount(self):
        """Gets the fiat_amount of this InlineObject2.  # noqa: E501

        Fiat amount  # noqa: E501

        :return: The fiat_amount of this InlineObject2.  # noqa: E501
        :rtype: str
        """
        return self._fiat_amount

    @fiat_amount.setter
    def fiat_amount(self, fiat_amount):
        """Sets the fiat_amount of this InlineObject2.

        Fiat amount  # noqa: E501

        :param fiat_amount: The fiat_amount of this InlineObject2.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and fiat_amount is None:  # noqa: E501
            raise ValueError("Invalid value for `fiat_amount`, must not be `None`")  # noqa: E501

        self._fiat_amount = fiat_amount

    @property
    def promotion_code(self):
        """Gets the promotion_code of this InlineObject2.  # noqa: E501

        Promotion code  # noqa: E501

        :return: The promotion_code of this InlineObject2.  # noqa: E501
        :rtype: str
        """
        return self._promotion_code

    @promotion_code.setter
    def promotion_code(self, promotion_code):
        """Sets the promotion_code of this InlineObject2.

        Promotion code  # noqa: E501

        :param promotion_code: The promotion_code of this InlineObject2.  # noqa: E501
        :type: str
        """

        self._promotion_code = promotion_code

    @property
    def quote_token(self):
        """Gets the quote_token of this InlineObject2.  # noqa: E501

        Parameter returned by the quote API  # noqa: E501

        :return: The quote_token of this InlineObject2.  # noqa: E501
        :rtype: str
        """
        return self._quote_token

    @quote_token.setter
    def quote_token(self, quote_token):
        """Sets the quote_token of this InlineObject2.

        Parameter returned by the quote API  # noqa: E501

        :param quote_token: The quote_token of this InlineObject2.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and quote_token is None:  # noqa: E501
            raise ValueError("Invalid value for `quote_token`, must not be `None`")  # noqa: E501

        self._quote_token = quote_token

    @property
    def bank_id(self):
        """Gets the bank_id of this InlineObject2.  # noqa: E501

        Bank card ID used for the order (retrieved via the default bank card API)  # noqa: E501

        :return: The bank_id of this InlineObject2.  # noqa: E501
        :rtype: str
        """
        return self._bank_id

    @bank_id.setter
    def bank_id(self, bank_id):
        """Sets the bank_id of this InlineObject2.

        Bank card ID used for the order (retrieved via the default bank card API)  # noqa: E501

        :param bank_id: The bank_id of this InlineObject2.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and bank_id is None:  # noqa: E501
            raise ValueError("Invalid value for `bank_id`, must not be `None`")  # noqa: E501

        self._bank_id = bank_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineObject2):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, InlineObject2):
            return True

        return self.to_dict() != other.to_dict()
