# coding: utf-8

"""
    Gate API

    Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.  # noqa: E501

    Contact: support@mail.gate.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from gate_api.configuration import Configuration


class InlineResponse2007(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'code': 'int',
        'label': 'str',
        'message': 'str',
        'data': 'InlineResponse2007Data'
    }

    attribute_map = {
        'code': 'code',
        'label': 'label',
        'message': 'message',
        'data': 'data'
    }

    def __init__(self, code=None, label=None, message=None, data=None, local_vars_configuration=None):  # noqa: E501
        # type: (int, str, str, InlineResponse2007Data, Configuration) -> None
        """InlineResponse2007 - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._code = None
        self._label = None
        self._message = None
        self._data = None
        self.discriminator = None

        if code is not None:
            self.code = code
        if label is not None:
            self.label = label
        if message is not None:
            self.message = message
        if data is not None:
            self.data = data

    @property
    def code(self):
        """Gets the code of this InlineResponse2007.  # noqa: E501

        Response code. `0` = success; `2002` = user not logged in; `50105` = parameter validation failed; `10001` = coupon record does not exist or does not belong to current user; `10000` = invalid parameter (e.g., task coupon missing coupon_info)  # noqa: E501

        :return: The code of this InlineResponse2007.  # noqa: E501
        :rtype: int
        """
        return self._code

    @code.setter
    def code(self, code):
        """Sets the code of this InlineResponse2007.

        Response code. `0` = success; `2002` = user not logged in; `50105` = parameter validation failed; `10001` = coupon record does not exist or does not belong to current user; `10000` = invalid parameter (e.g., task coupon missing coupon_info)  # noqa: E501

        :param code: The code of this InlineResponse2007.  # noqa: E501
        :type: int
        """
        allowed_values = [0, 2002, 50105, 10001, 10000]  # noqa: E501
        if self.local_vars_configuration.client_side_validation and code not in allowed_values:  # noqa: E501
            raise ValueError(
                "Invalid value for `code` ({0}), must be one of {1}"  # noqa: E501
                .format(code, allowed_values)
            )

        self._code = code

    @property
    def label(self):
        """Gets the label of this InlineResponse2007.  # noqa: E501

        Error identifier code. Empty string on success, machine-readable error label on error  # noqa: E501

        :return: The label of this InlineResponse2007.  # noqa: E501
        :rtype: str
        """
        return self._label

    @label.setter
    def label(self, label):
        """Sets the label of this InlineResponse2007.

        Error identifier code. Empty string on success, machine-readable error label on error  # noqa: E501

        :param label: The label of this InlineResponse2007.  # noqa: E501
        :type: str
        """

        self._label = label

    @property
    def message(self):
        """Gets the message of this InlineResponse2007.  # noqa: E501


        :return: The message of this InlineResponse2007.  # noqa: E501
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this InlineResponse2007.


        :param message: The message of this InlineResponse2007.  # noqa: E501
        :type: str
        """

        self._message = message

    @property
    def data(self):
        """Gets the data of this InlineResponse2007.  # noqa: E501


        :return: The data of this InlineResponse2007.  # noqa: E501
        :rtype: InlineResponse2007Data
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this InlineResponse2007.


        :param data: The data of this InlineResponse2007.  # noqa: E501
        :type: InlineResponse2007Data
        """

        self._data = data

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse2007):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, InlineResponse2007):
            return True

        return self.to_dict() != other.to_dict()
