# coding: utf-8

"""
    Gate API

    Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.  # noqa: E501

    Contact: support@mail.gate.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from gate_api.configuration import Configuration


class InlineResponse20016DataConvertInfo(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'convert_type': 'str',
        'convert_status': 'str',
        'pre_rate': 'str',
        'rate': 'str',
        'pre_fiat_rate': 'str',
        'fiat_rate': 'str',
        'amount': 'str',
        'convert_amount': 'str',
        'slippage': 'str',
        'status': 'str'
    }

    attribute_map = {
        'convert_type': 'convert_type',
        'convert_status': 'convert_status',
        'pre_rate': 'pre_rate',
        'rate': 'rate',
        'pre_fiat_rate': 'pre_fiat_rate',
        'fiat_rate': 'fiat_rate',
        'amount': 'amount',
        'convert_amount': 'convert_amount',
        'slippage': 'slippage',
        'status': 'status'
    }

    def __init__(self, convert_type=None, convert_status=None, pre_rate=None, rate=None, pre_fiat_rate=None, fiat_rate=None, amount=None, convert_amount=None, slippage=None, status=None, local_vars_configuration=None):  # noqa: E501
        # type: (str, str, str, str, str, str, str, str, str, str, Configuration) -> None
        """InlineResponse20016DataConvertInfo - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._convert_type = None
        self._convert_status = None
        self._pre_rate = None
        self._rate = None
        self._pre_fiat_rate = None
        self._fiat_rate = None
        self._amount = None
        self._convert_amount = None
        self._slippage = None
        self._status = None
        self.discriminator = None

        self.convert_type = convert_type
        self.convert_status = convert_status
        self.pre_rate = pre_rate
        self.rate = rate
        self.pre_fiat_rate = pre_fiat_rate
        self.fiat_rate = fiat_rate
        self.amount = amount
        self.convert_amount = convert_amount
        self.slippage = slippage
        self.status = status

    @property
    def convert_type(self):
        """Gets the convert_type of this InlineResponse20016DataConvertInfo.  # noqa: E501

        Flash swap target currency  # noqa: E501

        :return: The convert_type of this InlineResponse20016DataConvertInfo.  # noqa: E501
        :rtype: str
        """
        return self._convert_type

    @convert_type.setter
    def convert_type(self, convert_type):
        """Sets the convert_type of this InlineResponse20016DataConvertInfo.

        Flash swap target currency  # noqa: E501

        :param convert_type: The convert_type of this InlineResponse20016DataConvertInfo.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and convert_type is None:  # noqa: E501
            raise ValueError("Invalid value for `convert_type`, must not be `None`")  # noqa: E501

        self._convert_type = convert_type

    @property
    def convert_status(self):
        """Gets the convert_status of this InlineResponse20016DataConvertInfo.  # noqa: E501

        Flash swap order status  # noqa: E501

        :return: The convert_status of this InlineResponse20016DataConvertInfo.  # noqa: E501
        :rtype: str
        """
        return self._convert_status

    @convert_status.setter
    def convert_status(self, convert_status):
        """Sets the convert_status of this InlineResponse20016DataConvertInfo.

        Flash swap order status  # noqa: E501

        :param convert_status: The convert_status of this InlineResponse20016DataConvertInfo.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and convert_status is None:  # noqa: E501
            raise ValueError("Invalid value for `convert_status`, must not be `None`")  # noqa: E501

        self._convert_status = convert_status

    @property
    def pre_rate(self):
        """Gets the pre_rate of this InlineResponse20016DataConvertInfo.  # noqa: E501

        Expected price when placing order  # noqa: E501

        :return: The pre_rate of this InlineResponse20016DataConvertInfo.  # noqa: E501
        :rtype: str
        """
        return self._pre_rate

    @pre_rate.setter
    def pre_rate(self, pre_rate):
        """Sets the pre_rate of this InlineResponse20016DataConvertInfo.

        Expected price when placing order  # noqa: E501

        :param pre_rate: The pre_rate of this InlineResponse20016DataConvertInfo.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and pre_rate is None:  # noqa: E501
            raise ValueError("Invalid value for `pre_rate`, must not be `None`")  # noqa: E501

        self._pre_rate = pre_rate

    @property
    def rate(self):
        """Gets the rate of this InlineResponse20016DataConvertInfo.  # noqa: E501

        Execution price  # noqa: E501

        :return: The rate of this InlineResponse20016DataConvertInfo.  # noqa: E501
        :rtype: str
        """
        return self._rate

    @rate.setter
    def rate(self, rate):
        """Sets the rate of this InlineResponse20016DataConvertInfo.

        Execution price  # noqa: E501

        :param rate: The rate of this InlineResponse20016DataConvertInfo.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and rate is None:  # noqa: E501
            raise ValueError("Invalid value for `rate`, must not be `None`")  # noqa: E501

        self._rate = rate

    @property
    def pre_fiat_rate(self):
        """Gets the pre_fiat_rate of this InlineResponse20016DataConvertInfo.  # noqa: E501

        Expected fiat price when placing order  # noqa: E501

        :return: The pre_fiat_rate of this InlineResponse20016DataConvertInfo.  # noqa: E501
        :rtype: str
        """
        return self._pre_fiat_rate

    @pre_fiat_rate.setter
    def pre_fiat_rate(self, pre_fiat_rate):
        """Sets the pre_fiat_rate of this InlineResponse20016DataConvertInfo.

        Expected fiat price when placing order  # noqa: E501

        :param pre_fiat_rate: The pre_fiat_rate of this InlineResponse20016DataConvertInfo.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and pre_fiat_rate is None:  # noqa: E501
            raise ValueError("Invalid value for `pre_fiat_rate`, must not be `None`")  # noqa: E501

        self._pre_fiat_rate = pre_fiat_rate

    @property
    def fiat_rate(self):
        """Gets the fiat_rate of this InlineResponse20016DataConvertInfo.  # noqa: E501

        Fiat price at execution  # noqa: E501

        :return: The fiat_rate of this InlineResponse20016DataConvertInfo.  # noqa: E501
        :rtype: str
        """
        return self._fiat_rate

    @fiat_rate.setter
    def fiat_rate(self, fiat_rate):
        """Sets the fiat_rate of this InlineResponse20016DataConvertInfo.

        Fiat price at execution  # noqa: E501

        :param fiat_rate: The fiat_rate of this InlineResponse20016DataConvertInfo.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and fiat_rate is None:  # noqa: E501
            raise ValueError("Invalid value for `fiat_rate`, must not be `None`")  # noqa: E501

        self._fiat_rate = fiat_rate

    @property
    def amount(self):
        """Gets the amount of this InlineResponse20016DataConvertInfo.  # noqa: E501

        Size  # noqa: E501

        :return: The amount of this InlineResponse20016DataConvertInfo.  # noqa: E501
        :rtype: str
        """
        return self._amount

    @amount.setter
    def amount(self, amount):
        """Sets the amount of this InlineResponse20016DataConvertInfo.

        Size  # noqa: E501

        :param amount: The amount of this InlineResponse20016DataConvertInfo.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and amount is None:  # noqa: E501
            raise ValueError("Invalid value for `amount`, must not be `None`")  # noqa: E501

        self._amount = amount

    @property
    def convert_amount(self):
        """Gets the convert_amount of this InlineResponse20016DataConvertInfo.  # noqa: E501

        Swap Amount  # noqa: E501

        :return: The convert_amount of this InlineResponse20016DataConvertInfo.  # noqa: E501
        :rtype: str
        """
        return self._convert_amount

    @convert_amount.setter
    def convert_amount(self, convert_amount):
        """Sets the convert_amount of this InlineResponse20016DataConvertInfo.

        Swap Amount  # noqa: E501

        :param convert_amount: The convert_amount of this InlineResponse20016DataConvertInfo.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and convert_amount is None:  # noqa: E501
            raise ValueError("Invalid value for `convert_amount`, must not be `None`")  # noqa: E501

        self._convert_amount = convert_amount

    @property
    def slippage(self):
        """Gets the slippage of this InlineResponse20016DataConvertInfo.  # noqa: E501

        Slippage calculation: slippage = (expected price when placing order - real-time price during auto swap) / expected price when placing order  # noqa: E501

        :return: The slippage of this InlineResponse20016DataConvertInfo.  # noqa: E501
        :rtype: str
        """
        return self._slippage

    @slippage.setter
    def slippage(self, slippage):
        """Sets the slippage of this InlineResponse20016DataConvertInfo.

        Slippage calculation: slippage = (expected price when placing order - real-time price during auto swap) / expected price when placing order  # noqa: E501

        :param slippage: The slippage of this InlineResponse20016DataConvertInfo.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and slippage is None:  # noqa: E501
            raise ValueError("Invalid value for `slippage`, must not be `None`")  # noqa: E501

        self._slippage = slippage

    @property
    def status(self):
        """Gets the status of this InlineResponse20016DataConvertInfo.  # noqa: E501

        Flash swap order display status  # noqa: E501

        :return: The status of this InlineResponse20016DataConvertInfo.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this InlineResponse20016DataConvertInfo.

        Flash swap order display status  # noqa: E501

        :param status: The status of this InlineResponse20016DataConvertInfo.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and status is None:  # noqa: E501
            raise ValueError("Invalid value for `status`, must not be `None`")  # noqa: E501

        self._status = status

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse20016DataConvertInfo):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, InlineResponse20016DataConvertInfo):
            return True

        return self.to_dict() != other.to_dict()
