# coding: utf-8

"""
    Gate API

    Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.  # noqa: E501

    Contact: support@mail.gate.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from gate_api.configuration import Configuration


class LaunchPoolV4PledgeRecord(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'create_timest': 'str',
        'reward_coin': 'str',
        'coin': 'str',
        'type': 'int',
        'amount': 'str',
        'id': 'int'
    }

    attribute_map = {
        'create_timest': 'create_timest',
        'reward_coin': 'reward_coin',
        'coin': 'coin',
        'type': 'type',
        'amount': 'amount',
        'id': 'id'
    }

    def __init__(self, create_timest=None, reward_coin=None, coin=None, type=None, amount=None, id=None, local_vars_configuration=None):  # noqa: E501
        # type: (str, str, str, int, str, int, Configuration) -> None
        """LaunchPoolV4PledgeRecord - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._create_timest = None
        self._reward_coin = None
        self._coin = None
        self._type = None
        self._amount = None
        self._id = None
        self.discriminator = None

        self.create_timest = create_timest
        self.reward_coin = reward_coin
        self.coin = coin
        self.type = type
        self.amount = amount
        self.id = id

    @property
    def create_timest(self):
        """Gets the create_timest of this LaunchPoolV4PledgeRecord.  # noqa: E501

        Creation date  # noqa: E501

        :return: The create_timest of this LaunchPoolV4PledgeRecord.  # noqa: E501
        :rtype: str
        """
        return self._create_timest

    @create_timest.setter
    def create_timest(self, create_timest):
        """Sets the create_timest of this LaunchPoolV4PledgeRecord.

        Creation date  # noqa: E501

        :param create_timest: The create_timest of this LaunchPoolV4PledgeRecord.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and create_timest is None:  # noqa: E501
            raise ValueError("Invalid value for `create_timest`, must not be `None`")  # noqa: E501

        self._create_timest = create_timest

    @property
    def reward_coin(self):
        """Gets the reward_coin of this LaunchPoolV4PledgeRecord.  # noqa: E501

        Reward currency  # noqa: E501

        :return: The reward_coin of this LaunchPoolV4PledgeRecord.  # noqa: E501
        :rtype: str
        """
        return self._reward_coin

    @reward_coin.setter
    def reward_coin(self, reward_coin):
        """Sets the reward_coin of this LaunchPoolV4PledgeRecord.

        Reward currency  # noqa: E501

        :param reward_coin: The reward_coin of this LaunchPoolV4PledgeRecord.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and reward_coin is None:  # noqa: E501
            raise ValueError("Invalid value for `reward_coin`, must not be `None`")  # noqa: E501

        self._reward_coin = reward_coin

    @property
    def coin(self):
        """Gets the coin of this LaunchPoolV4PledgeRecord.  # noqa: E501

        Collateral currency  # noqa: E501

        :return: The coin of this LaunchPoolV4PledgeRecord.  # noqa: E501
        :rtype: str
        """
        return self._coin

    @coin.setter
    def coin(self, coin):
        """Sets the coin of this LaunchPoolV4PledgeRecord.

        Collateral currency  # noqa: E501

        :param coin: The coin of this LaunchPoolV4PledgeRecord.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and coin is None:  # noqa: E501
            raise ValueError("Invalid value for `coin`, must not be `None`")  # noqa: E501

        self._coin = coin

    @property
    def type(self):
        """Gets the type of this LaunchPoolV4PledgeRecord.  # noqa: E501

        Type: 1 for pledge, 2 for redemption  # noqa: E501

        :return: The type of this LaunchPoolV4PledgeRecord.  # noqa: E501
        :rtype: int
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this LaunchPoolV4PledgeRecord.

        Type: 1 for pledge, 2 for redemption  # noqa: E501

        :param type: The type of this LaunchPoolV4PledgeRecord.  # noqa: E501
        :type: int
        """
        if self.local_vars_configuration.client_side_validation and type is None:  # noqa: E501
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type

    @property
    def amount(self):
        """Gets the amount of this LaunchPoolV4PledgeRecord.  # noqa: E501

        Size  # noqa: E501

        :return: The amount of this LaunchPoolV4PledgeRecord.  # noqa: E501
        :rtype: str
        """
        return self._amount

    @amount.setter
    def amount(self, amount):
        """Sets the amount of this LaunchPoolV4PledgeRecord.

        Size  # noqa: E501

        :param amount: The amount of this LaunchPoolV4PledgeRecord.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and amount is None:  # noqa: E501
            raise ValueError("Invalid value for `amount`, must not be `None`")  # noqa: E501

        self._amount = amount

    @property
    def id(self):
        """Gets the id of this LaunchPoolV4PledgeRecord.  # noqa: E501

        Record ID  # noqa: E501

        :return: The id of this LaunchPoolV4PledgeRecord.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this LaunchPoolV4PledgeRecord.

        Record ID  # noqa: E501

        :param id: The id of this LaunchPoolV4PledgeRecord.  # noqa: E501
        :type: int
        """
        if self.local_vars_configuration.client_side_validation and id is None:  # noqa: E501
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, LaunchPoolV4PledgeRecord):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, LaunchPoolV4PledgeRecord):
            return True

        return self.to_dict() != other.to_dict()
