# coding: utf-8

"""
    Gate API

    Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.  # noqa: E501

    Contact: support@mail.gate.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from gate_api.configuration import Configuration


class LaunchPoolV4Project(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'pid': 'int',
        'name': 'str',
        'total_amount': 'str',
        'start_timest': 'int',
        'end_timest': 'int',
        'days': 'int',
        'project_state': 'int',
        'reward_pools': 'list[LaunchPoolV4RewardPool]'
    }

    attribute_map = {
        'pid': 'pid',
        'name': 'name',
        'total_amount': 'total_amount',
        'start_timest': 'start_timest',
        'end_timest': 'end_timest',
        'days': 'days',
        'project_state': 'project_state',
        'reward_pools': 'reward_pools'
    }

    def __init__(self, pid=None, name=None, total_amount=None, start_timest=None, end_timest=None, days=None, project_state=None, reward_pools=None, local_vars_configuration=None):  # noqa: E501
        # type: (int, str, str, int, int, int, int, list[LaunchPoolV4RewardPool], Configuration) -> None
        """LaunchPoolV4Project - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._pid = None
        self._name = None
        self._total_amount = None
        self._start_timest = None
        self._end_timest = None
        self._days = None
        self._project_state = None
        self._reward_pools = None
        self.discriminator = None

        self.pid = pid
        self.name = name
        self.total_amount = total_amount
        self.start_timest = start_timest
        self.end_timest = end_timest
        self.days = days
        self.project_state = project_state
        self.reward_pools = reward_pools

    @property
    def pid(self):
        """Gets the pid of this LaunchPoolV4Project.  # noqa: E501

        Product ID  # noqa: E501

        :return: The pid of this LaunchPoolV4Project.  # noqa: E501
        :rtype: int
        """
        return self._pid

    @pid.setter
    def pid(self, pid):
        """Sets the pid of this LaunchPoolV4Project.

        Product ID  # noqa: E501

        :param pid: The pid of this LaunchPoolV4Project.  # noqa: E501
        :type: int
        """
        if self.local_vars_configuration.client_side_validation and pid is None:  # noqa: E501
            raise ValueError("Invalid value for `pid`, must not be `None`")  # noqa: E501

        self._pid = pid

    @property
    def name(self):
        """Gets the name of this LaunchPoolV4Project.  # noqa: E501

        Product Name  # noqa: E501

        :return: The name of this LaunchPoolV4Project.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this LaunchPoolV4Project.

        Product Name  # noqa: E501

        :param name: The name of this LaunchPoolV4Project.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and name is None:  # noqa: E501
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def total_amount(self):
        """Gets the total_amount of this LaunchPoolV4Project.  # noqa: E501

        Total rewards  # noqa: E501

        :return: The total_amount of this LaunchPoolV4Project.  # noqa: E501
        :rtype: str
        """
        return self._total_amount

    @total_amount.setter
    def total_amount(self, total_amount):
        """Sets the total_amount of this LaunchPoolV4Project.

        Total rewards  # noqa: E501

        :param total_amount: The total_amount of this LaunchPoolV4Project.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and total_amount is None:  # noqa: E501
            raise ValueError("Invalid value for `total_amount`, must not be `None`")  # noqa: E501

        self._total_amount = total_amount

    @property
    def start_timest(self):
        """Gets the start_timest of this LaunchPoolV4Project.  # noqa: E501

        Project start timestamp  # noqa: E501

        :return: The start_timest of this LaunchPoolV4Project.  # noqa: E501
        :rtype: int
        """
        return self._start_timest

    @start_timest.setter
    def start_timest(self, start_timest):
        """Sets the start_timest of this LaunchPoolV4Project.

        Project start timestamp  # noqa: E501

        :param start_timest: The start_timest of this LaunchPoolV4Project.  # noqa: E501
        :type: int
        """
        if self.local_vars_configuration.client_side_validation and start_timest is None:  # noqa: E501
            raise ValueError("Invalid value for `start_timest`, must not be `None`")  # noqa: E501

        self._start_timest = start_timest

    @property
    def end_timest(self):
        """Gets the end_timest of this LaunchPoolV4Project.  # noqa: E501

        Project end timestamp  # noqa: E501

        :return: The end_timest of this LaunchPoolV4Project.  # noqa: E501
        :rtype: int
        """
        return self._end_timest

    @end_timest.setter
    def end_timest(self, end_timest):
        """Sets the end_timest of this LaunchPoolV4Project.

        Project end timestamp  # noqa: E501

        :param end_timest: The end_timest of this LaunchPoolV4Project.  # noqa: E501
        :type: int
        """
        if self.local_vars_configuration.client_side_validation and end_timest is None:  # noqa: E501
            raise ValueError("Invalid value for `end_timest`, must not be `None`")  # noqa: E501

        self._end_timest = end_timest

    @property
    def days(self):
        """Gets the days of this LaunchPoolV4Project.  # noqa: E501

        Staking period (in days)  # noqa: E501

        :return: The days of this LaunchPoolV4Project.  # noqa: E501
        :rtype: int
        """
        return self._days

    @days.setter
    def days(self, days):
        """Sets the days of this LaunchPoolV4Project.

        Staking period (in days)  # noqa: E501

        :param days: The days of this LaunchPoolV4Project.  # noqa: E501
        :type: int
        """
        if self.local_vars_configuration.client_side_validation and days is None:  # noqa: E501
            raise ValueError("Invalid value for `days`, must not be `None`")  # noqa: E501

        self._days = days

    @property
    def project_state(self):
        """Gets the project_state of this LaunchPoolV4Project.  # noqa: E501

        Project status: 1 for ongoing, 2 for warming up, 3 for ended  # noqa: E501

        :return: The project_state of this LaunchPoolV4Project.  # noqa: E501
        :rtype: int
        """
        return self._project_state

    @project_state.setter
    def project_state(self, project_state):
        """Sets the project_state of this LaunchPoolV4Project.

        Project status: 1 for ongoing, 2 for warming up, 3 for ended  # noqa: E501

        :param project_state: The project_state of this LaunchPoolV4Project.  # noqa: E501
        :type: int
        """
        if self.local_vars_configuration.client_side_validation and project_state is None:  # noqa: E501
            raise ValueError("Invalid value for `project_state`, must not be `None`")  # noqa: E501
        allowed_values = [1, 2, 3]  # noqa: E501
        if self.local_vars_configuration.client_side_validation and project_state not in allowed_values:  # noqa: E501
            raise ValueError(
                "Invalid value for `project_state` ({0}), must be one of {1}"  # noqa: E501
                .format(project_state, allowed_values)
            )

        self._project_state = project_state

    @property
    def reward_pools(self):
        """Gets the reward_pools of this LaunchPoolV4Project.  # noqa: E501

        Collateral currency list  # noqa: E501

        :return: The reward_pools of this LaunchPoolV4Project.  # noqa: E501
        :rtype: list[LaunchPoolV4RewardPool]
        """
        return self._reward_pools

    @reward_pools.setter
    def reward_pools(self, reward_pools):
        """Sets the reward_pools of this LaunchPoolV4Project.

        Collateral currency list  # noqa: E501

        :param reward_pools: The reward_pools of this LaunchPoolV4Project.  # noqa: E501
        :type: list[LaunchPoolV4RewardPool]
        """
        if self.local_vars_configuration.client_side_validation and reward_pools is None:  # noqa: E501
            raise ValueError("Invalid value for `reward_pools`, must not be `None`")  # noqa: E501

        self._reward_pools = reward_pools

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, LaunchPoolV4Project):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, LaunchPoolV4Project):
            return True

        return self.to_dict() != other.to_dict()
