# coding: utf-8

"""
    Gate API

    Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.  # noqa: E501

    Contact: support@mail.gate.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from gate_api.configuration import Configuration


class ListUserCouponsResponseDataList(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'int',
        'details_id': 'int',
        'coupon_type': 'str',
        'name': 'str',
        'amount': 'str',
        'origin_amount': 'str',
        'currency': 'str',
        'rule_new': 'str',
        'status': 'str',
        'jump_url': 'ListUserCouponsResponseDataJumpUrl',
        'help_url': 'ListUserCouponsResponseDataHelpUrl',
        'expire_time': 'int',
        'expire_time_order_by': 'int',
        'expire_second': 'int',
        'has_usage_history': 'bool',
        'has_progress': 'bool',
        'progress_config': 'ListUserCouponsResponseDataProgressConfig',
        'activation_info': 'object',
        'is_task_coupon': 'int',
        'upgrade_toast': 'bool',
        'task_title': 'str',
        'task_desc': 'str',
        'task_start_at': 'int',
        'task_expire_at': 'int',
        'task_completed_at': 'int',
        'extra': 'list[object]'
    }

    attribute_map = {
        'id': 'id',
        'details_id': 'details_id',
        'coupon_type': 'coupon_type',
        'name': 'name',
        'amount': 'amount',
        'origin_amount': 'origin_amount',
        'currency': 'currency',
        'rule_new': 'rule_new',
        'status': 'status',
        'jump_url': 'jump_url',
        'help_url': 'help_url',
        'expire_time': 'expire_time',
        'expire_time_order_by': 'expire_time_order_by',
        'expire_second': 'expire_second',
        'has_usage_history': 'has_usage_history',
        'has_progress': 'has_progress',
        'progress_config': 'progress_config',
        'activation_info': 'activation_info',
        'is_task_coupon': 'is_task_coupon',
        'upgrade_toast': 'upgrade_toast',
        'task_title': 'task_title',
        'task_desc': 'task_desc',
        'task_start_at': 'task_start_at',
        'task_expire_at': 'task_expire_at',
        'task_completed_at': 'task_completed_at',
        'extra': 'extra'
    }

    def __init__(self, id=None, details_id=None, coupon_type=None, name=None, amount=None, origin_amount=None, currency=None, rule_new=None, status=None, jump_url=None, help_url=None, expire_time=None, expire_time_order_by=None, expire_second=None, has_usage_history=None, has_progress=None, progress_config=None, activation_info=None, is_task_coupon=None, upgrade_toast=None, task_title=None, task_desc=None, task_start_at=None, task_expire_at=None, task_completed_at=None, extra=None, local_vars_configuration=None):  # noqa: E501
        # type: (int, int, str, str, str, str, str, str, str, ListUserCouponsResponseDataJumpUrl, ListUserCouponsResponseDataHelpUrl, int, int, int, bool, bool, ListUserCouponsResponseDataProgressConfig, object, int, bool, str, str, int, int, int, list[object], Configuration) -> None
        """ListUserCouponsResponseDataList - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._id = None
        self._details_id = None
        self._coupon_type = None
        self._name = None
        self._amount = None
        self._origin_amount = None
        self._currency = None
        self._rule_new = None
        self._status = None
        self._jump_url = None
        self._help_url = None
        self._expire_time = None
        self._expire_time_order_by = None
        self._expire_second = None
        self._has_usage_history = None
        self._has_progress = None
        self._progress_config = None
        self._activation_info = None
        self._is_task_coupon = None
        self._upgrade_toast = None
        self._task_title = None
        self._task_desc = None
        self._task_start_at = None
        self._task_expire_at = None
        self._task_completed_at = None
        self._extra = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if details_id is not None:
            self.details_id = details_id
        if coupon_type is not None:
            self.coupon_type = coupon_type
        if name is not None:
            self.name = name
        if amount is not None:
            self.amount = amount
        if origin_amount is not None:
            self.origin_amount = origin_amount
        if currency is not None:
            self.currency = currency
        if rule_new is not None:
            self.rule_new = rule_new
        if status is not None:
            self.status = status
        if jump_url is not None:
            self.jump_url = jump_url
        if help_url is not None:
            self.help_url = help_url
        if expire_time is not None:
            self.expire_time = expire_time
        if expire_time_order_by is not None:
            self.expire_time_order_by = expire_time_order_by
        if expire_second is not None:
            self.expire_second = expire_second
        if has_usage_history is not None:
            self.has_usage_history = has_usage_history
        if has_progress is not None:
            self.has_progress = has_progress
        if progress_config is not None:
            self.progress_config = progress_config
        if activation_info is not None:
            self.activation_info = activation_info
        if is_task_coupon is not None:
            self.is_task_coupon = is_task_coupon
        if upgrade_toast is not None:
            self.upgrade_toast = upgrade_toast
        if task_title is not None:
            self.task_title = task_title
        if task_desc is not None:
            self.task_desc = task_desc
        if task_start_at is not None:
            self.task_start_at = task_start_at
        if task_expire_at is not None:
            self.task_expire_at = task_expire_at
        if task_completed_at is not None:
            self.task_completed_at = task_completed_at
        if extra is not None:
            self.extra = extra

    @property
    def id(self):
        """Gets the id of this ListUserCouponsResponseDataList.  # noqa: E501

        Coupon distribution record ID (coupon_send_issuing_log.id), used as `last_id` for cursor-based pagination  # noqa: E501

        :return: The id of this ListUserCouponsResponseDataList.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ListUserCouponsResponseDataList.

        Coupon distribution record ID (coupon_send_issuing_log.id), used as `last_id` for cursor-based pagination  # noqa: E501

        :param id: The id of this ListUserCouponsResponseDataList.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def details_id(self):
        """Gets the details_id of this ListUserCouponsResponseDataList.  # noqa: E501

        User coupon detail table primary key (separate table per type). This field is 0 for task coupons, has value for regular coupons  # noqa: E501

        :return: The details_id of this ListUserCouponsResponseDataList.  # noqa: E501
        :rtype: int
        """
        return self._details_id

    @details_id.setter
    def details_id(self, details_id):
        """Sets the details_id of this ListUserCouponsResponseDataList.

        User coupon detail table primary key (separate table per type). This field is 0 for task coupons, has value for regular coupons  # noqa: E501

        :param details_id: The details_id of this ListUserCouponsResponseDataList.  # noqa: E501
        :type: int
        """

        self._details_id = details_id

    @property
    def coupon_type(self):
        """Gets the coupon_type of this ListUserCouponsResponseDataList.  # noqa: E501

        Coupon type, enum values same as the `type` parameter  # noqa: E501

        :return: The coupon_type of this ListUserCouponsResponseDataList.  # noqa: E501
        :rtype: str
        """
        return self._coupon_type

    @coupon_type.setter
    def coupon_type(self, coupon_type):
        """Sets the coupon_type of this ListUserCouponsResponseDataList.

        Coupon type, enum values same as the `type` parameter  # noqa: E501

        :param coupon_type: The coupon_type of this ListUserCouponsResponseDataList.  # noqa: E501
        :type: str
        """

        self._coupon_type = coupon_type

    @property
    def name(self):
        """Gets the name of this ListUserCouponsResponseDataList.  # noqa: E501

        Coupon display name (i18n translated)  # noqa: E501

        :return: The name of this ListUserCouponsResponseDataList.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ListUserCouponsResponseDataList.

        Coupon display name (i18n translated)  # noqa: E501

        :param name: The name of this ListUserCouponsResponseDataList.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def amount(self):
        """Gets the amount of this ListUserCouponsResponseDataList.  # noqa: E501

        Coupon denomination (formatted string with thousand separators). Meaning by type: point card = balance, interest rate boost coupon = interest rate percentage (e.g., '5%'), VIP trial card = VIP level number, position voucher = face value × leverage, others = face value  # noqa: E501

        :return: The amount of this ListUserCouponsResponseDataList.  # noqa: E501
        :rtype: str
        """
        return self._amount

    @amount.setter
    def amount(self, amount):
        """Sets the amount of this ListUserCouponsResponseDataList.

        Coupon denomination (formatted string with thousand separators). Meaning by type: point card = balance, interest rate boost coupon = interest rate percentage (e.g., '5%'), VIP trial card = VIP level number, position voucher = face value × leverage, others = face value  # noqa: E501

        :param amount: The amount of this ListUserCouponsResponseDataList.  # noqa: E501
        :type: str
        """

        self._amount = amount

    @property
    def origin_amount(self):
        """Gets the origin_amount of this ListUserCouponsResponseDataList.  # noqa: E501

        Original denomination (string with trailing zeros removed). Only returned for point card type, other types do not have this field  # noqa: E501

        :return: The origin_amount of this ListUserCouponsResponseDataList.  # noqa: E501
        :rtype: str
        """
        return self._origin_amount

    @origin_amount.setter
    def origin_amount(self, origin_amount):
        """Sets the origin_amount of this ListUserCouponsResponseDataList.

        Original denomination (string with trailing zeros removed). Only returned for point card type, other types do not have this field  # noqa: E501

        :param origin_amount: The origin_amount of this ListUserCouponsResponseDataList.  # noqa: E501
        :type: str
        """

        self._origin_amount = origin_amount

    @property
    def currency(self):
        """Gets the currency of this ListUserCouponsResponseDataList.  # noqa: E501

        Denomination unit. Point card = 'POINT', interest rate boost coupon = 'APR', VIP trial card = 'VIP', Alpha cash coupon = base currency, others = uppercase currency symbol (e.g., 'USDT'/'GT')  # noqa: E501

        :return: The currency of this ListUserCouponsResponseDataList.  # noqa: E501
        :rtype: str
        """
        return self._currency

    @currency.setter
    def currency(self, currency):
        """Sets the currency of this ListUserCouponsResponseDataList.

        Denomination unit. Point card = 'POINT', interest rate boost coupon = 'APR', VIP trial card = 'VIP', Alpha cash coupon = base currency, others = uppercase currency symbol (e.g., 'USDT'/'GT')  # noqa: E501

        :param currency: The currency of this ListUserCouponsResponseDataList.  # noqa: E501
        :type: str
        """

        self._currency = currency

    @property
    def rule_new(self):
        """Gets the rule_new of this ListUserCouponsResponseDataList.  # noqa: E501

        Coupon usage rule text. List endpoint always returns empty string \"\", only detail endpoint returns actual value  # noqa: E501

        :return: The rule_new of this ListUserCouponsResponseDataList.  # noqa: E501
        :rtype: str
        """
        return self._rule_new

    @rule_new.setter
    def rule_new(self, rule_new):
        """Sets the rule_new of this ListUserCouponsResponseDataList.

        Coupon usage rule text. List endpoint always returns empty string \"\", only detail endpoint returns actual value  # noqa: E501

        :param rule_new: The rule_new of this ListUserCouponsResponseDataList.  # noqa: E501
        :type: str
        """

        self._rule_new = rule_new

    @property
    def status(self):
        """Gets the status of this ListUserCouponsResponseDataList.  # noqa: E501

        Coupon status. Regular coupon: NOT_ACTIVE (pending activation), ACTIVATED (activated), TO_BE_USED (to be used), EXPIRED (expired), RECYCLED (recycled), INVALID (invalidated), USED (used), UNKNOWN (unknown), LOCKED (locked, P2P only). Task coupon: TASK_START (task not started), TASK_WAIT (task in progress), TASK_DONE (task completed, processing), TASK_EXPIRED (task not completed, expired), TASK_NOT_STARTED_EXPIRED (not started, expired), TASK_RECEIVE_SUCCESS (reward claimed successfully), TASK_RECEIVE_FAIL (reward claim failed)  # noqa: E501

        :return: The status of this ListUserCouponsResponseDataList.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this ListUserCouponsResponseDataList.

        Coupon status. Regular coupon: NOT_ACTIVE (pending activation), ACTIVATED (activated), TO_BE_USED (to be used), EXPIRED (expired), RECYCLED (recycled), INVALID (invalidated), USED (used), UNKNOWN (unknown), LOCKED (locked, P2P only). Task coupon: TASK_START (task not started), TASK_WAIT (task in progress), TASK_DONE (task completed, processing), TASK_EXPIRED (task not completed, expired), TASK_NOT_STARTED_EXPIRED (not started, expired), TASK_RECEIVE_SUCCESS (reward claimed successfully), TASK_RECEIVE_FAIL (reward claim failed)  # noqa: E501

        :param status: The status of this ListUserCouponsResponseDataList.  # noqa: E501
        :type: str
        """
        allowed_values = ["NOT_ACTIVE", "ACTIVATED", "TO_BE_USED", "EXPIRED", "RECYCLED", "INVALID", "USED", "UNKNOWN", "LOCKED", "TASK_START", "TASK_WAIT", "TASK_DONE", "TASK_EXPIRED", "TASK_NOT_STARTED_EXPIRED", "TASK_RECEIVE_SUCCESS", "TASK_RECEIVE_FAIL"]  # noqa: E501
        if self.local_vars_configuration.client_side_validation and status not in allowed_values:  # noqa: E501
            raise ValueError(
                "Invalid value for `status` ({0}), must be one of {1}"  # noqa: E501
                .format(status, allowed_values)
            )

        self._status = status

    @property
    def jump_url(self):
        """Gets the jump_url of this ListUserCouponsResponseDataList.  # noqa: E501


        :return: The jump_url of this ListUserCouponsResponseDataList.  # noqa: E501
        :rtype: ListUserCouponsResponseDataJumpUrl
        """
        return self._jump_url

    @jump_url.setter
    def jump_url(self, jump_url):
        """Sets the jump_url of this ListUserCouponsResponseDataList.


        :param jump_url: The jump_url of this ListUserCouponsResponseDataList.  # noqa: E501
        :type: ListUserCouponsResponseDataJumpUrl
        """

        self._jump_url = jump_url

    @property
    def help_url(self):
        """Gets the help_url of this ListUserCouponsResponseDataList.  # noqa: E501


        :return: The help_url of this ListUserCouponsResponseDataList.  # noqa: E501
        :rtype: ListUserCouponsResponseDataHelpUrl
        """
        return self._help_url

    @help_url.setter
    def help_url(self, help_url):
        """Sets the help_url of this ListUserCouponsResponseDataList.


        :param help_url: The help_url of this ListUserCouponsResponseDataList.  # noqa: E501
        :type: ListUserCouponsResponseDataHelpUrl
        """

        self._help_url = help_url

    @property
    def expire_time(self):
        """Gets the expire_time of this ListUserCouponsResponseDataList.  # noqa: E501

        Expiration time (Unix timestamp). Some types replace this with actual expiration time after activation or use (e.g., contract_bonus uses expired_timest after activation). Point card type returns 0  # noqa: E501

        :return: The expire_time of this ListUserCouponsResponseDataList.  # noqa: E501
        :rtype: int
        """
        return self._expire_time

    @expire_time.setter
    def expire_time(self, expire_time):
        """Sets the expire_time of this ListUserCouponsResponseDataList.

        Expiration time (Unix timestamp). Some types replace this with actual expiration time after activation or use (e.g., contract_bonus uses expired_timest after activation). Point card type returns 0  # noqa: E501

        :param expire_time: The expire_time of this ListUserCouponsResponseDataList.  # noqa: E501
        :type: int
        """

        self._expire_time = expire_time

    @property
    def expire_time_order_by(self):
        """Gets the expire_time_order_by of this ListUserCouponsResponseDataList.  # noqa: E501

        Sorting expiration time (from the original expiration time of the distribution record, unaffected by activation). Used as the `expire_time` parameter for the next request in cursor-based pagination  # noqa: E501

        :return: The expire_time_order_by of this ListUserCouponsResponseDataList.  # noqa: E501
        :rtype: int
        """
        return self._expire_time_order_by

    @expire_time_order_by.setter
    def expire_time_order_by(self, expire_time_order_by):
        """Sets the expire_time_order_by of this ListUserCouponsResponseDataList.

        Sorting expiration time (from the original expiration time of the distribution record, unaffected by activation). Used as the `expire_time` parameter for the next request in cursor-based pagination  # noqa: E501

        :param expire_time_order_by: The expire_time_order_by of this ListUserCouponsResponseDataList.  # noqa: E501
        :type: int
        """

        self._expire_time_order_by = expire_time_order_by

    @property
    def expire_second(self):
        """Gets the expire_second of this ListUserCouponsResponseDataList.  # noqa: E501

        Seconds remaining until expiration. Returns 0 for expired or Point Card types  # noqa: E501

        :return: The expire_second of this ListUserCouponsResponseDataList.  # noqa: E501
        :rtype: int
        """
        return self._expire_second

    @expire_second.setter
    def expire_second(self, expire_second):
        """Sets the expire_second of this ListUserCouponsResponseDataList.

        Seconds remaining until expiration. Returns 0 for expired or Point Card types  # noqa: E501

        :param expire_second: The expire_second of this ListUserCouponsResponseDataList.  # noqa: E501
        :type: int
        """

        self._expire_second = expire_second

    @property
    def has_usage_history(self):
        """Gets the has_usage_history of this ListUserCouponsResponseDataList.  # noqa: E501

        Whether there is a usage history. Fixed as true for point card type, determined by type for others  # noqa: E501

        :return: The has_usage_history of this ListUserCouponsResponseDataList.  # noqa: E501
        :rtype: bool
        """
        return self._has_usage_history

    @has_usage_history.setter
    def has_usage_history(self, has_usage_history):
        """Sets the has_usage_history of this ListUserCouponsResponseDataList.

        Whether there is a usage history. Fixed as true for point card type, determined by type for others  # noqa: E501

        :param has_usage_history: The has_usage_history of this ListUserCouponsResponseDataList.  # noqa: E501
        :type: bool
        """

        self._has_usage_history = has_usage_history

    @property
    def has_progress(self):
        """Gets the has_progress of this ListUserCouponsResponseDataList.  # noqa: E501

        Whether to display a progress bar. Only true for commission_rebate, interest_voucher, and qualifying task coupons  # noqa: E501

        :return: The has_progress of this ListUserCouponsResponseDataList.  # noqa: E501
        :rtype: bool
        """
        return self._has_progress

    @has_progress.setter
    def has_progress(self, has_progress):
        """Sets the has_progress of this ListUserCouponsResponseDataList.

        Whether to display a progress bar. Only true for commission_rebate, interest_voucher, and qualifying task coupons  # noqa: E501

        :param has_progress: The has_progress of this ListUserCouponsResponseDataList.  # noqa: E501
        :type: bool
        """

        self._has_progress = has_progress

    @property
    def progress_config(self):
        """Gets the progress_config of this ListUserCouponsResponseDataList.  # noqa: E501


        :return: The progress_config of this ListUserCouponsResponseDataList.  # noqa: E501
        :rtype: ListUserCouponsResponseDataProgressConfig
        """
        return self._progress_config

    @progress_config.setter
    def progress_config(self, progress_config):
        """Sets the progress_config of this ListUserCouponsResponseDataList.


        :param progress_config: The progress_config of this ListUserCouponsResponseDataList.  # noqa: E501
        :type: ListUserCouponsResponseDataProgressConfig
        """

        self._progress_config = progress_config

    @property
    def activation_info(self):
        """Gets the activation_info of this ListUserCouponsResponseDataList.  # noqa: E501

        Type-specific activation information. Types without specific fields return empty object {}. Fields by type: interest_voucher={supported_pairs,transaction_type}; contract_bonus_new={received_expired_hour}; contract_bonus={check_unified_account_mode,received_expired_days,abtest}; commission_rebate={market,market_name}; robot_bonus={designated_bots}; position_voucher={symbols,leverage,need_user_funds,user_funds_amount,position_bonus}; tradfi_position_voucher={symbols,leverage,position_bonus}; etf_voucher={currency_markets,amount}  # noqa: E501

        :return: The activation_info of this ListUserCouponsResponseDataList.  # noqa: E501
        :rtype: object
        """
        return self._activation_info

    @activation_info.setter
    def activation_info(self, activation_info):
        """Sets the activation_info of this ListUserCouponsResponseDataList.

        Type-specific activation information. Types without specific fields return empty object {}. Fields by type: interest_voucher={supported_pairs,transaction_type}; contract_bonus_new={received_expired_hour}; contract_bonus={check_unified_account_mode,received_expired_days,abtest}; commission_rebate={market,market_name}; robot_bonus={designated_bots}; position_voucher={symbols,leverage,need_user_funds,user_funds_amount,position_bonus}; tradfi_position_voucher={symbols,leverage,position_bonus}; etf_voucher={currency_markets,amount}  # noqa: E501

        :param activation_info: The activation_info of this ListUserCouponsResponseDataList.  # noqa: E501
        :type: object
        """

        self._activation_info = activation_info

    @property
    def is_task_coupon(self):
        """Gets the is_task_coupon of this ListUserCouponsResponseDataList.  # noqa: E501

        Whether it is a task coupon. `0` = regular coupon; `1` = task coupon  # noqa: E501

        :return: The is_task_coupon of this ListUserCouponsResponseDataList.  # noqa: E501
        :rtype: int
        """
        return self._is_task_coupon

    @is_task_coupon.setter
    def is_task_coupon(self, is_task_coupon):
        """Sets the is_task_coupon of this ListUserCouponsResponseDataList.

        Whether it is a task coupon. `0` = regular coupon; `1` = task coupon  # noqa: E501

        :param is_task_coupon: The is_task_coupon of this ListUserCouponsResponseDataList.  # noqa: E501
        :type: int
        """
        allowed_values = [0, 1]  # noqa: E501
        if self.local_vars_configuration.client_side_validation and is_task_coupon not in allowed_values:  # noqa: E501
            raise ValueError(
                "Invalid value for `is_task_coupon` ({0}), must be one of {1}"  # noqa: E501
                .format(is_task_coupon, allowed_values)
            )

        self._is_task_coupon = is_task_coupon

    @property
    def upgrade_toast(self):
        """Gets the upgrade_toast of this ListUserCouponsResponseDataList.  # noqa: E501

        Whether to prompt the user to upgrade the App (true when app version is too old to support the coupon). Triggered types: copy_trading/alpha_voucher (Android<7320000/iOS<202507320000), commission_rebate subtype tradfi (Android<8040000/iOS<202608040000), etf_voucher (Android<8090000/iOS<202608090000), tradfi_position_voucher (Android<8100000/iOS<202508240000)  # noqa: E501

        :return: The upgrade_toast of this ListUserCouponsResponseDataList.  # noqa: E501
        :rtype: bool
        """
        return self._upgrade_toast

    @upgrade_toast.setter
    def upgrade_toast(self, upgrade_toast):
        """Sets the upgrade_toast of this ListUserCouponsResponseDataList.

        Whether to prompt the user to upgrade the App (true when app version is too old to support the coupon). Triggered types: copy_trading/alpha_voucher (Android<7320000/iOS<202507320000), commission_rebate subtype tradfi (Android<8040000/iOS<202608040000), etf_voucher (Android<8090000/iOS<202608090000), tradfi_position_voucher (Android<8100000/iOS<202508240000)  # noqa: E501

        :param upgrade_toast: The upgrade_toast of this ListUserCouponsResponseDataList.  # noqa: E501
        :type: bool
        """

        self._upgrade_toast = upgrade_toast

    @property
    def task_title(self):
        """Gets the task_title of this ListUserCouponsResponseDataList.  # noqa: E501

        Task title (only task coupons have value, regular coupons return empty string \"\")  # noqa: E501

        :return: The task_title of this ListUserCouponsResponseDataList.  # noqa: E501
        :rtype: str
        """
        return self._task_title

    @task_title.setter
    def task_title(self, task_title):
        """Sets the task_title of this ListUserCouponsResponseDataList.

        Task title (only task coupons have value, regular coupons return empty string \"\")  # noqa: E501

        :param task_title: The task_title of this ListUserCouponsResponseDataList.  # noqa: E501
        :type: str
        """

        self._task_title = task_title

    @property
    def task_desc(self):
        """Gets the task_desc of this ListUserCouponsResponseDataList.  # noqa: E501

        Task description (only task coupons have value, regular coupons return empty string \"\")  # noqa: E501

        :return: The task_desc of this ListUserCouponsResponseDataList.  # noqa: E501
        :rtype: str
        """
        return self._task_desc

    @task_desc.setter
    def task_desc(self, task_desc):
        """Sets the task_desc of this ListUserCouponsResponseDataList.

        Task description (only task coupons have value, regular coupons return empty string \"\")  # noqa: E501

        :param task_desc: The task_desc of this ListUserCouponsResponseDataList.  # noqa: E501
        :type: str
        """

        self._task_desc = task_desc

    @property
    def task_start_at(self):
        """Gets the task_start_at of this ListUserCouponsResponseDataList.  # noqa: E501

        Task start timestamp (Unix). Only has value for task coupons in TASK_EXPIRED status, otherwise 0  # noqa: E501

        :return: The task_start_at of this ListUserCouponsResponseDataList.  # noqa: E501
        :rtype: int
        """
        return self._task_start_at

    @task_start_at.setter
    def task_start_at(self, task_start_at):
        """Sets the task_start_at of this ListUserCouponsResponseDataList.

        Task start timestamp (Unix). Only has value for task coupons in TASK_EXPIRED status, otherwise 0  # noqa: E501

        :param task_start_at: The task_start_at of this ListUserCouponsResponseDataList.  # noqa: E501
        :type: int
        """

        self._task_start_at = task_start_at

    @property
    def task_expire_at(self):
        """Gets the task_expire_at of this ListUserCouponsResponseDataList.  # noqa: E501

        Task expiration timestamp (Unix). Currently fixed at 0, reserved field  # noqa: E501

        :return: The task_expire_at of this ListUserCouponsResponseDataList.  # noqa: E501
        :rtype: int
        """
        return self._task_expire_at

    @task_expire_at.setter
    def task_expire_at(self, task_expire_at):
        """Sets the task_expire_at of this ListUserCouponsResponseDataList.

        Task expiration timestamp (Unix). Currently fixed at 0, reserved field  # noqa: E501

        :param task_expire_at: The task_expire_at of this ListUserCouponsResponseDataList.  # noqa: E501
        :type: int
        """

        self._task_expire_at = task_expire_at

    @property
    def task_completed_at(self):
        """Gets the task_completed_at of this ListUserCouponsResponseDataList.  # noqa: E501

        Task completion timestamp (Unix). Currently fixed at 0, reserved field  # noqa: E501

        :return: The task_completed_at of this ListUserCouponsResponseDataList.  # noqa: E501
        :rtype: int
        """
        return self._task_completed_at

    @task_completed_at.setter
    def task_completed_at(self, task_completed_at):
        """Sets the task_completed_at of this ListUserCouponsResponseDataList.

        Task completion timestamp (Unix). Currently fixed at 0, reserved field  # noqa: E501

        :param task_completed_at: The task_completed_at of this ListUserCouponsResponseDataList.  # noqa: E501
        :type: int
        """

        self._task_completed_at = task_completed_at

    @property
    def extra(self):
        """Gets the extra of this ListUserCouponsResponseDataList.  # noqa: E501

        Extension fields. List endpoint always returns empty array [], only the detail endpoint has values  # noqa: E501

        :return: The extra of this ListUserCouponsResponseDataList.  # noqa: E501
        :rtype: list[object]
        """
        return self._extra

    @extra.setter
    def extra(self, extra):
        """Sets the extra of this ListUserCouponsResponseDataList.

        Extension fields. List endpoint always returns empty array [], only the detail endpoint has values  # noqa: E501

        :param extra: The extra of this ListUserCouponsResponseDataList.  # noqa: E501
        :type: list[object]
        """

        self._extra = extra

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ListUserCouponsResponseDataList):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ListUserCouponsResponseDataList):
            return True

        return self.to_dict() != other.to_dict()
