# coding: utf-8

"""
    Gate API

    Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.  # noqa: E501

    Contact: support@mail.gate.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from gate_api.configuration import Configuration


class ListLiveReplayResponseDataVideo(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'str',
        'stream_id': 'str',
        'title': 'str',
        'avatar': 'str',
        'nick': 'str',
        'nick_en': 'str',
        'cover': 'str',
        'watched': 'int',
        'subscription_required': 'bool',
        'has_subscribed': 'bool',
        'duration': 'int',
        'weight': 'int',
        'moments_uid': 'str',
        'session_id': 'str',
        'ended_at_format': 'str',
        'ended_at_type': 'int',
        'tier': 'int',
        'tag': 'str'
    }

    attribute_map = {
        'id': 'id',
        'stream_id': 'stream_id',
        'title': 'title',
        'avatar': 'avatar',
        'nick': 'nick',
        'nick_en': 'nick_en',
        'cover': 'cover',
        'watched': 'watched',
        'subscription_required': 'subscription_required',
        'has_subscribed': 'has_subscribed',
        'duration': 'duration',
        'weight': 'weight',
        'moments_uid': 'moments_uid',
        'session_id': 'session_id',
        'ended_at_format': 'ended_at_format',
        'ended_at_type': 'ended_at_type',
        'tier': 'tier',
        'tag': 'tag'
    }

    def __init__(self, id=None, stream_id=None, title=None, avatar=None, nick=None, nick_en=None, cover=None, watched=None, subscription_required=None, has_subscribed=None, duration=None, weight=None, moments_uid=None, session_id=None, ended_at_format=None, ended_at_type=None, tier=None, tag=None, local_vars_configuration=None):  # noqa: E501
        # type: (str, str, str, str, str, str, str, int, bool, bool, int, int, str, str, str, int, int, str, Configuration) -> None
        """ListLiveReplayResponseDataVideo - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._id = None
        self._stream_id = None
        self._title = None
        self._avatar = None
        self._nick = None
        self._nick_en = None
        self._cover = None
        self._watched = None
        self._subscription_required = None
        self._has_subscribed = None
        self._duration = None
        self._weight = None
        self._moments_uid = None
        self._session_id = None
        self._ended_at_format = None
        self._ended_at_type = None
        self._tier = None
        self._tag = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if stream_id is not None:
            self.stream_id = stream_id
        if title is not None:
            self.title = title
        if avatar is not None:
            self.avatar = avatar
        if nick is not None:
            self.nick = nick
        if nick_en is not None:
            self.nick_en = nick_en
        if cover is not None:
            self.cover = cover
        if watched is not None:
            self.watched = watched
        if subscription_required is not None:
            self.subscription_required = subscription_required
        if has_subscribed is not None:
            self.has_subscribed = has_subscribed
        if duration is not None:
            self.duration = duration
        if weight is not None:
            self.weight = weight
        if moments_uid is not None:
            self.moments_uid = moments_uid
        if session_id is not None:
            self.session_id = session_id
        if ended_at_format is not None:
            self.ended_at_format = ended_at_format
        if ended_at_type is not None:
            self.ended_at_type = ended_at_type
        if tier is not None:
            self.tier = tier
        self.tag = tag

    @property
    def id(self):
        """Gets the id of this ListLiveReplayResponseDataVideo.  # noqa: E501

        Video ID  # noqa: E501

        :return: The id of this ListLiveReplayResponseDataVideo.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ListLiveReplayResponseDataVideo.

        Video ID  # noqa: E501

        :param id: The id of this ListLiveReplayResponseDataVideo.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def stream_id(self):
        """Gets the stream_id of this ListLiveReplayResponseDataVideo.  # noqa: E501

        Live stream ID  # noqa: E501

        :return: The stream_id of this ListLiveReplayResponseDataVideo.  # noqa: E501
        :rtype: str
        """
        return self._stream_id

    @stream_id.setter
    def stream_id(self, stream_id):
        """Sets the stream_id of this ListLiveReplayResponseDataVideo.

        Live stream ID  # noqa: E501

        :param stream_id: The stream_id of this ListLiveReplayResponseDataVideo.  # noqa: E501
        :type: str
        """

        self._stream_id = stream_id

    @property
    def title(self):
        """Gets the title of this ListLiveReplayResponseDataVideo.  # noqa: E501

        Video Title  # noqa: E501

        :return: The title of this ListLiveReplayResponseDataVideo.  # noqa: E501
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this ListLiveReplayResponseDataVideo.

        Video Title  # noqa: E501

        :param title: The title of this ListLiveReplayResponseDataVideo.  # noqa: E501
        :type: str
        """

        self._title = title

    @property
    def avatar(self):
        """Gets the avatar of this ListLiveReplayResponseDataVideo.  # noqa: E501

        Author avatar URL  # noqa: E501

        :return: The avatar of this ListLiveReplayResponseDataVideo.  # noqa: E501
        :rtype: str
        """
        return self._avatar

    @avatar.setter
    def avatar(self, avatar):
        """Sets the avatar of this ListLiveReplayResponseDataVideo.

        Author avatar URL  # noqa: E501

        :param avatar: The avatar of this ListLiveReplayResponseDataVideo.  # noqa: E501
        :type: str
        """

        self._avatar = avatar

    @property
    def nick(self):
        """Gets the nick of this ListLiveReplayResponseDataVideo.  # noqa: E501

        Author nickname  # noqa: E501

        :return: The nick of this ListLiveReplayResponseDataVideo.  # noqa: E501
        :rtype: str
        """
        return self._nick

    @nick.setter
    def nick(self, nick):
        """Sets the nick of this ListLiveReplayResponseDataVideo.

        Author nickname  # noqa: E501

        :param nick: The nick of this ListLiveReplayResponseDataVideo.  # noqa: E501
        :type: str
        """

        self._nick = nick

    @property
    def nick_en(self):
        """Gets the nick_en of this ListLiveReplayResponseDataVideo.  # noqa: E501

        Author English nickname  # noqa: E501

        :return: The nick_en of this ListLiveReplayResponseDataVideo.  # noqa: E501
        :rtype: str
        """
        return self._nick_en

    @nick_en.setter
    def nick_en(self, nick_en):
        """Sets the nick_en of this ListLiveReplayResponseDataVideo.

        Author English nickname  # noqa: E501

        :param nick_en: The nick_en of this ListLiveReplayResponseDataVideo.  # noqa: E501
        :type: str
        """

        self._nick_en = nick_en

    @property
    def cover(self):
        """Gets the cover of this ListLiveReplayResponseDataVideo.  # noqa: E501

        Cover image URL  # noqa: E501

        :return: The cover of this ListLiveReplayResponseDataVideo.  # noqa: E501
        :rtype: str
        """
        return self._cover

    @cover.setter
    def cover(self, cover):
        """Sets the cover of this ListLiveReplayResponseDataVideo.

        Cover image URL  # noqa: E501

        :param cover: The cover of this ListLiveReplayResponseDataVideo.  # noqa: E501
        :type: str
        """

        self._cover = cover

    @property
    def watched(self):
        """Gets the watched of this ListLiveReplayResponseDataVideo.  # noqa: E501

        Viewer count  # noqa: E501

        :return: The watched of this ListLiveReplayResponseDataVideo.  # noqa: E501
        :rtype: int
        """
        return self._watched

    @watched.setter
    def watched(self, watched):
        """Sets the watched of this ListLiveReplayResponseDataVideo.

        Viewer count  # noqa: E501

        :param watched: The watched of this ListLiveReplayResponseDataVideo.  # noqa: E501
        :type: int
        """

        self._watched = watched

    @property
    def subscription_required(self):
        """Gets the subscription_required of this ListLiveReplayResponseDataVideo.  # noqa: E501

        Whether subscription is required  # noqa: E501

        :return: The subscription_required of this ListLiveReplayResponseDataVideo.  # noqa: E501
        :rtype: bool
        """
        return self._subscription_required

    @subscription_required.setter
    def subscription_required(self, subscription_required):
        """Sets the subscription_required of this ListLiveReplayResponseDataVideo.

        Whether subscription is required  # noqa: E501

        :param subscription_required: The subscription_required of this ListLiveReplayResponseDataVideo.  # noqa: E501
        :type: bool
        """

        self._subscription_required = subscription_required

    @property
    def has_subscribed(self):
        """Gets the has_subscribed of this ListLiveReplayResponseDataVideo.  # noqa: E501

        Whether the current user has subscribed  # noqa: E501

        :return: The has_subscribed of this ListLiveReplayResponseDataVideo.  # noqa: E501
        :rtype: bool
        """
        return self._has_subscribed

    @has_subscribed.setter
    def has_subscribed(self, has_subscribed):
        """Sets the has_subscribed of this ListLiveReplayResponseDataVideo.

        Whether the current user has subscribed  # noqa: E501

        :param has_subscribed: The has_subscribed of this ListLiveReplayResponseDataVideo.  # noqa: E501
        :type: bool
        """

        self._has_subscribed = has_subscribed

    @property
    def duration(self):
        """Gets the duration of this ListLiveReplayResponseDataVideo.  # noqa: E501

        Video duration (in seconds)  # noqa: E501

        :return: The duration of this ListLiveReplayResponseDataVideo.  # noqa: E501
        :rtype: int
        """
        return self._duration

    @duration.setter
    def duration(self, duration):
        """Sets the duration of this ListLiveReplayResponseDataVideo.

        Video duration (in seconds)  # noqa: E501

        :param duration: The duration of this ListLiveReplayResponseDataVideo.  # noqa: E501
        :type: int
        """

        self._duration = duration

    @property
    def weight(self):
        """Gets the weight of this ListLiveReplayResponseDataVideo.  # noqa: E501

        Sort weight  # noqa: E501

        :return: The weight of this ListLiveReplayResponseDataVideo.  # noqa: E501
        :rtype: int
        """
        return self._weight

    @weight.setter
    def weight(self, weight):
        """Sets the weight of this ListLiveReplayResponseDataVideo.

        Sort weight  # noqa: E501

        :param weight: The weight of this ListLiveReplayResponseDataVideo.  # noqa: E501
        :type: int
        """

        self._weight = weight

    @property
    def moments_uid(self):
        """Gets the moments_uid of this ListLiveReplayResponseDataVideo.  # noqa: E501

        Square user ID  # noqa: E501

        :return: The moments_uid of this ListLiveReplayResponseDataVideo.  # noqa: E501
        :rtype: str
        """
        return self._moments_uid

    @moments_uid.setter
    def moments_uid(self, moments_uid):
        """Sets the moments_uid of this ListLiveReplayResponseDataVideo.

        Square user ID  # noqa: E501

        :param moments_uid: The moments_uid of this ListLiveReplayResponseDataVideo.  # noqa: E501
        :type: str
        """

        self._moments_uid = moments_uid

    @property
    def session_id(self):
        """Gets the session_id of this ListLiveReplayResponseDataVideo.  # noqa: E501

        Session ID  # noqa: E501

        :return: The session_id of this ListLiveReplayResponseDataVideo.  # noqa: E501
        :rtype: str
        """
        return self._session_id

    @session_id.setter
    def session_id(self, session_id):
        """Sets the session_id of this ListLiveReplayResponseDataVideo.

        Session ID  # noqa: E501

        :param session_id: The session_id of this ListLiveReplayResponseDataVideo.  # noqa: E501
        :type: str
        """

        self._session_id = session_id

    @property
    def ended_at_format(self):
        """Gets the ended_at_format of this ListLiveReplayResponseDataVideo.  # noqa: E501

        End time format  # noqa: E501

        :return: The ended_at_format of this ListLiveReplayResponseDataVideo.  # noqa: E501
        :rtype: str
        """
        return self._ended_at_format

    @ended_at_format.setter
    def ended_at_format(self, ended_at_format):
        """Sets the ended_at_format of this ListLiveReplayResponseDataVideo.

        End time format  # noqa: E501

        :param ended_at_format: The ended_at_format of this ListLiveReplayResponseDataVideo.  # noqa: E501
        :type: str
        """

        self._ended_at_format = ended_at_format

    @property
    def ended_at_type(self):
        """Gets the ended_at_type of this ListLiveReplayResponseDataVideo.  # noqa: E501

        End time type  # noqa: E501

        :return: The ended_at_type of this ListLiveReplayResponseDataVideo.  # noqa: E501
        :rtype: int
        """
        return self._ended_at_type

    @ended_at_type.setter
    def ended_at_type(self, ended_at_type):
        """Sets the ended_at_type of this ListLiveReplayResponseDataVideo.

        End time type  # noqa: E501

        :param ended_at_type: The ended_at_type of this ListLiveReplayResponseDataVideo.  # noqa: E501
        :type: int
        """

        self._ended_at_type = ended_at_type

    @property
    def tier(self):
        """Gets the tier of this ListLiveReplayResponseDataVideo.  # noqa: E501

        Author level  # noqa: E501

        :return: The tier of this ListLiveReplayResponseDataVideo.  # noqa: E501
        :rtype: int
        """
        return self._tier

    @tier.setter
    def tier(self, tier):
        """Sets the tier of this ListLiveReplayResponseDataVideo.

        Author level  # noqa: E501

        :param tier: The tier of this ListLiveReplayResponseDataVideo.  # noqa: E501
        :type: int
        """

        self._tier = tier

    @property
    def tag(self):
        """Gets the tag of this ListLiveReplayResponseDataVideo.  # noqa: E501

        Tag  # noqa: E501

        :return: The tag of this ListLiveReplayResponseDataVideo.  # noqa: E501
        :rtype: str
        """
        return self._tag

    @tag.setter
    def tag(self, tag):
        """Sets the tag of this ListLiveReplayResponseDataVideo.

        Tag  # noqa: E501

        :param tag: The tag of this ListLiveReplayResponseDataVideo.  # noqa: E501
        :type: str
        """

        self._tag = tag

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ListLiveReplayResponseDataVideo):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ListLiveReplayResponseDataVideo):
            return True

        return self.to_dict() != other.to_dict()
