# coding: utf-8

"""
    Gate API

    Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.  # noqa: E501

    Contact: support@mail.gate.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from gate_api.configuration import Configuration


class ListLiveReplayResponseDataLive(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'str',
        'uid': 'str',
        'chat_group_id': 'str',
        'name': 'str',
        'cover': 'str',
        'started_at': 'str',
        'subscription_required': 'bool',
        'hot_weight': 'int',
        'live_type': 'int',
        'session_id': 'str',
        'host': 'ListLiveReplayResponseDataLiveHost',
        'status': 'str'
    }

    attribute_map = {
        'id': 'id',
        'uid': 'uid',
        'chat_group_id': 'chat_group_id',
        'name': 'name',
        'cover': 'cover',
        'started_at': 'started_at',
        'subscription_required': 'subscription_required',
        'hot_weight': 'hot_weight',
        'live_type': 'live_type',
        'session_id': 'session_id',
        'host': 'host',
        'status': 'status'
    }

    def __init__(self, id=None, uid=None, chat_group_id=None, name=None, cover=None, started_at=None, subscription_required=None, hot_weight=None, live_type=None, session_id=None, host=None, status=None, local_vars_configuration=None):  # noqa: E501
        # type: (str, str, str, str, str, str, bool, int, int, str, ListLiveReplayResponseDataLiveHost, str, Configuration) -> None
        """ListLiveReplayResponseDataLive - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._id = None
        self._uid = None
        self._chat_group_id = None
        self._name = None
        self._cover = None
        self._started_at = None
        self._subscription_required = None
        self._hot_weight = None
        self._live_type = None
        self._session_id = None
        self._host = None
        self._status = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if uid is not None:
            self.uid = uid
        if chat_group_id is not None:
            self.chat_group_id = chat_group_id
        if name is not None:
            self.name = name
        if cover is not None:
            self.cover = cover
        if started_at is not None:
            self.started_at = started_at
        if subscription_required is not None:
            self.subscription_required = subscription_required
        if hot_weight is not None:
            self.hot_weight = hot_weight
        if live_type is not None:
            self.live_type = live_type
        if session_id is not None:
            self.session_id = session_id
        if host is not None:
            self.host = host
        if status is not None:
            self.status = status

    @property
    def id(self):
        """Gets the id of this ListLiveReplayResponseDataLive.  # noqa: E501

        Live ID  # noqa: E501

        :return: The id of this ListLiveReplayResponseDataLive.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ListLiveReplayResponseDataLive.

        Live ID  # noqa: E501

        :param id: The id of this ListLiveReplayResponseDataLive.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def uid(self):
        """Gets the uid of this ListLiveReplayResponseDataLive.  # noqa: E501

        Anchor User ID  # noqa: E501

        :return: The uid of this ListLiveReplayResponseDataLive.  # noqa: E501
        :rtype: str
        """
        return self._uid

    @uid.setter
    def uid(self, uid):
        """Sets the uid of this ListLiveReplayResponseDataLive.

        Anchor User ID  # noqa: E501

        :param uid: The uid of this ListLiveReplayResponseDataLive.  # noqa: E501
        :type: str
        """

        self._uid = uid

    @property
    def chat_group_id(self):
        """Gets the chat_group_id of this ListLiveReplayResponseDataLive.  # noqa: E501

        Chat group ID  # noqa: E501

        :return: The chat_group_id of this ListLiveReplayResponseDataLive.  # noqa: E501
        :rtype: str
        """
        return self._chat_group_id

    @chat_group_id.setter
    def chat_group_id(self, chat_group_id):
        """Sets the chat_group_id of this ListLiveReplayResponseDataLive.

        Chat group ID  # noqa: E501

        :param chat_group_id: The chat_group_id of this ListLiveReplayResponseDataLive.  # noqa: E501
        :type: str
        """

        self._chat_group_id = chat_group_id

    @property
    def name(self):
        """Gets the name of this ListLiveReplayResponseDataLive.  # noqa: E501

        Live room name  # noqa: E501

        :return: The name of this ListLiveReplayResponseDataLive.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ListLiveReplayResponseDataLive.

        Live room name  # noqa: E501

        :param name: The name of this ListLiveReplayResponseDataLive.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def cover(self):
        """Gets the cover of this ListLiveReplayResponseDataLive.  # noqa: E501

        Cover image URL  # noqa: E501

        :return: The cover of this ListLiveReplayResponseDataLive.  # noqa: E501
        :rtype: str
        """
        return self._cover

    @cover.setter
    def cover(self, cover):
        """Sets the cover of this ListLiveReplayResponseDataLive.

        Cover image URL  # noqa: E501

        :param cover: The cover of this ListLiveReplayResponseDataLive.  # noqa: E501
        :type: str
        """

        self._cover = cover

    @property
    def started_at(self):
        """Gets the started_at of this ListLiveReplayResponseDataLive.  # noqa: E501

        Broadcast start time (Unix timestamp string)  # noqa: E501

        :return: The started_at of this ListLiveReplayResponseDataLive.  # noqa: E501
        :rtype: str
        """
        return self._started_at

    @started_at.setter
    def started_at(self, started_at):
        """Sets the started_at of this ListLiveReplayResponseDataLive.

        Broadcast start time (Unix timestamp string)  # noqa: E501

        :param started_at: The started_at of this ListLiveReplayResponseDataLive.  # noqa: E501
        :type: str
        """

        self._started_at = started_at

    @property
    def subscription_required(self):
        """Gets the subscription_required of this ListLiveReplayResponseDataLive.  # noqa: E501

        Whether subscription is required  # noqa: E501

        :return: The subscription_required of this ListLiveReplayResponseDataLive.  # noqa: E501
        :rtype: bool
        """
        return self._subscription_required

    @subscription_required.setter
    def subscription_required(self, subscription_required):
        """Sets the subscription_required of this ListLiveReplayResponseDataLive.

        Whether subscription is required  # noqa: E501

        :param subscription_required: The subscription_required of this ListLiveReplayResponseDataLive.  # noqa: E501
        :type: bool
        """

        self._subscription_required = subscription_required

    @property
    def hot_weight(self):
        """Gets the hot_weight of this ListLiveReplayResponseDataLive.  # noqa: E501

        Popularity weight  # noqa: E501

        :return: The hot_weight of this ListLiveReplayResponseDataLive.  # noqa: E501
        :rtype: int
        """
        return self._hot_weight

    @hot_weight.setter
    def hot_weight(self, hot_weight):
        """Sets the hot_weight of this ListLiveReplayResponseDataLive.

        Popularity weight  # noqa: E501

        :param hot_weight: The hot_weight of this ListLiveReplayResponseDataLive.  # noqa: E501
        :type: int
        """

        self._hot_weight = hot_weight

    @property
    def live_type(self):
        """Gets the live_type of this ListLiveReplayResponseDataLive.  # noqa: E501

        Live stream type  # noqa: E501

        :return: The live_type of this ListLiveReplayResponseDataLive.  # noqa: E501
        :rtype: int
        """
        return self._live_type

    @live_type.setter
    def live_type(self, live_type):
        """Sets the live_type of this ListLiveReplayResponseDataLive.

        Live stream type  # noqa: E501

        :param live_type: The live_type of this ListLiveReplayResponseDataLive.  # noqa: E501
        :type: int
        """

        self._live_type = live_type

    @property
    def session_id(self):
        """Gets the session_id of this ListLiveReplayResponseDataLive.  # noqa: E501

        Session ID  # noqa: E501

        :return: The session_id of this ListLiveReplayResponseDataLive.  # noqa: E501
        :rtype: str
        """
        return self._session_id

    @session_id.setter
    def session_id(self, session_id):
        """Sets the session_id of this ListLiveReplayResponseDataLive.

        Session ID  # noqa: E501

        :param session_id: The session_id of this ListLiveReplayResponseDataLive.  # noqa: E501
        :type: str
        """

        self._session_id = session_id

    @property
    def host(self):
        """Gets the host of this ListLiveReplayResponseDataLive.  # noqa: E501


        :return: The host of this ListLiveReplayResponseDataLive.  # noqa: E501
        :rtype: ListLiveReplayResponseDataLiveHost
        """
        return self._host

    @host.setter
    def host(self, host):
        """Sets the host of this ListLiveReplayResponseDataLive.


        :param host: The host of this ListLiveReplayResponseDataLive.  # noqa: E501
        :type: ListLiveReplayResponseDataLiveHost
        """

        self._host = host

    @property
    def status(self):
        """Gets the status of this ListLiveReplayResponseDataLive.  # noqa: E501

        Live stream status (e.g., streaming)  # noqa: E501

        :return: The status of this ListLiveReplayResponseDataLive.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this ListLiveReplayResponseDataLive.

        Live stream status (e.g., streaming)  # noqa: E501

        :param status: The status of this ListLiveReplayResponseDataLive.  # noqa: E501
        :type: str
        """

        self._status = status

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ListLiveReplayResponseDataLive):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ListLiveReplayResponseDataLive):
            return True

        return self.to_dict() != other.to_dict()
