# coding: utf-8

"""
    Gate API

    Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.  # noqa: E501

    Contact: support@mail.gate.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from gate_api.configuration import Configuration


class OrderHistoryListDataList(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'order_id': 'int',
        'symbol': 'str',
        'symbol_desc': 'str',
        'price_type': 'str',
        'order_opt_type': 'int',
        'state': 'int',
        'state_desc': 'str',
        'side': 'int',
        'volume': 'str',
        'fill_volume': 'str',
        'close_pnl': 'str',
        'price': 'str',
        'trigger_price': 'str',
        'price_tp': 'str',
        'price_sl': 'str',
        'time_setup': 'int',
        'time_done': 'int'
    }

    attribute_map = {
        'order_id': 'order_id',
        'symbol': 'symbol',
        'symbol_desc': 'symbol_desc',
        'price_type': 'price_type',
        'order_opt_type': 'order_opt_type',
        'state': 'state',
        'state_desc': 'state_desc',
        'side': 'side',
        'volume': 'volume',
        'fill_volume': 'fill_volume',
        'close_pnl': 'close_pnl',
        'price': 'price',
        'trigger_price': 'trigger_price',
        'price_tp': 'price_tp',
        'price_sl': 'price_sl',
        'time_setup': 'time_setup',
        'time_done': 'time_done'
    }

    def __init__(self, order_id=None, symbol=None, symbol_desc=None, price_type=None, order_opt_type=None, state=None, state_desc=None, side=None, volume=None, fill_volume=None, close_pnl=None, price=None, trigger_price=None, price_tp=None, price_sl=None, time_setup=None, time_done=None, local_vars_configuration=None):  # noqa: E501
        # type: (int, str, str, str, int, int, str, int, str, str, str, str, str, str, str, int, int, Configuration) -> None
        """OrderHistoryListDataList - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._order_id = None
        self._symbol = None
        self._symbol_desc = None
        self._price_type = None
        self._order_opt_type = None
        self._state = None
        self._state_desc = None
        self._side = None
        self._volume = None
        self._fill_volume = None
        self._close_pnl = None
        self._price = None
        self._trigger_price = None
        self._price_tp = None
        self._price_sl = None
        self._time_setup = None
        self._time_done = None
        self.discriminator = None

        if order_id is not None:
            self.order_id = order_id
        if symbol is not None:
            self.symbol = symbol
        if symbol_desc is not None:
            self.symbol_desc = symbol_desc
        if price_type is not None:
            self.price_type = price_type
        if order_opt_type is not None:
            self.order_opt_type = order_opt_type
        if state is not None:
            self.state = state
        if state_desc is not None:
            self.state_desc = state_desc
        if side is not None:
            self.side = side
        if volume is not None:
            self.volume = volume
        if fill_volume is not None:
            self.fill_volume = fill_volume
        if close_pnl is not None:
            self.close_pnl = close_pnl
        if price is not None:
            self.price = price
        if trigger_price is not None:
            self.trigger_price = trigger_price
        if price_tp is not None:
            self.price_tp = price_tp
        if price_sl is not None:
            self.price_sl = price_sl
        if time_setup is not None:
            self.time_setup = time_setup
        if time_done is not None:
            self.time_done = time_done

    @property
    def order_id(self):
        """Gets the order_id of this OrderHistoryListDataList.  # noqa: E501

        Order ID  # noqa: E501

        :return: The order_id of this OrderHistoryListDataList.  # noqa: E501
        :rtype: int
        """
        return self._order_id

    @order_id.setter
    def order_id(self, order_id):
        """Sets the order_id of this OrderHistoryListDataList.

        Order ID  # noqa: E501

        :param order_id: The order_id of this OrderHistoryListDataList.  # noqa: E501
        :type: int
        """

        self._order_id = order_id

    @property
    def symbol(self):
        """Gets the symbol of this OrderHistoryListDataList.  # noqa: E501

        Currency pair  # noqa: E501

        :return: The symbol of this OrderHistoryListDataList.  # noqa: E501
        :rtype: str
        """
        return self._symbol

    @symbol.setter
    def symbol(self, symbol):
        """Sets the symbol of this OrderHistoryListDataList.

        Currency pair  # noqa: E501

        :param symbol: The symbol of this OrderHistoryListDataList.  # noqa: E501
        :type: str
        """

        self._symbol = symbol

    @property
    def symbol_desc(self):
        """Gets the symbol_desc of this OrderHistoryListDataList.  # noqa: E501

        Trading symbol description  # noqa: E501

        :return: The symbol_desc of this OrderHistoryListDataList.  # noqa: E501
        :rtype: str
        """
        return self._symbol_desc

    @symbol_desc.setter
    def symbol_desc(self, symbol_desc):
        """Sets the symbol_desc of this OrderHistoryListDataList.

        Trading symbol description  # noqa: E501

        :param symbol_desc: The symbol_desc of this OrderHistoryListDataList.  # noqa: E501
        :type: str
        """

        self._symbol_desc = symbol_desc

    @property
    def price_type(self):
        """Gets the price_type of this OrderHistoryListDataList.  # noqa: E501

        Trade type (market=market price, trigger=trigger price)  # noqa: E501

        :return: The price_type of this OrderHistoryListDataList.  # noqa: E501
        :rtype: str
        """
        return self._price_type

    @price_type.setter
    def price_type(self, price_type):
        """Sets the price_type of this OrderHistoryListDataList.

        Trade type (market=market price, trigger=trigger price)  # noqa: E501

        :param price_type: The price_type of this OrderHistoryListDataList.  # noqa: E501
        :type: str
        """
        allowed_values = ["market", "trigger"]  # noqa: E501
        if self.local_vars_configuration.client_side_validation and price_type not in allowed_values:  # noqa: E501
            raise ValueError(
                "Invalid value for `price_type` ({0}), must be one of {1}"  # noqa: E501
                .format(price_type, allowed_values)
            )

        self._price_type = price_type

    @property
    def order_opt_type(self):
        """Gets the order_opt_type of this OrderHistoryListDataList.  # noqa: E501

        Order operation type (1=sell, 2=buy, 3=close long, 4=close short, 5=force close long, 6=force close short)  # noqa: E501

        :return: The order_opt_type of this OrderHistoryListDataList.  # noqa: E501
        :rtype: int
        """
        return self._order_opt_type

    @order_opt_type.setter
    def order_opt_type(self, order_opt_type):
        """Sets the order_opt_type of this OrderHistoryListDataList.

        Order operation type (1=sell, 2=buy, 3=close long, 4=close short, 5=force close long, 6=force close short)  # noqa: E501

        :param order_opt_type: The order_opt_type of this OrderHistoryListDataList.  # noqa: E501
        :type: int
        """
        allowed_values = [1, 2, 3, 4, 5, 6]  # noqa: E501
        if self.local_vars_configuration.client_side_validation and order_opt_type not in allowed_values:  # noqa: E501
            raise ValueError(
                "Invalid value for `order_opt_type` ({0}), must be one of {1}"  # noqa: E501
                .format(order_opt_type, allowed_values)
            )

        self._order_opt_type = order_opt_type

    @property
    def state(self):
        """Gets the state of this OrderHistoryListDataList.  # noqa: E501

        Order status code  # noqa: E501

        :return: The state of this OrderHistoryListDataList.  # noqa: E501
        :rtype: int
        """
        return self._state

    @state.setter
    def state(self, state):
        """Sets the state of this OrderHistoryListDataList.

        Order status code  # noqa: E501

        :param state: The state of this OrderHistoryListDataList.  # noqa: E501
        :type: int
        """

        self._state = state

    @property
    def state_desc(self):
        """Gets the state_desc of this OrderHistoryListDataList.  # noqa: E501

        Order status description  # noqa: E501

        :return: The state_desc of this OrderHistoryListDataList.  # noqa: E501
        :rtype: str
        """
        return self._state_desc

    @state_desc.setter
    def state_desc(self, state_desc):
        """Sets the state_desc of this OrderHistoryListDataList.

        Order status description  # noqa: E501

        :param state_desc: The state_desc of this OrderHistoryListDataList.  # noqa: E501
        :type: str
        """

        self._state_desc = state_desc

    @property
    def side(self):
        """Gets the side of this OrderHistoryListDataList.  # noqa: E501

        Order side (1=sell, 2=buy)  # noqa: E501

        :return: The side of this OrderHistoryListDataList.  # noqa: E501
        :rtype: int
        """
        return self._side

    @side.setter
    def side(self, side):
        """Sets the side of this OrderHistoryListDataList.

        Order side (1=sell, 2=buy)  # noqa: E501

        :param side: The side of this OrderHistoryListDataList.  # noqa: E501
        :type: int
        """
        allowed_values = [1, 2]  # noqa: E501
        if self.local_vars_configuration.client_side_validation and side not in allowed_values:  # noqa: E501
            raise ValueError(
                "Invalid value for `side` ({0}), must be one of {1}"  # noqa: E501
                .format(side, allowed_values)
            )

        self._side = side

    @property
    def volume(self):
        """Gets the volume of this OrderHistoryListDataList.  # noqa: E501

        Order volume  # noqa: E501

        :return: The volume of this OrderHistoryListDataList.  # noqa: E501
        :rtype: str
        """
        return self._volume

    @volume.setter
    def volume(self, volume):
        """Sets the volume of this OrderHistoryListDataList.

        Order volume  # noqa: E501

        :param volume: The volume of this OrderHistoryListDataList.  # noqa: E501
        :type: str
        """

        self._volume = volume

    @property
    def fill_volume(self):
        """Gets the fill_volume of this OrderHistoryListDataList.  # noqa: E501

        Trading size  # noqa: E501

        :return: The fill_volume of this OrderHistoryListDataList.  # noqa: E501
        :rtype: str
        """
        return self._fill_volume

    @fill_volume.setter
    def fill_volume(self, fill_volume):
        """Sets the fill_volume of this OrderHistoryListDataList.

        Trading size  # noqa: E501

        :param fill_volume: The fill_volume of this OrderHistoryListDataList.  # noqa: E501
        :type: str
        """

        self._fill_volume = fill_volume

    @property
    def close_pnl(self):
        """Gets the close_pnl of this OrderHistoryListDataList.  # noqa: E501

        Close Position P&L  # noqa: E501

        :return: The close_pnl of this OrderHistoryListDataList.  # noqa: E501
        :rtype: str
        """
        return self._close_pnl

    @close_pnl.setter
    def close_pnl(self, close_pnl):
        """Sets the close_pnl of this OrderHistoryListDataList.

        Close Position P&L  # noqa: E501

        :param close_pnl: The close_pnl of this OrderHistoryListDataList.  # noqa: E501
        :type: str
        """

        self._close_pnl = close_pnl

    @property
    def price(self):
        """Gets the price of this OrderHistoryListDataList.  # noqa: E501

        Average fill price  # noqa: E501

        :return: The price of this OrderHistoryListDataList.  # noqa: E501
        :rtype: str
        """
        return self._price

    @price.setter
    def price(self, price):
        """Sets the price of this OrderHistoryListDataList.

        Average fill price  # noqa: E501

        :param price: The price of this OrderHistoryListDataList.  # noqa: E501
        :type: str
        """

        self._price = price

    @property
    def trigger_price(self):
        """Gets the trigger_price of this OrderHistoryListDataList.  # noqa: E501

        Trigger price  # noqa: E501

        :return: The trigger_price of this OrderHistoryListDataList.  # noqa: E501
        :rtype: str
        """
        return self._trigger_price

    @trigger_price.setter
    def trigger_price(self, trigger_price):
        """Sets the trigger_price of this OrderHistoryListDataList.

        Trigger price  # noqa: E501

        :param trigger_price: The trigger_price of this OrderHistoryListDataList.  # noqa: E501
        :type: str
        """

        self._trigger_price = trigger_price

    @property
    def price_tp(self):
        """Gets the price_tp of this OrderHistoryListDataList.  # noqa: E501

        Take profit price  # noqa: E501

        :return: The price_tp of this OrderHistoryListDataList.  # noqa: E501
        :rtype: str
        """
        return self._price_tp

    @price_tp.setter
    def price_tp(self, price_tp):
        """Sets the price_tp of this OrderHistoryListDataList.

        Take profit price  # noqa: E501

        :param price_tp: The price_tp of this OrderHistoryListDataList.  # noqa: E501
        :type: str
        """

        self._price_tp = price_tp

    @property
    def price_sl(self):
        """Gets the price_sl of this OrderHistoryListDataList.  # noqa: E501

        Stop loss price  # noqa: E501

        :return: The price_sl of this OrderHistoryListDataList.  # noqa: E501
        :rtype: str
        """
        return self._price_sl

    @price_sl.setter
    def price_sl(self, price_sl):
        """Sets the price_sl of this OrderHistoryListDataList.

        Stop loss price  # noqa: E501

        :param price_sl: The price_sl of this OrderHistoryListDataList.  # noqa: E501
        :type: str
        """

        self._price_sl = price_sl

    @property
    def time_setup(self):
        """Gets the time_setup of this OrderHistoryListDataList.  # noqa: E501

        Order time (Unix timestamp in seconds)  # noqa: E501

        :return: The time_setup of this OrderHistoryListDataList.  # noqa: E501
        :rtype: int
        """
        return self._time_setup

    @time_setup.setter
    def time_setup(self, time_setup):
        """Sets the time_setup of this OrderHistoryListDataList.

        Order time (Unix timestamp in seconds)  # noqa: E501

        :param time_setup: The time_setup of this OrderHistoryListDataList.  # noqa: E501
        :type: int
        """

        self._time_setup = time_setup

    @property
    def time_done(self):
        """Gets the time_done of this OrderHistoryListDataList.  # noqa: E501

        End time (Unix timestamp in seconds)  # noqa: E501

        :return: The time_done of this OrderHistoryListDataList.  # noqa: E501
        :rtype: int
        """
        return self._time_done

    @time_done.setter
    def time_done(self, time_done):
        """Sets the time_done of this OrderHistoryListDataList.

        End time (Unix timestamp in seconds)  # noqa: E501

        :param time_done: The time_done of this OrderHistoryListDataList.  # noqa: E501
        :type: int
        """

        self._time_done = time_done

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, OrderHistoryListDataList):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, OrderHistoryListDataList):
            return True

        return self.to_dict() != other.to_dict()
