# coding: utf-8

"""
    Gate API

    Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.  # noqa: E501

    Contact: support@mail.gate.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from gate_api.configuration import Configuration


class OrderHistoryListItem(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'order_id': 'str',
        'symbol': 'str',
        'exchange': 'str',
        'quote_currency': 'str',
        'fx_rate': 'str',
        'symbol_desc': 'str',
        'price_type': 'str',
        'status': 'int',
        'status_desc': 'str',
        'status_detail': 'OrderHistoryListItemStatusDetail',
        'finish_as': 'int',
        'side': 'int',
        'time_in_force': 'str',
        'volume': 'str',
        'fill_volume': 'str',
        'price': 'str',
        'avg_fill_price': 'str',
        'commission': 'str',
        'time_setup': 'int',
        'time_done': 'int'
    }

    attribute_map = {
        'order_id': 'order_id',
        'symbol': 'symbol',
        'exchange': 'exchange',
        'quote_currency': 'quote_currency',
        'fx_rate': 'fx_rate',
        'symbol_desc': 'symbol_desc',
        'price_type': 'price_type',
        'status': 'status',
        'status_desc': 'status_desc',
        'status_detail': 'status_detail',
        'finish_as': 'finish_as',
        'side': 'side',
        'time_in_force': 'time_in_force',
        'volume': 'volume',
        'fill_volume': 'fill_volume',
        'price': 'price',
        'avg_fill_price': 'avg_fill_price',
        'commission': 'commission',
        'time_setup': 'time_setup',
        'time_done': 'time_done'
    }

    def __init__(self, order_id=None, symbol=None, exchange=None, quote_currency=None, fx_rate=None, symbol_desc=None, price_type=None, status=None, status_desc=None, status_detail=None, finish_as=None, side=None, time_in_force=None, volume=None, fill_volume=None, price=None, avg_fill_price=None, commission=None, time_setup=None, time_done=None, local_vars_configuration=None):  # noqa: E501
        # type: (str, str, str, str, str, str, str, int, str, OrderHistoryListItemStatusDetail, int, int, str, str, str, str, str, str, int, int, Configuration) -> None
        """OrderHistoryListItem - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._order_id = None
        self._symbol = None
        self._exchange = None
        self._quote_currency = None
        self._fx_rate = None
        self._symbol_desc = None
        self._price_type = None
        self._status = None
        self._status_desc = None
        self._status_detail = None
        self._finish_as = None
        self._side = None
        self._time_in_force = None
        self._volume = None
        self._fill_volume = None
        self._price = None
        self._avg_fill_price = None
        self._commission = None
        self._time_setup = None
        self._time_done = None
        self.discriminator = None

        if order_id is not None:
            self.order_id = order_id
        if symbol is not None:
            self.symbol = symbol
        if exchange is not None:
            self.exchange = exchange
        if quote_currency is not None:
            self.quote_currency = quote_currency
        if fx_rate is not None:
            self.fx_rate = fx_rate
        if symbol_desc is not None:
            self.symbol_desc = symbol_desc
        if price_type is not None:
            self.price_type = price_type
        if status is not None:
            self.status = status
        if status_desc is not None:
            self.status_desc = status_desc
        self.status_detail = status_detail
        if finish_as is not None:
            self.finish_as = finish_as
        if side is not None:
            self.side = side
        if time_in_force is not None:
            self.time_in_force = time_in_force
        if volume is not None:
            self.volume = volume
        if fill_volume is not None:
            self.fill_volume = fill_volume
        if price is not None:
            self.price = price
        self.avg_fill_price = avg_fill_price
        if commission is not None:
            self.commission = commission
        if time_setup is not None:
            self.time_setup = time_setup
        if time_done is not None:
            self.time_done = time_done

    @property
    def order_id(self):
        """Gets the order_id of this OrderHistoryListItem.  # noqa: E501


        :return: The order_id of this OrderHistoryListItem.  # noqa: E501
        :rtype: str
        """
        return self._order_id

    @order_id.setter
    def order_id(self, order_id):
        """Sets the order_id of this OrderHistoryListItem.


        :param order_id: The order_id of this OrderHistoryListItem.  # noqa: E501
        :type: str
        """

        self._order_id = order_id

    @property
    def symbol(self):
        """Gets the symbol of this OrderHistoryListItem.  # noqa: E501


        :return: The symbol of this OrderHistoryListItem.  # noqa: E501
        :rtype: str
        """
        return self._symbol

    @symbol.setter
    def symbol(self, symbol):
        """Sets the symbol of this OrderHistoryListItem.


        :param symbol: The symbol of this OrderHistoryListItem.  # noqa: E501
        :type: str
        """

        self._symbol = symbol

    @property
    def exchange(self):
        """Gets the exchange of this OrderHistoryListItem.  # noqa: E501

        Exchange, supports us, hk, and kr  # noqa: E501

        :return: The exchange of this OrderHistoryListItem.  # noqa: E501
        :rtype: str
        """
        return self._exchange

    @exchange.setter
    def exchange(self, exchange):
        """Sets the exchange of this OrderHistoryListItem.

        Exchange, supports us, hk, and kr  # noqa: E501

        :param exchange: The exchange of this OrderHistoryListItem.  # noqa: E501
        :type: str
        """
        allowed_values = ["us", "hk", "kr"]  # noqa: E501
        if self.local_vars_configuration.client_side_validation and exchange not in allowed_values:  # noqa: E501
            raise ValueError(
                "Invalid value for `exchange` ({0}), must be one of {1}"  # noqa: E501
                .format(exchange, allowed_values)
            )

        self._exchange = exchange

    @property
    def quote_currency(self):
        """Gets the quote_currency of this OrderHistoryListItem.  # noqa: E501


        :return: The quote_currency of this OrderHistoryListItem.  # noqa: E501
        :rtype: str
        """
        return self._quote_currency

    @quote_currency.setter
    def quote_currency(self, quote_currency):
        """Sets the quote_currency of this OrderHistoryListItem.


        :param quote_currency: The quote_currency of this OrderHistoryListItem.  # noqa: E501
        :type: str
        """

        self._quote_currency = quote_currency

    @property
    def fx_rate(self):
        """Gets the fx_rate of this OrderHistoryListItem.  # noqa: E501

        Quote currency to USD exchange rate  # noqa: E501

        :return: The fx_rate of this OrderHistoryListItem.  # noqa: E501
        :rtype: str
        """
        return self._fx_rate

    @fx_rate.setter
    def fx_rate(self, fx_rate):
        """Sets the fx_rate of this OrderHistoryListItem.

        Quote currency to USD exchange rate  # noqa: E501

        :param fx_rate: The fx_rate of this OrderHistoryListItem.  # noqa: E501
        :type: str
        """

        self._fx_rate = fx_rate

    @property
    def symbol_desc(self):
        """Gets the symbol_desc of this OrderHistoryListItem.  # noqa: E501


        :return: The symbol_desc of this OrderHistoryListItem.  # noqa: E501
        :rtype: str
        """
        return self._symbol_desc

    @symbol_desc.setter
    def symbol_desc(self, symbol_desc):
        """Sets the symbol_desc of this OrderHistoryListItem.


        :param symbol_desc: The symbol_desc of this OrderHistoryListItem.  # noqa: E501
        :type: str
        """

        self._symbol_desc = symbol_desc

    @property
    def price_type(self):
        """Gets the price_type of this OrderHistoryListItem.  # noqa: E501

        Price type (market = market order, limit = limit order)  # noqa: E501

        :return: The price_type of this OrderHistoryListItem.  # noqa: E501
        :rtype: str
        """
        return self._price_type

    @price_type.setter
    def price_type(self, price_type):
        """Sets the price_type of this OrderHistoryListItem.

        Price type (market = market order, limit = limit order)  # noqa: E501

        :param price_type: The price_type of this OrderHistoryListItem.  # noqa: E501
        :type: str
        """
        allowed_values = ["market", "limit"]  # noqa: E501
        if self.local_vars_configuration.client_side_validation and price_type not in allowed_values:  # noqa: E501
            raise ValueError(
                "Invalid value for `price_type` ({0}), must be one of {1}"  # noqa: E501
                .format(price_type, allowed_values)
            )

        self._price_type = price_type

    @property
    def status(self):
        """Gets the status of this OrderHistoryListItem.  # noqa: E501

        Order status  # noqa: E501

        :return: The status of this OrderHistoryListItem.  # noqa: E501
        :rtype: int
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this OrderHistoryListItem.

        Order status  # noqa: E501

        :param status: The status of this OrderHistoryListItem.  # noqa: E501
        :type: int
        """

        self._status = status

    @property
    def status_desc(self):
        """Gets the status_desc of this OrderHistoryListItem.  # noqa: E501

        Order status description  # noqa: E501

        :return: The status_desc of this OrderHistoryListItem.  # noqa: E501
        :rtype: str
        """
        return self._status_desc

    @status_desc.setter
    def status_desc(self, status_desc):
        """Sets the status_desc of this OrderHistoryListItem.

        Order status description  # noqa: E501

        :param status_desc: The status_desc of this OrderHistoryListItem.  # noqa: E501
        :type: str
        """

        self._status_desc = status_desc

    @property
    def status_detail(self):
        """Gets the status_detail of this OrderHistoryListItem.  # noqa: E501


        :return: The status_detail of this OrderHistoryListItem.  # noqa: E501
        :rtype: OrderHistoryListItemStatusDetail
        """
        return self._status_detail

    @status_detail.setter
    def status_detail(self, status_detail):
        """Sets the status_detail of this OrderHistoryListItem.


        :param status_detail: The status_detail of this OrderHistoryListItem.  # noqa: E501
        :type: OrderHistoryListItemStatusDetail
        """

        self._status_detail = status_detail

    @property
    def finish_as(self):
        """Gets the finish_as of this OrderHistoryListItem.  # noqa: E501

        Order completion reason  # noqa: E501

        :return: The finish_as of this OrderHistoryListItem.  # noqa: E501
        :rtype: int
        """
        return self._finish_as

    @finish_as.setter
    def finish_as(self, finish_as):
        """Sets the finish_as of this OrderHistoryListItem.

        Order completion reason  # noqa: E501

        :param finish_as: The finish_as of this OrderHistoryListItem.  # noqa: E501
        :type: int
        """

        self._finish_as = finish_as

    @property
    def side(self):
        """Gets the side of this OrderHistoryListItem.  # noqa: E501

        Side (1=sell, 2=buy)  # noqa: E501

        :return: The side of this OrderHistoryListItem.  # noqa: E501
        :rtype: int
        """
        return self._side

    @side.setter
    def side(self, side):
        """Sets the side of this OrderHistoryListItem.

        Side (1=sell, 2=buy)  # noqa: E501

        :param side: The side of this OrderHistoryListItem.  # noqa: E501
        :type: int
        """
        allowed_values = [1, 2]  # noqa: E501
        if self.local_vars_configuration.client_side_validation and side not in allowed_values:  # noqa: E501
            raise ValueError(
                "Invalid value for `side` ({0}), must be one of {1}"  # noqa: E501
                .format(side, allowed_values)
            )

        self._side = side

    @property
    def time_in_force(self):
        """Gets the time_in_force of this OrderHistoryListItem.  # noqa: E501

        Time in force. - day: Day order.  # noqa: E501

        :return: The time_in_force of this OrderHistoryListItem.  # noqa: E501
        :rtype: str
        """
        return self._time_in_force

    @time_in_force.setter
    def time_in_force(self, time_in_force):
        """Sets the time_in_force of this OrderHistoryListItem.

        Time in force. - day: Day order.  # noqa: E501

        :param time_in_force: The time_in_force of this OrderHistoryListItem.  # noqa: E501
        :type: str
        """
        allowed_values = ["day"]  # noqa: E501
        if self.local_vars_configuration.client_side_validation and time_in_force not in allowed_values:  # noqa: E501
            raise ValueError(
                "Invalid value for `time_in_force` ({0}), must be one of {1}"  # noqa: E501
                .format(time_in_force, allowed_values)
            )

        self._time_in_force = time_in_force

    @property
    def volume(self):
        """Gets the volume of this OrderHistoryListItem.  # noqa: E501


        :return: The volume of this OrderHistoryListItem.  # noqa: E501
        :rtype: str
        """
        return self._volume

    @volume.setter
    def volume(self, volume):
        """Sets the volume of this OrderHistoryListItem.


        :param volume: The volume of this OrderHistoryListItem.  # noqa: E501
        :type: str
        """

        self._volume = volume

    @property
    def fill_volume(self):
        """Gets the fill_volume of this OrderHistoryListItem.  # noqa: E501


        :return: The fill_volume of this OrderHistoryListItem.  # noqa: E501
        :rtype: str
        """
        return self._fill_volume

    @fill_volume.setter
    def fill_volume(self, fill_volume):
        """Sets the fill_volume of this OrderHistoryListItem.


        :param fill_volume: The fill_volume of this OrderHistoryListItem.  # noqa: E501
        :type: str
        """

        self._fill_volume = fill_volume

    @property
    def price(self):
        """Gets the price of this OrderHistoryListItem.  # noqa: E501


        :return: The price of this OrderHistoryListItem.  # noqa: E501
        :rtype: str
        """
        return self._price

    @price.setter
    def price(self, price):
        """Sets the price of this OrderHistoryListItem.


        :param price: The price of this OrderHistoryListItem.  # noqa: E501
        :type: str
        """

        self._price = price

    @property
    def avg_fill_price(self):
        """Gets the avg_fill_price of this OrderHistoryListItem.  # noqa: E501


        :return: The avg_fill_price of this OrderHistoryListItem.  # noqa: E501
        :rtype: str
        """
        return self._avg_fill_price

    @avg_fill_price.setter
    def avg_fill_price(self, avg_fill_price):
        """Sets the avg_fill_price of this OrderHistoryListItem.


        :param avg_fill_price: The avg_fill_price of this OrderHistoryListItem.  # noqa: E501
        :type: str
        """

        self._avg_fill_price = avg_fill_price

    @property
    def commission(self):
        """Gets the commission of this OrderHistoryListItem.  # noqa: E501

        fee  # noqa: E501

        :return: The commission of this OrderHistoryListItem.  # noqa: E501
        :rtype: str
        """
        return self._commission

    @commission.setter
    def commission(self, commission):
        """Sets the commission of this OrderHistoryListItem.

        fee  # noqa: E501

        :param commission: The commission of this OrderHistoryListItem.  # noqa: E501
        :type: str
        """

        self._commission = commission

    @property
    def time_setup(self):
        """Gets the time_setup of this OrderHistoryListItem.  # noqa: E501


        :return: The time_setup of this OrderHistoryListItem.  # noqa: E501
        :rtype: int
        """
        return self._time_setup

    @time_setup.setter
    def time_setup(self, time_setup):
        """Sets the time_setup of this OrderHistoryListItem.


        :param time_setup: The time_setup of this OrderHistoryListItem.  # noqa: E501
        :type: int
        """

        self._time_setup = time_setup

    @property
    def time_done(self):
        """Gets the time_done of this OrderHistoryListItem.  # noqa: E501


        :return: The time_done of this OrderHistoryListItem.  # noqa: E501
        :rtype: int
        """
        return self._time_done

    @time_done.setter
    def time_done(self, time_done):
        """Sets the time_done of this OrderHistoryListItem.


        :param time_done: The time_done of this OrderHistoryListItem.  # noqa: E501
        :type: int
        """

        self._time_done = time_done

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, OrderHistoryListItem):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, OrderHistoryListItem):
            return True

        return self.to_dict() != other.to_dict()
