# coding: utf-8

"""
    Gate API

    Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.  # noqa: E501

    Contact: support@mail.gate.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from gate_api.configuration import Configuration


class P2pMerchantBooksPlaceBizPushOrderResponseDataRiskEvent(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'type': 'str',
        'title': 'str',
        'msg': 'str',
        'action': 'list[P2pMerchantBooksPlaceBizPushOrderResponseDataRiskEventAction]',
        'content_risk_type': 'str',
        'trade_tips': 'str',
        'auto_reply': 'str'
    }

    attribute_map = {
        'type': 'type',
        'title': 'title',
        'msg': 'msg',
        'action': 'action',
        'content_risk_type': 'content_risk_type',
        'trade_tips': 'trade_tips',
        'auto_reply': 'auto_reply'
    }

    def __init__(self, type=None, title=None, msg=None, action=None, content_risk_type=None, trade_tips=None, auto_reply=None, local_vars_configuration=None):  # noqa: E501
        # type: (str, str, str, list[P2pMerchantBooksPlaceBizPushOrderResponseDataRiskEventAction], str, str, str, Configuration) -> None
        """P2pMerchantBooksPlaceBizPushOrderResponseDataRiskEvent - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._type = None
        self._title = None
        self._msg = None
        self._action = None
        self._content_risk_type = None
        self._trade_tips = None
        self._auto_reply = None
        self.discriminator = None

        if type is not None:
            self.type = type
        if title is not None:
            self.title = title
        if msg is not None:
            self.msg = msg
        if action is not None:
            self.action = action
        if content_risk_type is not None:
            self.content_risk_type = content_risk_type
        if trade_tips is not None:
            self.trade_tips = trade_tips
        if auto_reply is not None:
            self.auto_reply = auto_reply

    @property
    def type(self):
        """Gets the type of this P2pMerchantBooksPlaceBizPushOrderResponseDataRiskEvent.  # noqa: E501

        Prompt display type  # noqa: E501

        :return: The type of this P2pMerchantBooksPlaceBizPushOrderResponseDataRiskEvent.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this P2pMerchantBooksPlaceBizPushOrderResponseDataRiskEvent.

        Prompt display type  # noqa: E501

        :param type: The type of this P2pMerchantBooksPlaceBizPushOrderResponseDataRiskEvent.  # noqa: E501
        :type: str
        """
        allowed_values = ["modal"]  # noqa: E501
        if self.local_vars_configuration.client_side_validation and type not in allowed_values:  # noqa: E501
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"  # noqa: E501
                .format(type, allowed_values)
            )

        self._type = type

    @property
    def title(self):
        """Gets the title of this P2pMerchantBooksPlaceBizPushOrderResponseDataRiskEvent.  # noqa: E501

        Risk control prompt title  # noqa: E501

        :return: The title of this P2pMerchantBooksPlaceBizPushOrderResponseDataRiskEvent.  # noqa: E501
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this P2pMerchantBooksPlaceBizPushOrderResponseDataRiskEvent.

        Risk control prompt title  # noqa: E501

        :param title: The title of this P2pMerchantBooksPlaceBizPushOrderResponseDataRiskEvent.  # noqa: E501
        :type: str
        """

        self._title = title

    @property
    def msg(self):
        """Gets the msg of this P2pMerchantBooksPlaceBizPushOrderResponseDataRiskEvent.  # noqa: E501

        Risk control prompt message generated based on the field that hit risk control  # noqa: E501

        :return: The msg of this P2pMerchantBooksPlaceBizPushOrderResponseDataRiskEvent.  # noqa: E501
        :rtype: str
        """
        return self._msg

    @msg.setter
    def msg(self, msg):
        """Sets the msg of this P2pMerchantBooksPlaceBizPushOrderResponseDataRiskEvent.

        Risk control prompt message generated based on the field that hit risk control  # noqa: E501

        :param msg: The msg of this P2pMerchantBooksPlaceBizPushOrderResponseDataRiskEvent.  # noqa: E501
        :type: str
        """

        self._msg = msg

    @property
    def action(self):
        """Gets the action of this P2pMerchantBooksPlaceBizPushOrderResponseDataRiskEvent.  # noqa: E501

        Available actions; advertisement content risk control only returns the close action  # noqa: E501

        :return: The action of this P2pMerchantBooksPlaceBizPushOrderResponseDataRiskEvent.  # noqa: E501
        :rtype: list[P2pMerchantBooksPlaceBizPushOrderResponseDataRiskEventAction]
        """
        return self._action

    @action.setter
    def action(self, action):
        """Sets the action of this P2pMerchantBooksPlaceBizPushOrderResponseDataRiskEvent.

        Available actions; advertisement content risk control only returns the close action  # noqa: E501

        :param action: The action of this P2pMerchantBooksPlaceBizPushOrderResponseDataRiskEvent.  # noqa: E501
        :type: list[P2pMerchantBooksPlaceBizPushOrderResponseDataRiskEventAction]
        """

        self._action = action

    @property
    def content_risk_type(self):
        """Gets the content_risk_type of this P2pMerchantBooksPlaceBizPushOrderResponseDataRiskEvent.  # noqa: E501

        Advertisement content field that hit risk control  # noqa: E501

        :return: The content_risk_type of this P2pMerchantBooksPlaceBizPushOrderResponseDataRiskEvent.  # noqa: E501
        :rtype: str
        """
        return self._content_risk_type

    @content_risk_type.setter
    def content_risk_type(self, content_risk_type):
        """Sets the content_risk_type of this P2pMerchantBooksPlaceBizPushOrderResponseDataRiskEvent.

        Advertisement content field that hit risk control  # noqa: E501

        :param content_risk_type: The content_risk_type of this P2pMerchantBooksPlaceBizPushOrderResponseDataRiskEvent.  # noqa: E501
        :type: str
        """
        allowed_values = ["trade_tips", "auto_reply", "trade_tips_auto_reply"]  # noqa: E501
        if self.local_vars_configuration.client_side_validation and content_risk_type not in allowed_values:  # noqa: E501
            raise ValueError(
                "Invalid value for `content_risk_type` ({0}), must be one of {1}"  # noqa: E501
                .format(content_risk_type, allowed_values)
            )

        self._content_risk_type = content_risk_type

    @property
    def trade_tips(self):
        """Gets the trade_tips of this P2pMerchantBooksPlaceBizPushOrderResponseDataRiskEvent.  # noqa: E501

        Prompt message returned when the trade terms hit risk control  # noqa: E501

        :return: The trade_tips of this P2pMerchantBooksPlaceBizPushOrderResponseDataRiskEvent.  # noqa: E501
        :rtype: str
        """
        return self._trade_tips

    @trade_tips.setter
    def trade_tips(self, trade_tips):
        """Sets the trade_tips of this P2pMerchantBooksPlaceBizPushOrderResponseDataRiskEvent.

        Prompt message returned when the trade terms hit risk control  # noqa: E501

        :param trade_tips: The trade_tips of this P2pMerchantBooksPlaceBizPushOrderResponseDataRiskEvent.  # noqa: E501
        :type: str
        """

        self._trade_tips = trade_tips

    @property
    def auto_reply(self):
        """Gets the auto_reply of this P2pMerchantBooksPlaceBizPushOrderResponseDataRiskEvent.  # noqa: E501

        Prompt message returned when the auto reply hits risk control  # noqa: E501

        :return: The auto_reply of this P2pMerchantBooksPlaceBizPushOrderResponseDataRiskEvent.  # noqa: E501
        :rtype: str
        """
        return self._auto_reply

    @auto_reply.setter
    def auto_reply(self, auto_reply):
        """Sets the auto_reply of this P2pMerchantBooksPlaceBizPushOrderResponseDataRiskEvent.

        Prompt message returned when the auto reply hits risk control  # noqa: E501

        :param auto_reply: The auto_reply of this P2pMerchantBooksPlaceBizPushOrderResponseDataRiskEvent.  # noqa: E501
        :type: str
        """

        self._auto_reply = auto_reply

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, P2pMerchantBooksPlaceBizPushOrderResponseDataRiskEvent):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, P2pMerchantBooksPlaceBizPushOrderResponseDataRiskEvent):
            return True

        return self.to_dict() != other.to_dict()
