# coding: utf-8

"""
    Gate API

    Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.  # noqa: E501

    Contact: support@mail.gate.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from gate_api.configuration import Configuration


class QuickRepaymentRequest(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'debt_currencies': 'list[str]',
        'available_currencies': 'list[str]'
    }

    attribute_map = {
        'debt_currencies': 'debt_currencies',
        'available_currencies': 'available_currencies'
    }

    def __init__(self, debt_currencies=None, available_currencies=None, local_vars_configuration=None):  # noqa: E501
        # type: (list[str], list[str], Configuration) -> None
        """QuickRepaymentRequest - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._debt_currencies = None
        self._available_currencies = None
        self.discriminator = None

        self.debt_currencies = debt_currencies
        self.available_currencies = available_currencies

    @property
    def debt_currencies(self):
        """Gets the debt_currencies of this QuickRepaymentRequest.  # noqa: E501

        Liability currencies  # noqa: E501

        :return: The debt_currencies of this QuickRepaymentRequest.  # noqa: E501
        :rtype: list[str]
        """
        return self._debt_currencies

    @debt_currencies.setter
    def debt_currencies(self, debt_currencies):
        """Sets the debt_currencies of this QuickRepaymentRequest.

        Liability currencies  # noqa: E501

        :param debt_currencies: The debt_currencies of this QuickRepaymentRequest.  # noqa: E501
        :type: list[str]
        """
        if self.local_vars_configuration.client_side_validation and debt_currencies is None:  # noqa: E501
            raise ValueError("Invalid value for `debt_currencies`, must not be `None`")  # noqa: E501

        self._debt_currencies = debt_currencies

    @property
    def available_currencies(self):
        """Gets the available_currencies of this QuickRepaymentRequest.  # noqa: E501

        Currencies to repay with  # noqa: E501

        :return: The available_currencies of this QuickRepaymentRequest.  # noqa: E501
        :rtype: list[str]
        """
        return self._available_currencies

    @available_currencies.setter
    def available_currencies(self, available_currencies):
        """Sets the available_currencies of this QuickRepaymentRequest.

        Currencies to repay with  # noqa: E501

        :param available_currencies: The available_currencies of this QuickRepaymentRequest.  # noqa: E501
        :type: list[str]
        """
        if self.local_vars_configuration.client_side_validation and available_currencies is None:  # noqa: E501
            raise ValueError("Invalid value for `available_currencies`, must not be `None`")  # noqa: E501

        self._available_currencies = available_currencies

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, QuickRepaymentRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, QuickRepaymentRequest):
            return True

        return self.to_dict() != other.to_dict()
