# coding: utf-8

"""
    Gate API

    Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.  # noqa: E501

    Contact: support@mail.gate.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from gate_api.configuration import Configuration


class RecommendV2Strategy(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'name': 'str',
        'priority': 'int',
        'schemes': 'list[RecommendV2Scheme]'
    }

    attribute_map = {
        'name': 'name',
        'priority': 'priority',
        'schemes': 'schemes'
    }

    def __init__(self, name=None, priority=None, schemes=None, local_vars_configuration=None):  # noqa: E501
        # type: (str, int, list[RecommendV2Scheme], Configuration) -> None
        """RecommendV2Strategy - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._name = None
        self._priority = None
        self._schemes = None
        self.discriminator = None

        self.name = name
        self.priority = priority
        self.schemes = schemes

    @property
    def name(self):
        """Gets the name of this RecommendV2Strategy.  # noqa: E501


        :return: The name of this RecommendV2Strategy.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this RecommendV2Strategy.


        :param name: The name of this RecommendV2Strategy.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and name is None:  # noqa: E501
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def priority(self):
        """Gets the priority of this RecommendV2Strategy.  # noqa: E501


        :return: The priority of this RecommendV2Strategy.  # noqa: E501
        :rtype: int
        """
        return self._priority

    @priority.setter
    def priority(self, priority):
        """Sets the priority of this RecommendV2Strategy.


        :param priority: The priority of this RecommendV2Strategy.  # noqa: E501
        :type: int
        """
        if self.local_vars_configuration.client_side_validation and priority is None:  # noqa: E501
            raise ValueError("Invalid value for `priority`, must not be `None`")  # noqa: E501

        self._priority = priority

    @property
    def schemes(self):
        """Gets the schemes of this RecommendV2Strategy.  # noqa: E501


        :return: The schemes of this RecommendV2Strategy.  # noqa: E501
        :rtype: list[RecommendV2Scheme]
        """
        return self._schemes

    @schemes.setter
    def schemes(self, schemes):
        """Sets the schemes of this RecommendV2Strategy.


        :param schemes: The schemes of this RecommendV2Strategy.  # noqa: E501
        :type: list[RecommendV2Scheme]
        """
        if self.local_vars_configuration.client_side_validation and schemes is None:  # noqa: E501
            raise ValueError("Invalid value for `schemes`, must not be `None`")  # noqa: E501

        self._schemes = schemes

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RecommendV2Strategy):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, RecommendV2Strategy):
            return True

        return self.to_dict() != other.to_dict()
