# coding: utf-8

"""
    Gate API

    Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.  # noqa: E501

    Contact: support@mail.gate.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from gate_api.configuration import Configuration


class SymbolDetailItem(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'symbol': 'str',
        'exchange': 'str',
        'exchange_desc': 'str',
        'quote_currency': 'str',
        'quote_currency_precision': 'int',
        'fx_rate': 'str',
        'symbol_desc': 'str',
        'category': 'str',
        'settlement_currency': 'str',
        'max_order_volume': 'str',
        'step_order_volume': 'str',
        'min_order_volume': 'str',
        'price_precision': 'int',
        'volume_precision': 'int',
        'is_ipo': 'bool',
        'ipo_price': 'str',
        'price_protection': 'str',
        'sell_price_protection': 'str',
        'buy_price_protection': 'str',
        'slippage_rate': 'str',
        'commission_rate': 'str',
        'trade_status': 'str',
        'trade_mode': 'int',
        'order_fill_timing': 'int',
        'symbol_descs': 'list[SymbolDetailItemSymbolDescs]',
        'icon_link': 'str'
    }

    attribute_map = {
        'symbol': 'symbol',
        'exchange': 'exchange',
        'exchange_desc': 'exchange_desc',
        'quote_currency': 'quote_currency',
        'quote_currency_precision': 'quote_currency_precision',
        'fx_rate': 'fx_rate',
        'symbol_desc': 'symbol_desc',
        'category': 'category',
        'settlement_currency': 'settlement_currency',
        'max_order_volume': 'max_order_volume',
        'step_order_volume': 'step_order_volume',
        'min_order_volume': 'min_order_volume',
        'price_precision': 'price_precision',
        'volume_precision': 'volume_precision',
        'is_ipo': 'is_ipo',
        'ipo_price': 'ipo_price',
        'price_protection': 'price_protection',
        'sell_price_protection': 'sell_price_protection',
        'buy_price_protection': 'buy_price_protection',
        'slippage_rate': 'slippage_rate',
        'commission_rate': 'commission_rate',
        'trade_status': 'trade_status',
        'trade_mode': 'trade_mode',
        'order_fill_timing': 'order_fill_timing',
        'symbol_descs': 'symbol_descs',
        'icon_link': 'icon_link'
    }

    def __init__(self, symbol=None, exchange=None, exchange_desc=None, quote_currency=None, quote_currency_precision=None, fx_rate=None, symbol_desc=None, category=None, settlement_currency=None, max_order_volume=None, step_order_volume=None, min_order_volume=None, price_precision=None, volume_precision=None, is_ipo=None, ipo_price=None, price_protection=None, sell_price_protection=None, buy_price_protection=None, slippage_rate=None, commission_rate=None, trade_status=None, trade_mode=None, order_fill_timing=None, symbol_descs=None, icon_link=None, local_vars_configuration=None):  # noqa: E501
        # type: (str, str, str, str, int, str, str, str, str, str, str, str, int, int, bool, str, str, str, str, str, str, str, int, int, list[SymbolDetailItemSymbolDescs], str, Configuration) -> None
        """SymbolDetailItem - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._symbol = None
        self._exchange = None
        self._exchange_desc = None
        self._quote_currency = None
        self._quote_currency_precision = None
        self._fx_rate = None
        self._symbol_desc = None
        self._category = None
        self._settlement_currency = None
        self._max_order_volume = None
        self._step_order_volume = None
        self._min_order_volume = None
        self._price_precision = None
        self._volume_precision = None
        self._is_ipo = None
        self._ipo_price = None
        self._price_protection = None
        self._sell_price_protection = None
        self._buy_price_protection = None
        self._slippage_rate = None
        self._commission_rate = None
        self._trade_status = None
        self._trade_mode = None
        self._order_fill_timing = None
        self._symbol_descs = None
        self._icon_link = None
        self.discriminator = None

        if symbol is not None:
            self.symbol = symbol
        if exchange is not None:
            self.exchange = exchange
        if exchange_desc is not None:
            self.exchange_desc = exchange_desc
        if quote_currency is not None:
            self.quote_currency = quote_currency
        if quote_currency_precision is not None:
            self.quote_currency_precision = quote_currency_precision
        if fx_rate is not None:
            self.fx_rate = fx_rate
        if symbol_desc is not None:
            self.symbol_desc = symbol_desc
        if category is not None:
            self.category = category
        if settlement_currency is not None:
            self.settlement_currency = settlement_currency
        if max_order_volume is not None:
            self.max_order_volume = max_order_volume
        if step_order_volume is not None:
            self.step_order_volume = step_order_volume
        if min_order_volume is not None:
            self.min_order_volume = min_order_volume
        if price_precision is not None:
            self.price_precision = price_precision
        if volume_precision is not None:
            self.volume_precision = volume_precision
        if is_ipo is not None:
            self.is_ipo = is_ipo
        if ipo_price is not None:
            self.ipo_price = ipo_price
        if price_protection is not None:
            self.price_protection = price_protection
        if sell_price_protection is not None:
            self.sell_price_protection = sell_price_protection
        if buy_price_protection is not None:
            self.buy_price_protection = buy_price_protection
        if slippage_rate is not None:
            self.slippage_rate = slippage_rate
        if commission_rate is not None:
            self.commission_rate = commission_rate
        if trade_status is not None:
            self.trade_status = trade_status
        if trade_mode is not None:
            self.trade_mode = trade_mode
        if order_fill_timing is not None:
            self.order_fill_timing = order_fill_timing
        if symbol_descs is not None:
            self.symbol_descs = symbol_descs
        if icon_link is not None:
            self.icon_link = icon_link

    @property
    def symbol(self):
        """Gets the symbol of this SymbolDetailItem.  # noqa: E501


        :return: The symbol of this SymbolDetailItem.  # noqa: E501
        :rtype: str
        """
        return self._symbol

    @symbol.setter
    def symbol(self, symbol):
        """Sets the symbol of this SymbolDetailItem.


        :param symbol: The symbol of this SymbolDetailItem.  # noqa: E501
        :type: str
        """

        self._symbol = symbol

    @property
    def exchange(self):
        """Gets the exchange of this SymbolDetailItem.  # noqa: E501

        Exchange, supports us, hk, and kr  # noqa: E501

        :return: The exchange of this SymbolDetailItem.  # noqa: E501
        :rtype: str
        """
        return self._exchange

    @exchange.setter
    def exchange(self, exchange):
        """Sets the exchange of this SymbolDetailItem.

        Exchange, supports us, hk, and kr  # noqa: E501

        :param exchange: The exchange of this SymbolDetailItem.  # noqa: E501
        :type: str
        """
        allowed_values = ["us", "hk", "kr"]  # noqa: E501
        if self.local_vars_configuration.client_side_validation and exchange not in allowed_values:  # noqa: E501
            raise ValueError(
                "Invalid value for `exchange` ({0}), must be one of {1}"  # noqa: E501
                .format(exchange, allowed_values)
            )

        self._exchange = exchange

    @property
    def exchange_desc(self):
        """Gets the exchange_desc of this SymbolDetailItem.  # noqa: E501


        :return: The exchange_desc of this SymbolDetailItem.  # noqa: E501
        :rtype: str
        """
        return self._exchange_desc

    @exchange_desc.setter
    def exchange_desc(self, exchange_desc):
        """Sets the exchange_desc of this SymbolDetailItem.


        :param exchange_desc: The exchange_desc of this SymbolDetailItem.  # noqa: E501
        :type: str
        """

        self._exchange_desc = exchange_desc

    @property
    def quote_currency(self):
        """Gets the quote_currency of this SymbolDetailItem.  # noqa: E501


        :return: The quote_currency of this SymbolDetailItem.  # noqa: E501
        :rtype: str
        """
        return self._quote_currency

    @quote_currency.setter
    def quote_currency(self, quote_currency):
        """Sets the quote_currency of this SymbolDetailItem.


        :param quote_currency: The quote_currency of this SymbolDetailItem.  # noqa: E501
        :type: str
        """

        self._quote_currency = quote_currency

    @property
    def quote_currency_precision(self):
        """Gets the quote_currency_precision of this SymbolDetailItem.  # noqa: E501


        :return: The quote_currency_precision of this SymbolDetailItem.  # noqa: E501
        :rtype: int
        """
        return self._quote_currency_precision

    @quote_currency_precision.setter
    def quote_currency_precision(self, quote_currency_precision):
        """Sets the quote_currency_precision of this SymbolDetailItem.


        :param quote_currency_precision: The quote_currency_precision of this SymbolDetailItem.  # noqa: E501
        :type: int
        """

        self._quote_currency_precision = quote_currency_precision

    @property
    def fx_rate(self):
        """Gets the fx_rate of this SymbolDetailItem.  # noqa: E501

        Quote currency to USD exchange rate  # noqa: E501

        :return: The fx_rate of this SymbolDetailItem.  # noqa: E501
        :rtype: str
        """
        return self._fx_rate

    @fx_rate.setter
    def fx_rate(self, fx_rate):
        """Sets the fx_rate of this SymbolDetailItem.

        Quote currency to USD exchange rate  # noqa: E501

        :param fx_rate: The fx_rate of this SymbolDetailItem.  # noqa: E501
        :type: str
        """

        self._fx_rate = fx_rate

    @property
    def symbol_desc(self):
        """Gets the symbol_desc of this SymbolDetailItem.  # noqa: E501


        :return: The symbol_desc of this SymbolDetailItem.  # noqa: E501
        :rtype: str
        """
        return self._symbol_desc

    @symbol_desc.setter
    def symbol_desc(self, symbol_desc):
        """Sets the symbol_desc of this SymbolDetailItem.


        :param symbol_desc: The symbol_desc of this SymbolDetailItem.  # noqa: E501
        :type: str
        """

        self._symbol_desc = symbol_desc

    @property
    def category(self):
        """Gets the category of this SymbolDetailItem.  # noqa: E501


        :return: The category of this SymbolDetailItem.  # noqa: E501
        :rtype: str
        """
        return self._category

    @category.setter
    def category(self, category):
        """Sets the category of this SymbolDetailItem.


        :param category: The category of this SymbolDetailItem.  # noqa: E501
        :type: str
        """

        self._category = category

    @property
    def settlement_currency(self):
        """Gets the settlement_currency of this SymbolDetailItem.  # noqa: E501


        :return: The settlement_currency of this SymbolDetailItem.  # noqa: E501
        :rtype: str
        """
        return self._settlement_currency

    @settlement_currency.setter
    def settlement_currency(self, settlement_currency):
        """Sets the settlement_currency of this SymbolDetailItem.


        :param settlement_currency: The settlement_currency of this SymbolDetailItem.  # noqa: E501
        :type: str
        """

        self._settlement_currency = settlement_currency

    @property
    def max_order_volume(self):
        """Gets the max_order_volume of this SymbolDetailItem.  # noqa: E501


        :return: The max_order_volume of this SymbolDetailItem.  # noqa: E501
        :rtype: str
        """
        return self._max_order_volume

    @max_order_volume.setter
    def max_order_volume(self, max_order_volume):
        """Sets the max_order_volume of this SymbolDetailItem.


        :param max_order_volume: The max_order_volume of this SymbolDetailItem.  # noqa: E501
        :type: str
        """

        self._max_order_volume = max_order_volume

    @property
    def step_order_volume(self):
        """Gets the step_order_volume of this SymbolDetailItem.  # noqa: E501


        :return: The step_order_volume of this SymbolDetailItem.  # noqa: E501
        :rtype: str
        """
        return self._step_order_volume

    @step_order_volume.setter
    def step_order_volume(self, step_order_volume):
        """Sets the step_order_volume of this SymbolDetailItem.


        :param step_order_volume: The step_order_volume of this SymbolDetailItem.  # noqa: E501
        :type: str
        """

        self._step_order_volume = step_order_volume

    @property
    def min_order_volume(self):
        """Gets the min_order_volume of this SymbolDetailItem.  # noqa: E501


        :return: The min_order_volume of this SymbolDetailItem.  # noqa: E501
        :rtype: str
        """
        return self._min_order_volume

    @min_order_volume.setter
    def min_order_volume(self, min_order_volume):
        """Sets the min_order_volume of this SymbolDetailItem.


        :param min_order_volume: The min_order_volume of this SymbolDetailItem.  # noqa: E501
        :type: str
        """

        self._min_order_volume = min_order_volume

    @property
    def price_precision(self):
        """Gets the price_precision of this SymbolDetailItem.  # noqa: E501

        Price precision  # noqa: E501

        :return: The price_precision of this SymbolDetailItem.  # noqa: E501
        :rtype: int
        """
        return self._price_precision

    @price_precision.setter
    def price_precision(self, price_precision):
        """Sets the price_precision of this SymbolDetailItem.

        Price precision  # noqa: E501

        :param price_precision: The price_precision of this SymbolDetailItem.  # noqa: E501
        :type: int
        """

        self._price_precision = price_precision

    @property
    def volume_precision(self):
        """Gets the volume_precision of this SymbolDetailItem.  # noqa: E501


        :return: The volume_precision of this SymbolDetailItem.  # noqa: E501
        :rtype: int
        """
        return self._volume_precision

    @volume_precision.setter
    def volume_precision(self, volume_precision):
        """Sets the volume_precision of this SymbolDetailItem.


        :param volume_precision: The volume_precision of this SymbolDetailItem.  # noqa: E501
        :type: int
        """

        self._volume_precision = volume_precision

    @property
    def is_ipo(self):
        """Gets the is_ipo of this SymbolDetailItem.  # noqa: E501


        :return: The is_ipo of this SymbolDetailItem.  # noqa: E501
        :rtype: bool
        """
        return self._is_ipo

    @is_ipo.setter
    def is_ipo(self, is_ipo):
        """Sets the is_ipo of this SymbolDetailItem.


        :param is_ipo: The is_ipo of this SymbolDetailItem.  # noqa: E501
        :type: bool
        """

        self._is_ipo = is_ipo

    @property
    def ipo_price(self):
        """Gets the ipo_price of this SymbolDetailItem.  # noqa: E501


        :return: The ipo_price of this SymbolDetailItem.  # noqa: E501
        :rtype: str
        """
        return self._ipo_price

    @ipo_price.setter
    def ipo_price(self, ipo_price):
        """Sets the ipo_price of this SymbolDetailItem.


        :param ipo_price: The ipo_price of this SymbolDetailItem.  # noqa: E501
        :type: str
        """

        self._ipo_price = ipo_price

    @property
    def price_protection(self):
        """Gets the price_protection of this SymbolDetailItem.  # noqa: E501


        :return: The price_protection of this SymbolDetailItem.  # noqa: E501
        :rtype: str
        """
        return self._price_protection

    @price_protection.setter
    def price_protection(self, price_protection):
        """Sets the price_protection of this SymbolDetailItem.


        :param price_protection: The price_protection of this SymbolDetailItem.  # noqa: E501
        :type: str
        """

        self._price_protection = price_protection

    @property
    def sell_price_protection(self):
        """Gets the sell_price_protection of this SymbolDetailItem.  # noqa: E501


        :return: The sell_price_protection of this SymbolDetailItem.  # noqa: E501
        :rtype: str
        """
        return self._sell_price_protection

    @sell_price_protection.setter
    def sell_price_protection(self, sell_price_protection):
        """Sets the sell_price_protection of this SymbolDetailItem.


        :param sell_price_protection: The sell_price_protection of this SymbolDetailItem.  # noqa: E501
        :type: str
        """

        self._sell_price_protection = sell_price_protection

    @property
    def buy_price_protection(self):
        """Gets the buy_price_protection of this SymbolDetailItem.  # noqa: E501


        :return: The buy_price_protection of this SymbolDetailItem.  # noqa: E501
        :rtype: str
        """
        return self._buy_price_protection

    @buy_price_protection.setter
    def buy_price_protection(self, buy_price_protection):
        """Sets the buy_price_protection of this SymbolDetailItem.


        :param buy_price_protection: The buy_price_protection of this SymbolDetailItem.  # noqa: E501
        :type: str
        """

        self._buy_price_protection = buy_price_protection

    @property
    def slippage_rate(self):
        """Gets the slippage_rate of this SymbolDetailItem.  # noqa: E501


        :return: The slippage_rate of this SymbolDetailItem.  # noqa: E501
        :rtype: str
        """
        return self._slippage_rate

    @slippage_rate.setter
    def slippage_rate(self, slippage_rate):
        """Sets the slippage_rate of this SymbolDetailItem.


        :param slippage_rate: The slippage_rate of this SymbolDetailItem.  # noqa: E501
        :type: str
        """

        self._slippage_rate = slippage_rate

    @property
    def commission_rate(self):
        """Gets the commission_rate of this SymbolDetailItem.  # noqa: E501

        Fee Rate  # noqa: E501

        :return: The commission_rate of this SymbolDetailItem.  # noqa: E501
        :rtype: str
        """
        return self._commission_rate

    @commission_rate.setter
    def commission_rate(self, commission_rate):
        """Sets the commission_rate of this SymbolDetailItem.

        Fee Rate  # noqa: E501

        :param commission_rate: The commission_rate of this SymbolDetailItem.  # noqa: E501
        :type: str
        """

        self._commission_rate = commission_rate

    @property
    def trade_status(self):
        """Gets the trade_status of this SymbolDetailItem.  # noqa: E501

        Trading status. - pre_market: Pre-market. - open: Regular trading session. - post_market: Post-market. - closed: Market closed. - gt_lp: GT LP session.  # noqa: E501

        :return: The trade_status of this SymbolDetailItem.  # noqa: E501
        :rtype: str
        """
        return self._trade_status

    @trade_status.setter
    def trade_status(self, trade_status):
        """Sets the trade_status of this SymbolDetailItem.

        Trading status. - pre_market: Pre-market. - open: Regular trading session. - post_market: Post-market. - closed: Market closed. - gt_lp: GT LP session.  # noqa: E501

        :param trade_status: The trade_status of this SymbolDetailItem.  # noqa: E501
        :type: str
        """
        allowed_values = ["pre_market", "open", "post_market", "closed", "gt_lp"]  # noqa: E501
        if self.local_vars_configuration.client_side_validation and trade_status not in allowed_values:  # noqa: E501
            raise ValueError(
                "Invalid value for `trade_status` ({0}), must be one of {1}"  # noqa: E501
                .format(trade_status, allowed_values)
            )

        self._trade_status = trade_status

    @property
    def trade_mode(self):
        """Gets the trade_mode of this SymbolDetailItem.  # noqa: E501

        Current session trading mode. - 0: Trading disabled. - 1: Buy only. - 2: Sell only. - 4: Buy and sell supported.  # noqa: E501

        :return: The trade_mode of this SymbolDetailItem.  # noqa: E501
        :rtype: int
        """
        return self._trade_mode

    @trade_mode.setter
    def trade_mode(self, trade_mode):
        """Sets the trade_mode of this SymbolDetailItem.

        Current session trading mode. - 0: Trading disabled. - 1: Buy only. - 2: Sell only. - 4: Buy and sell supported.  # noqa: E501

        :param trade_mode: The trade_mode of this SymbolDetailItem.  # noqa: E501
        :type: int
        """
        allowed_values = [0, 1, 2, 4]  # noqa: E501
        if self.local_vars_configuration.client_side_validation and trade_mode not in allowed_values:  # noqa: E501
            raise ValueError(
                "Invalid value for `trade_mode` ({0}), must be one of {1}"  # noqa: E501
                .format(trade_mode, allowed_values)
            )

        self._trade_mode = trade_mode

    @property
    def order_fill_timing(self):
        """Gets the order_fill_timing of this SymbolDetailItem.  # noqa: E501

        Order fill timing (1=immediate, 2=after pre-market opens, 3=after regular session opens)  # noqa: E501

        :return: The order_fill_timing of this SymbolDetailItem.  # noqa: E501
        :rtype: int
        """
        return self._order_fill_timing

    @order_fill_timing.setter
    def order_fill_timing(self, order_fill_timing):
        """Sets the order_fill_timing of this SymbolDetailItem.

        Order fill timing (1=immediate, 2=after pre-market opens, 3=after regular session opens)  # noqa: E501

        :param order_fill_timing: The order_fill_timing of this SymbolDetailItem.  # noqa: E501
        :type: int
        """
        allowed_values = [1, 2, 3]  # noqa: E501
        if self.local_vars_configuration.client_side_validation and order_fill_timing not in allowed_values:  # noqa: E501
            raise ValueError(
                "Invalid value for `order_fill_timing` ({0}), must be one of {1}"  # noqa: E501
                .format(order_fill_timing, allowed_values)
            )

        self._order_fill_timing = order_fill_timing

    @property
    def symbol_descs(self):
        """Gets the symbol_descs of this SymbolDetailItem.  # noqa: E501


        :return: The symbol_descs of this SymbolDetailItem.  # noqa: E501
        :rtype: list[SymbolDetailItemSymbolDescs]
        """
        return self._symbol_descs

    @symbol_descs.setter
    def symbol_descs(self, symbol_descs):
        """Sets the symbol_descs of this SymbolDetailItem.


        :param symbol_descs: The symbol_descs of this SymbolDetailItem.  # noqa: E501
        :type: list[SymbolDetailItemSymbolDescs]
        """

        self._symbol_descs = symbol_descs

    @property
    def icon_link(self):
        """Gets the icon_link of this SymbolDetailItem.  # noqa: E501


        :return: The icon_link of this SymbolDetailItem.  # noqa: E501
        :rtype: str
        """
        return self._icon_link

    @icon_link.setter
    def icon_link(self, icon_link):
        """Sets the icon_link of this SymbolDetailItem.


        :param icon_link: The icon_link of this SymbolDetailItem.  # noqa: E501
        :type: str
        """

        self._icon_link = icon_link

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SymbolDetailItem):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, SymbolDetailItem):
            return True

        return self.to_dict() != other.to_dict()
