# coding: utf-8

"""
    Gate API

    Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.  # noqa: E501

    Contact: support@mail.gate.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from gate_api.configuration import Configuration


class TransactionListData(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'total': 'int',
        'total_page': 'int',
        'list': 'list[TransactionListDataList]'
    }

    attribute_map = {
        'total': 'total',
        'total_page': 'total_page',
        'list': 'list'
    }

    def __init__(self, total=None, total_page=None, list=None, local_vars_configuration=None):  # noqa: E501
        # type: (int, int, list[TransactionListDataList], Configuration) -> None
        """TransactionListData - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._total = None
        self._total_page = None
        self._list = None
        self.discriminator = None

        if total is not None:
            self.total = total
        if total_page is not None:
            self.total_page = total_page
        if list is not None:
            self.list = list

    @property
    def total(self):
        """Gets the total of this TransactionListData.  # noqa: E501

        Total Records  # noqa: E501

        :return: The total of this TransactionListData.  # noqa: E501
        :rtype: int
        """
        return self._total

    @total.setter
    def total(self, total):
        """Sets the total of this TransactionListData.

        Total Records  # noqa: E501

        :param total: The total of this TransactionListData.  # noqa: E501
        :type: int
        """

        self._total = total

    @property
    def total_page(self):
        """Gets the total_page of this TransactionListData.  # noqa: E501

        Total pages  # noqa: E501

        :return: The total_page of this TransactionListData.  # noqa: E501
        :rtype: int
        """
        return self._total_page

    @total_page.setter
    def total_page(self, total_page):
        """Sets the total_page of this TransactionListData.

        Total pages  # noqa: E501

        :param total_page: The total_page of this TransactionListData.  # noqa: E501
        :type: int
        """

        self._total_page = total_page

    @property
    def list(self):
        """Gets the list of this TransactionListData.  # noqa: E501

        Record List  # noqa: E501

        :return: The list of this TransactionListData.  # noqa: E501
        :rtype: list[TransactionListDataList]
        """
        return self._list

    @list.setter
    def list(self, list):
        """Sets the list of this TransactionListData.

        Record List  # noqa: E501

        :param list: The list of this TransactionListData.  # noqa: E501
        :type: list[TransactionListDataList]
        """

        self._list = list

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TransactionListData):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, TransactionListData):
            return True

        return self.to_dict() != other.to_dict()
