# coding: utf-8

"""
    Gate API

    Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.  # noqa: E501

    Contact: support@mail.gate.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from gate_api.configuration import Configuration


class UnifiedQuickRepayRepaidInfo(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'currency': 'str',
        'repaid': 'str',
        'left': 'str'
    }

    attribute_map = {
        'currency': 'currency',
        'repaid': 'repaid',
        'left': 'left'
    }

    def __init__(self, currency=None, repaid=None, left=None, local_vars_configuration=None):  # noqa: E501
        # type: (str, str, str, Configuration) -> None
        """UnifiedQuickRepayRepaidInfo - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._currency = None
        self._repaid = None
        self._left = None
        self.discriminator = None

        self.currency = currency
        self.repaid = repaid
        self.left = left

    @property
    def currency(self):
        """Gets the currency of this UnifiedQuickRepayRepaidInfo.  # noqa: E501

        Currency name  # noqa: E501

        :return: The currency of this UnifiedQuickRepayRepaidInfo.  # noqa: E501
        :rtype: str
        """
        return self._currency

    @currency.setter
    def currency(self, currency):
        """Sets the currency of this UnifiedQuickRepayRepaidInfo.

        Currency name  # noqa: E501

        :param currency: The currency of this UnifiedQuickRepayRepaidInfo.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and currency is None:  # noqa: E501
            raise ValueError("Invalid value for `currency`, must not be `None`")  # noqa: E501

        self._currency = currency

    @property
    def repaid(self):
        """Gets the repaid of this UnifiedQuickRepayRepaidInfo.  # noqa: E501

        Repaid amount  # noqa: E501

        :return: The repaid of this UnifiedQuickRepayRepaidInfo.  # noqa: E501
        :rtype: str
        """
        return self._repaid

    @repaid.setter
    def repaid(self, repaid):
        """Sets the repaid of this UnifiedQuickRepayRepaidInfo.

        Repaid amount  # noqa: E501

        :param repaid: The repaid of this UnifiedQuickRepayRepaidInfo.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and repaid is None:  # noqa: E501
            raise ValueError("Invalid value for `repaid`, must not be `None`")  # noqa: E501

        self._repaid = repaid

    @property
    def left(self):
        """Gets the left of this UnifiedQuickRepayRepaidInfo.  # noqa: E501

        Remaining liability amount  # noqa: E501

        :return: The left of this UnifiedQuickRepayRepaidInfo.  # noqa: E501
        :rtype: str
        """
        return self._left

    @left.setter
    def left(self, left):
        """Sets the left of this UnifiedQuickRepayRepaidInfo.

        Remaining liability amount  # noqa: E501

        :param left: The left of this UnifiedQuickRepayRepaidInfo.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and left is None:  # noqa: E501
            raise ValueError("Invalid value for `left`, must not be `None`")  # noqa: E501

        self._left = left

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UnifiedQuickRepayRepaidInfo):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, UnifiedQuickRepayRepaidInfo):
            return True

        return self.to_dict() != other.to_dict()
